### PR TITLE
Tasks 284-285: IMDB

### PR DESCRIPTION
**Pull request by Mihir3009**
1 Classification Task and 1 Answer Generation Task.

Please review.

### CODE REVIEW

**Review by swarooprm — COMMENTED** [review]
Looks good! Some comments:
1. Make sure that positive and negative labels are balanced in the data.
2. Similar tasks can be crated for the SST-2 dataset which is sort of out of distribution to IMDB. If you don't want to create those tasks, create an issue and someone can take it up.

**Comment by gkaramanolakis** [comment]
You can find SST-2 in the following pull request: [Task 363: SST2](https://github.com/allenai/natural-instructions-expansion/pull/195#issue-728166370)

**Comment by swarooprm** [comment]
> Looks good! Some comments:
> 
> 1. Make sure that positive and negative labels are balanced in the data.
> 2. Similar tasks can be crated for the SST-2 dataset which is sort of out of distribution to IMDB. If you don't want to create those tasks, create an issue and someone can take it up.

Can you address reviewer comments @Mihir3009 ?

**Comment by Mihir3009** [comment]
Resolved.

1. Positive: 3251, Negative: 3249 (Class instances) - balanced
2. For SST-2, we can create one more answer generation task similar to IMDB.

**Comment by Mihir3009** [comment]
> You can find SST-2 in the following pull request: [Task 363: SST2](https://github.com/allenai/natural-instructions-expansion/pull/195#issue-728166370)

Can you please add one answer generation task in your PR similar to IMDB? or I will do it or create a issue?

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
