### PR TITLE
task 104

### PR DESCRIPTION
**Pull request by amirrezamirzaei**
task 104 using  [semeval-2019 task 10](https://github.com/allenai/semeval-2019-task-10)

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! 

Looks good to me. 


I'll let @swarooprm make the merge call (especially if there is any other sub-task that can be generated based on this task).

**Review by swarooprm — CHANGES_REQUESTED** [review]
Looks good, some comments.
1. We already have categories like "mathematics", "algebra", "arithmetic". Don't add a new category, use one of these.
2. I see examples and instances are same in some cases, this should not happen. Make sure that positive examples and instances are not same.
3. [optional] you can create more tasks using these datasets. The same thing also works for your earlier task based on commonsenseQA. you can create more tasks there as well.

**Comment by danyaljj** [comment]
> [optional] you can create more tasks using these datasets. The same thing also works for your earlier task based on commonsenseQA. you can create more tasks there as well. 

Could you elaborate more on this ☝️, for this particular PR

**Comment by danyaljj** [comment]
@amirrezamirzaei after addressing the comments, please pull and merge with the main branch.

**Comment by swarooprm** [comment]
> > [optional] you can create more tasks using these datasets. The same thing also works for your earlier task based on commonsenseQA. you can create more tasks there as well.
> 
> Could you elaborate more on this ☝️, for this particular PR

Sure, for the semeval-2019 task 10, there could be 3 tasks based on the categories present there.
- Closed-vocabulary algebra
- Open-vocabulary algebra
- Geometry
etc...

In case of CommonsenseQA, there can be
- Question generation task
- Answer generation task
- Incorrect answer generation task
- helper tasks e.g. find the commonsenese category (table 3 in https://arxiv.org/pdf/1811.00937.pdf)

Similarly in Scruples, another possible task is finding who is wrong in anecdotes and there can be other tasks.

**Review by swarooprm — APPROVED** [review]
The tasks look good! You can create the suggested tasks in a different PR. I am merging these.

**Comment by swarooprm** [comment]
@amirrezamirzaei Please pull and merge with the main. Once tests pass and conflict gets resolved, I will merge.

**Comment by amirrezamirzaei** [comment]
@swarooprm I used both Closed-vocabulary algebra and Open-vocabulary algebra questions to create this task. should I break them into two tasks?

**Comment by swarooprm** [comment]
> @swarooprm I used both Closed-vocabulary algebra and Open-vocabulary algebra questions to create this task. should I break them into two tasks?

yes, you can actually since the skills required to solve each of the tasks are different. Feel free to create a new PR to update task 104 and the other new tasks.

**Pull request merged**
