### PR TITLE
Task 67-72: AbductiveNLI

### PR DESCRIPTION
**Pull request by aarunku5**
Created 6 tasks (4 answer generation, 2 classification)

### CODE REVIEW

**Comment by danyaljj** [comment]
FYI: Looks like your PR is failing the tests.

**Comment by aarunku5** [comment]
Sorry for the late reply! I've been traveling for the past week. Will fix it once I return on Tuesday, and resubmit.

**Comment by swarooprm** [comment]
Please pull and merge with the main branch. That should trigger the new automatic tests.

**Comment by danyaljj** [comment]
pinging the thread to make sure you have seen the comments above.

**Comment by aarunku5** [comment]
Yes, I think it's passing all the tests now?

**Comment by danyaljj** [comment]
Drop the `tasks/.DS_Store` file.

**Comment by danyaljj** [comment]
Reviewing the first task `task067_abductivenli_answer_generation`: 
 - For the source field, include a link to the paper. 
 - "an incomplete three-part story" ->  of a three-part story (drop "incomplete"); the story itself is complete, but what is given (beginning +ending) is "incomplete" 
 - "Your job is to complete the short story by writing a probable middle of the story that explains why the ending follows after the beginning and justify the created middle by describing the central message/theme of the story." -> simplify this, something along with this: Your job is to complete the story by writing a middle sentence that creates a seamless connection between the first sentence and the last sentence. 
 - "Input sentences must be short, have fewer than 10 words, and be simple as if narrating to a child." --> "Input" or output/generated? 
 - Not sure what this is saying: "The central message must be expressed as a general rule of thumb. For example: people don't like wearing soiled clothes."

Please apply these suggestions for the remaining tasks, wherever possible.

**Comment by aarunku5** [comment]
Made the changes over all tasks.

**Review by danyaljj — APPROVED** [review]
Two minor requests and it's good to go! 

- `task067_abductivenli_answer_generation` looks good! 
- `task068_abductivenli_incorrect_answer_generation` looks good to me! 
- `task069_abductivenli_classification`: be explicit that the output can be either `1` or `2` 
- `task070_abductivenli_incorrect_classification`: same issue as above (be explicit about the output) 
- `task071_abductivenli_answer_generation.json` looks good to me! 
- `task072_abductivenli_answer_generation.json` looks good to me!

**Comment by danyaljj** [comment]
@swarooprm feel free to merge when the changes updates are applied + you're happy.

**Comment by aarunku5** [comment]
Sure, made the update

**Comment by danyaljj** [comment]
Let's make it more clear:  `with output of 1 or 2` -> `by indicate 1 or 2 in the output` (or something that is more clear).

**Comment by aarunku5** [comment]
All right, have updated that as well.

**Comment by danyaljj** [comment]
@aarunku5 there is some feedback from crowd workers regarding your task(s), summarized here: 
https://github.com/allenai/natural-instructions-expansion/pull/276#issuecomment-942714679
Wondering if you can address the feedback?

**Comment by aarunku5** [comment]
Sure, will do it by tomorrow

**Comment by Palipoor** [comment]
@aarunku5 I have done a couple of changes, please check #447 and fix what is left. Thanks.

**Pull request merged**
