### PR TITLE
Tasks 469-472: from MRQA and hasPart KB datasets

### PR DESCRIPTION
**Pull request by Maitreyapatel**
@swarooprm Please refer to the tasks from NLP course assignments.

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/10

**Comment by danyaljj** [comment]
@jayavardhan3112 wondering if you can review this PR (in addition to the referenced reviews).

**Comment by jayavardhan3112** [comment]
In task469_mrqa_answer_generation, The output for some instances is a list with duplicate values, rather than only single value, 

In task470_mrqa_question_generation, please elaborate the definition

Please add the research paper link for all the tasks in the source.

Other than that I think it looks good.
Thanks

**Comment by Maitreyapatel** [comment]
@jayavardhan3112 Thanks for the suggestions. I have updated the files as you requested.
Please review them once again. And let me know your thoughts.

**Comment by jayavardhan3112** [comment]
> @jayavardhan3112 Thanks for the suggestions. I have updated the files as you requested.
> Please review them once again. And let me know your thoughts.

Looks good to me @Maitreyapatel , we can move ahead with the merge @swarooprm

**Comment by danyaljj** [comment]
Looks good, thanks!

**Pull request merged**
