### PR TITLE
Tasks 1168-1185 : Xcopa

### PR DESCRIPTION
**Pull request by amirrezamirzaei**
task 1168-1185 using [xcopa](https://github.com/cambridgeltl/xcopa)

### CODE REVIEW

**Comment by danyaljj** [comment]
@mishra-sid wondering if you can review this PR?

**Comment by mishra-sid** [comment]
@danyaljj Sure, I'll have a look tomorrow.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
> @danyaljj Sure, I'll have a look tomorrow.

@mishra-sid, wondering if you plan to review this PR?

**Comment by aarunku5** [comment]
> Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).


@amirrezamirzaei can you address this? Also, please update all your tasks to have the full name of the language in the input and output  language fields, not just the two-letter abbreviations.

**Pull request merged**
