### PR TITLE
Tasks 388-390: Torque

### PR DESCRIPTION
**Pull request by shailaja183**
1. task388_torque_event_detection.json | Given a passage, identify all events from it | Event Detection
2. task389_torque_generate_temporal_question.json | Given a passage, generate a temporal question | Question Generation
3. task390_torque_answer_temporal_question.json | Given a passage, a temporal question and a list of events in the passage, return a subset of event list that answers the given question | Answer Generation

### CODE REVIEW

**Comment by danyaljj** [comment]
@SavanDoshi wondering if you can review this PR?

**Comment by SavanDoshi** [comment]
> @SavanDoshi wondering if you can review this PR?

Yeah Sure. I will do it.

**Review by SavanDoshi — COMMENTED** [review]
Looks Good to me.

**Comment by danyaljj** [comment]
`tasks/task388_torque_event_detection.json`: 

 - "the goal is to identify all the events in that passage" -> So, when the output is a list of strings, we give full credit if the prediction matches at least one of the elements of the list. So, I think here we should say, "identify at exactly one event (any event) from the given passage" 


 `task390_torque_answer_temporal_question.json`: we should update this task too, according to the above intuition.

**Comment by shailaja183** [comment]
Makes sense! I have updated the description and positive/negative examples accordingly. 
If I understood correctly, there are no changes required in instances of task 388/390. 
Please review agian and let me know in case any changes are needed.

**Comment by shailaja183** [comment]
Closing this pull request as i accidentally committed changes on master branch. 
Creating new pull request due to merge conflicts.

**Pull request closed without merging**
