### PR TITLE
Tasks 595-599: MOCHA and CUAD Datasets

### PR DESCRIPTION
**Pull request by akhilkumargudipoodi**

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/23

**Comment by danyaljj** [comment]
In several places, you say:  "based on the paragraph that correspond to a phrase from the paragraph"?? Not sure what this means.

**Comment by swarooprm** [comment]
> In several places, you say: "based on the paragraph that correspond to a phrase from the paragraph"?? Not sure what this means.
@akhilkumargudipoodi, can you respond to reviewer comment and make the definition more clear?

**Comment by akhilkumargudipoodi** [comment]
Sure Swaroop, will make the changes to the definition by tomorrow.

**Comment by akhilkumargudipoodi** [comment]
@swarooprm I have modified the definitions for the tasks and made them more clear. Please let me know, in case of any concerns.

**Comment by aarunku5** [comment]
Thanks, couple of minor changes:
596-
Modify P2's explanation and include the phrase from the passage that answers the question.
598- 
Add a line to the definition stating that if multiple indices must be used to answer the question, the output should be a common separated list of indices.

**Comment by akhilkumargudipoodi** [comment]
@aarunku5 I have made the changes suggested but I'm not able to push the changes to the repo. Been getting the following error message: 
image

Might be due to the case that Master has been merged with my branch today in the morning.

Please let me know, how I can proceed forward.

**Comment by danyaljj** [comment]
You need to pull and/or merge with the main branch: 
https://stackoverflow.com/questions/8901973/why-git-push-is-rejected-git-pull-doesnt-help

**Comment by swarooprm** [comment]
> @aarunku5 I have made the changes suggested but I'm not able to push the changes to the repo. Been getting the following error message: image
> 
> Might be due to the case that Master has been merged with my branch today in the morning.
> 
> Please let me know, how I can proceed forward.

@akhilkumargudipoodi, any update?

**Comment by swarooprm** [comment]
@akhilkumargudipoodi, add the following to all files and answer the minor reviewer comments, and this PR is good to go then.
"Input_language": [
        "English"
    ],
    "Output_language": [
        "English"
    ],
    "Instruction_language": [
        "English"
    ],

**Comment by swarooprm** [comment]
> @akhilkumargudipoodi, add the following to all files and answer the minor reviewer comments, and this PR is good to go then. "Input_language": [ "English" ], "Output_language": [ "English" ], "Instruction_language": [ "English" ],

Can you do it soon so that we can go ahead with this PR @akhilkumargudipoodi ?

**Comment by akhilkumargudipoodi** [comment]
@swarooprm Have addressed all the suggestions and have also included the following "Input_language": [ "English" ], "Output_language": [ "English" ], "Instruction_language": [ "English" ]" in all the JSONs

**Pull request merged**
