### PR TITLE
Tasks 838-842: cdt & para_pdt Datasets

### PR DESCRIPTION
**Pull request by akhileshamara**
Reviews: https://github.com/swarooprm/CSE576HW/pull/38

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks, looks good to me!
Leaving it here for @swarooprm to give it a 2nd look.

**Comment by danyaljj** [comment]
Looks good! 
One suggestion though:  Densify the instructions a tad bit? 
```
In this task, you are given a text from polish tweets. Your task is to classify given tweet text into two categories
```
can be phrase as: 
```
Given a text from polish tweets, classify given tweet text ...
```
and similarly for the rest of the tasks. 

@swarooprm will give it a 2nd look before merging it.

**Comment by swarooprm** [comment]
@akhileshamara, task 839 has some problems.
First: "Does the tweet contains cyberbullying (harmful) content?"-->"Does the tweet contain cyberbullying (harmful) content?"

Second: When I said multiple prompts, I was asking to have two prompts like this:
(i) Does the tweet contain cyberbullying (harmful) content?
(ii) Is the tweet free of any cyberbullying (harmful) content?
Not positive, negative tweet etc.
Also, these should be present across all instances, not just positive and negative examples.
It's pretty easy to fix automatically. Wherever you replace prompt1 with prompt2, the label will flip (say from 'yes' to 'no')

Let me know once you fix.

**Comment by danyaljj** [comment]
@akhileshamara just checking if you can address the above suggestions?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by akhileshamara** [comment]
@danyaljj I will try to address these issues by end of this week. Thanks for understanding.

**Comment by swarooprm** [comment]
> @danyaljj I will try to address these issues by end of this week. Thanks for understanding.

@akhileshamara, could you address reviewer comments?

**Comment by swarooprm** [comment]
> > @danyaljj I will try to address these issues by end of this week. Thanks for understanding.
> 
> @akhileshamara, could you address reviewer comments?

@akhileshamara, a gentle reminder.

**Comment by akhileshamara** [comment]
@swarooprm I have made changes based on the review comments given. Please let check and let me know. Thanks and sorry for the delay.

**Pull request merged**
