### PR TITLE
Task 1285-1307: Keypoint Matching - 23 topics

### PR DESCRIPTION
**Pull request by ashok-arjun**
Dataset = https://github.com/IBM/KPA_2021_shared_task

There are overall 23 topics in the dataset. Each of the topics have many instances of arguments and keypoints, and if they match.

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi!
Can you please ensure all the tasks have balanced labels? I checked a couple of them and they didn't have.

**Comment by ashok-arjun** [comment]
@Palipoor Thanks for letting me know that - you were right, some had more False instances.

Now I've balanced them such that equal True and False instances are present.

**Comment by Palipoor** [comment]
I think the tasks look good! Can you add the category to the readme file as well? Thanks.

**Comment by ashok-arjun** [comment]
> I think the tasks look good! Can you add the category to the readme file as well? Thanks.

Yes - all tasks are in the README file as well, with the topic.

**An example:**

`task1306_kpa_keypoint_matching_space_exploration_topic` | Given an argument and a keypoint under the topic "We should subsidize space exploration", answer if the keypoint summarizes the argument

**Comment by ashok-arjun** [comment]
@Palipoor Please let me know if there's any other change to be made

**Comment by Palipoor** [comment]
Hi! Please change the categories to "Classification" in all tasks, 
and in the Readme file, see other tasks: They have title | short description | category.
Please add the third column to your tasks as well.

**Comment by ashok-arjun** [comment]
Thanks! I've done the changes @Palipoor !

**Comment by ashok-arjun** [comment]
The tests are failing because they are based on the new `src/test_all_.py` file, due to which all the previously upload `json` files (not only from this PR) are being treated invalid

**Comment by Palipoor** [comment]
> The tests are failing because they are based on the new `src/test_all_.py` file, due to which all the previously upload `json` files (not only from this PR) are being treated invalid

Yes, can you please add these to all your tasks?   

```
    "Input_language": [
        "English"
    ],
    "Output_language": [
        "English"
    ],
    "Instruction_language": [
        "English"
    ]
```

**Comment by ashok-arjun** [comment]
> > The tests are failing because they are based on the new `src/test_all_.py` file, due to which all the previously upload `json` files (not only from this PR) are being treated invalid
> 
> Yes, can you please add these to all your tasks?
> 
> ```
>     "Input_language": [
>         "English"
>     ],
>     "Output_language": [
>         "English"
>     ],
>     "Instruction_language": [
>         "English"
>     ]
> ```

I've added these to all the files in the given format. 

https://github.com/allenai/natural-instructions-expansion/blob/988b1175333936fe4a848c22101b147902212fa1/tasks/task1285_kpa_keypoint_matching_assisted_suicide_topic.json#L12-L20

**Pull request merged**
