### PR TITLE
Task 379: AGNews Topic Classification

### PR DESCRIPTION
**Pull request by gkaramanolakis**
Given a news article, classify the article's topic to four classes ('World', 'Sports', 'Business', 'Sci/Tech')

### CODE REVIEW

**Comment by swarooprm** [comment]
Please rename your task to Task379 as tasks till task378 is covered in the previous PR

**Comment by gkaramanolakis** [comment]
> Please rename your task to Task379 as tasks till task378 is covered in the previous PR

Done, thanks!

**Comment by danyaljj** [comment]
Thanks! Looks good to me! 

Leaving it here for @swarooprm to review before merging.

**Review by swarooprm — APPROVED** [review]
LGTM!
I am assuming class labels are almost balanced, if not please fix it in a new PR. 
Also, you can create more tasks from this dataset.

**Comment by swarooprm** [comment]
Is this true? @gkaramanolakis 
> I am assuming class labels are almost balanced, if not please fix it in a new PR.

**Comment by gkaramanolakis** [comment]
> Is this true? @gkaramanolakis
> 
> > I am assuming class labels are almost balanced, if not please fix it in a new PR.

Yes, classes labels are almost balanced: 
Business    1667
Sports      1637
Sci/Tech    1622
World       1574

Do you have specific ideas on what extra tasks to create using this dataset? (I am planning to add more topic classification tasks but using other datasets, e.g., product reviews.)

**Pull request merged**
