### PR TITLE
Task 493-496: Amazon Polarity and Semeval

### PR DESCRIPTION
**Pull request by SavanDoshi**
`task493_review_polarity_classification` | Classify amazon review into positive or negative | Classification
`task494_review_polarity_answer_generation` | Given pair of amazon review and polarity, generate True or False when a review matches polarity | Answer Generation

`task495_semeval_headline_classification` | Classify edited news headlines into funny and not funny | Classification
`task496_semeval_answer_generation` | Generate answer yes or no based on given edited sentence and label | Answer Generation

### CODE REVIEW

**Comment by swarooprm** [comment]
Review: https://github.com/swarooprm/CSE576HW/pull/9

**Comment by danyaljj** [comment]
@fsiar wondering if you can help review this PR?

**Comment by fsiar** [comment]
Hi, Thank you for submitting this task. 
Great job. But I would like to ask for: 
1- typo and grammar check.
I am not a native English to complete edit this task. But I can say the task needed some edit and review from this perspective.
For example: "to bad".   ""love it...very touch.it's to bad that in the dvd description doesn't mention no subtitles",

2- Edited: Solved for me.

**Comment by SavanDoshi** [comment]
@fsiar this dataset is created from amazon reviews. The reviews are written by random reviewers on amazon. Therefore, it might have some grammatical mistakes. I make sure that there are no grammatical mistakes in the explanation.

**Comment by fsiar** [comment]
[image: image.gif]Hi, I see. But the question is should the model also
learn it in this way?
I am not sure. It is more dependent on the task goal.
Maybe it could increase the model tolerance but is completely dependent on
the full set size.
For me considering this task from a grammar aspect has the potential to be
another separate task.
I am not in a place to say it is fit for this set or not. If the model can
tolerate it, so it is fine. But if it also learning the grammar from this
set maybe it could be a matter.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
10/04/21,
12:50:55 AM

**Comment by SavanDoshi** [comment]
@swarooprm Hey, can you have look at this issue? Should I update anything regarding grammar in the review?

**Comment by fsiar** [comment]
I recommend having this task in the dataset but include this aspect in the
task readme.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality7&>
10/04/21,
12:52:47 AM

**Comment by danyaljj** [comment]
@SavanDoshi several suggestions: 
 -  Add separators for the instances that contain multiple labels. For example, `Label:` can be ` <sep> Label: ` 
 - The notation of `\"<word\\>\"` is a bit confusing (it is easily confused with HTML tags). I would suggest using a slightly different notation (say, `{word}` or `[word]`).  
 - `original news headlines`  -> drop `original` and just call it `news headline`. This applies to multiple tasks here. 
 - Shorten the instructions: `Your task is to classify` -> `Classify` or `In this task, you're given X` -> `Given X, ...`

**Comment by SavanDoshi** [comment]
@danyaljj thank you for the suggestions. I have updated my files according to suggestions.

**Comment by danyaljj** [comment]
Looks good! Leaving it for @swarooprm to double-check before merging.

**Review by swarooprm — APPROVED** [review]
LGTM
You can do more tasks from the Semeval dataset.

**Pull request merged**
