### PR TITLE
Tasks 922-926:Event2Mind and Coached_Conv_Pref dataset

### PR DESCRIPTION
**Pull request by yashbhokare**

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks @yashbhokare! Looks like the tests are failing. 
Wondering if you can check the errors?

**Comment by aarunku5** [comment]
@yashbhokare can you address the test errors? Thanks!

> Thanks @yashbhokare! Looks like the tests are failing.
> Wondering if you can check the errors?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by yashbhokare** [comment]
Sure I'll check and update it by EOD.

**Comment by danyaljj** [comment]
Looks like the tests are failing. I am actually not sure why, but it might be easier to test them locally on your machine: 

```
> python src/test_all.py
```

**Comment by aarunku5** [comment]
> Looks like the tests are failing. I am actually not sure why, but it might be easier to test them locally on your machine:
> 
> ```
> > python src/test_all.py
> ```

@yashbhokare can you please address this?

**Pull request merged**
