### PR TITLE
Address human feedback for tasks 400 - 420 

### PR DESCRIPTION
**Pull request by Palipoor**

### CODE REVIEW

**Comment by Palipoor** [comment]
I tried fixing the Unicode characters, but it creates meaningless characters sometimes.

**Comment by danyaljj** [comment]
> I tried fixing the Unicode characters, but it creates meaningless characters sometimes.

And by that you mean, running this script? https://github.com/allenai/natural-instructions-expansion/blob/master/src/fix_unicode_characters.py

**Comment by Palipoor** [comment]
> > I tried fixing the Unicode characters, but it creates meaningless characters sometimes.
> 
> And by that you mean, running this script? https://github.com/allenai/natural-instructions-expansion/blob/master/src/fix_unicode_characters.py

Yes!

**Comment by danyaljj** [comment]
> > > I tried fixing the Unicode characters, but it creates meaningless characters sometimes.
> > 
> > 
> > And by that you mean, running this script? https://github.com/allenai/natural-instructions-expansion/blob/master/src/fix_unicode_characters.py
> 
> Yes!

How about we keep running this script separate from addressing human feedback? 
The issue is that sometimes fixing the unicode characters results in massive changes that make the PRs difficult to review.

**Comment by danyaljj** [comment]
Applied one minor fix. Will merge upon green. Thanks!

**Pull request merged**
