### PR TITLE
Tasks 927-928 : style transfer

### PR DESCRIPTION
**Pull request by tanay2001**
added style transfer #220

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks, @tanay2001! 

Looks good to me! Wondering if you can add a few more positive and negative examples? (so that we have 5 of each). Otherwise, looks good to me!  Leaving it here for @swarooprm to review before merging it.

**Comment by tanay2001** [comment]
> Thanks, @tanay2001!
> 
> Looks good to me! Wondering if you can add a few more positive and negative examples? (so that we have 5 of each). Otherwise, looks good to me! Leaving it here for @swarooprm to review before merging it.

Hi @danyaljj @swarooprm 
I have addressed the comments please have a look!

**Comment by swarooprm** [comment]
@tanay2001, looks good, two more comments, hopefully, the last one.
- Don't use generic explanations across examples, it has been shown that the model just ignores them. I wrote a customized explanation for the 1st positive example of task 927. Do the same for the rest in both tasks.
- There are some grammatical mistakes, some I fixed, but there are still a few e.g. "Though the output is positive , it changes the input text completely, as the task also involves to make minimal changes a better answer would be : i ate all of it""

**Comment by tanay2001** [comment]
> @tanay2001, looks good, two more comments, hopefully, the last one.
> 
> * Don't use generic explanations across examples, it has been shown that the model just ignores them. I wrote a customized explanation for the 1st positive example of task 927. Do the same for the rest in both tasks.
> * There are some grammatical mistakes, some I fixed, but there are still a few e.g. "Though the output is positive , it changes the input text completely, as the task also involves to make minimal changes a better answer would be : i ate all of it""

Thanks for the review, I have made the changes

**Comment by swarooprm** [comment]
@tanay2001, thanks for the changes, look good to me now.
However, the readme shows too many task addition (it should just show the 2 tasks that are part of this PR in the diff), may be because of incorrect merge?
This PR is good to go once the readme issues get resolved.

**Comment by tanay2001** [comment]
> @tanay2001, thanks for the changes, look good to me now. However, the readme shows too many task addition (it should just show the 2 tasks that are part of this PR in the diff), may be because of incorrect merge? This PR is good to go once the readme issues get resolved.

yes, it was a merge issue, fixed it!

**Pull request merged**
