### PR TITLE
task1508-1510 (wordnet antonym generation, evalution antonym generation and evalution relationship extraction), 1582-1585

### PR DESCRIPTION
**Pull request by atharva-naik**
task1508 (synthetic/wordnet): Given an adjective, generate it's antonym. An antonym of a word is a word opposite in meaning to it.
task1509 (EVALution dataset): Given an adjective, generate it's antonym. An antonym of a word is a word opposite in meaning to it.
task1510 (EVALution dataset): Given a phrase describing the relationship between two words, extract the words and the lexical relationship between them.

### CODE REVIEW

**Comment by swarooprm** [comment]
@kurbster, can you help review these tasks?

**Comment by kurbster** [comment]
Yep, I can take a look!

**Comment by kurbster** [comment]
Make sure to indent the json files.
```
json.dump(task, open(fname, 'w'), indent=4)
```
Can you add the domain for every task? The list of domains is [here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md). Also you should shuffle the instances of every class so there is no pattern amongst the samples. Can you add a link to the datasets in the sources section? 

For task 1508, Your explanation for the first negative example is wrong. It should say `... aren't opposite in meaning`.

For task 1509, the second positive example is a little weird. Yes, climb usually means going up but someone could say `I am going to climb down the latter`. You should change this example, maybe use ascend/descend instead. The second negative example doesn't have a good explanation. A war and a battle are not the same meaning, you should instead say `The output is incorrect because a battle is part of a war and are not antonyms`. Also, some of the instances in this task are suspicious like `age` and `young`, `air` and `water`, `trouble` and `smooth` I wouldn't define these as antonyms. @danyaljj @swarooprm what do you think about examples like these? This is only a handful I imagine there are more "pseudo" antonyms in the dataset.

Task 1510 is good.

**Comment by atharva-naik** [comment]
I'll fix 1508 and 1509 and make a new commit. Should I make a new PR for 1511-1514? Also I had a few queries regarding the domains. For a lexical dataset what should the domain be? Should it be something like 'Global Facts'?

**Comment by atharva-naik** [comment]
@kurbster Hi I have fixed the issues pointed out in your comment. Also, it is pretty hard to fix all antonyms without a manual review. The original dataset probably didn't review their antonyms properly I guess. I tried my best to manually delete and or edit as many antonym pairs as possible (nearly 200 or so). Please let me know if there are any obvious bad antonyms remaining. I'll try to do another manual review.

**Comment by aarunku5** [comment]
Made a few changes, the tasks all look good now. I've renamed the pull request, can you update the readme and file names to match the numbers?

**Comment by atharva-naik** [comment]
@aarunku5 should I change the filenames in my fork?

**Comment by aarunku5** [comment]
Yes, change 1511-1514 to 1582-1585

**Comment by atharva-naik** [comment]
@aarunku5  Sorry I had to re-fork due to some conflicts. I have changed the names in this PR: https://github.com/allenai/natural-instructions-expansion/pull/527. It has passed the CI build/test. Please let me know if any other changes are needed. Thanks for reviewing my submission : )

**Comment by aarunku5** [comment]
> @aarunku5 Sorry I had to re-fork due to some conflicts. I have changed the names in this PR: #527. It has passed the CI build/test. Please let me know if any other changes are needed. Thanks for reviewing my submission : )

In that case, I'll close this PR now. Can you add tasks 1508-1510 into your new PR, and update the README?

**Pull request closed without merging**
