### PR TITLE
Task 296-300: StoryCloze

### PR DESCRIPTION
**Pull request by Mirzyaaliii**
Created 5 new tasks from the **StoryCloze** dataset (created 1 earlier)

1.  task296_StoryCloze_correct_end_answer_generation  -->  Given four sentences of five sentence story, select correct answer for last (fifth) sentence from the given option.
2. task297_StoryCloze_incorrect_end_answer_generation  -->  Given four sentences of five sentence story, select incorrect answer for last (fifth) sentence from the given option.
3. task298_StoryCloze_correct_end_classification  -->  Given four sentences of five sentence story and fifth sentence, classify whether the fifth sentence is proper or not by providing 'Yes' or 'No'.
4. task299_StoryCloze_sentence_generation  -->  Given four sentences of five sentence story, provide the position and missing part (fifth sentence) of the story.
5. task300_StoryCloze_order_generation  -->  Given five sentences of the story (sentences are shuffled), provide the correct order of the story.

Please review.

### CODE REVIEW

**Comment by swarooprm** [comment]
Thanks for the PR. However, note that we already have a submission from ROC Stories https://github.com/allenai/natural-instructions-expansion/pull/132
Make sure that your tasks are not same as the ones already submitted.
Also, I hope the registering dataset in the spreadsheet will help to resolve such conflicts next time.

**Comment by swarooprm** [comment]
Also task 295 is already taken https://github.com/allenai/natural-instructions-expansion/pull/169, so please rename this to task 296-300

**Comment by Mirzyaaliii** [comment]
> Also task 295 is already taken #169, so please rename this to task 296-300

Done!!

**Comment by Mirzyaaliii** [comment]
> Thanks for the PR. However, note that we already have a submission from ROC Stories #132
> Make sure that your tasks are not same as the ones already submitted.
> Also, I hope the registering dataset in the spreadsheet will help to resolve such conflicts next time.

Yes, I am aware of PR #132.
StoryCloze and ROCStories are the different corpora [(Link of the dataset)](https://cs.rochester.edu/nlp/rocstories/).

**Comment by swarooprm** [comment]
> > Thanks for the PR. However, note that we already have a submission from ROC Stories #132
> > Make sure that your tasks are not same as the ones already submitted.
> > Also, I hope the registering dataset in the spreadsheet will help to resolve such conflicts next time.
> 
> Yes, I am aware of PR #132.
> StoryCloze and ROCStories are the different corpora [(Link of the dataset)](https://cs.rochester.edu/nlp/rocstories/).

Got it. thanks! Will add reviews later.

**Comment by swarooprm** [comment]
@aarunku5, can you review this task?

**Comment by aarunku5** [comment]
296, 297- The category should be classification and not answer generation since they're choosing a/b. Also could you modify the definition of both as they are quite similar to 213, 214 from PR #132?
298- Can you include one negative example where it is incorrectly classified? Swap out either the first or second negative example.
299- There is a chance that there will be a question about the position for certain stories, as the sentence generation is open ended. So based on someone's interpretation of the missing position, answers could vary. For example in this instance:
{
input: "Sentence1: Laverne needs to prepare something for her friend's party. Sentence2: She chooses a recipe and follows it closely. Sentence3: Laverne tests one of the brownies to make sure it is delicious. Sentence4: The brownies are so delicious Laverne eats two of them."
output: "2, She decides to bake a batch of brownies."
explanation: "As mentioned in the 3rd sentence, Laverne tests one of the brownies brownies; She must decides to take batch of brownies with her."
}
If the generated sentence was something like "She finished making a batch of brownies and waited for them to cool", it could go into position 3 instead, and the story would still make sense. I'm not sure how many stories exactly in the dataset would have this kind of ambiguity present. Could you clarify this?
300- The task is quite similar to 217 from PR #132, could you modify the definition/task a bit?

**Comment by Mirzyaaliii** [comment]
> 296, 297- The category should be classification and not answer generation since they're choosing a/b. Also could you modify the definition of both as they are quite similar to 213, 214 from PR #132?
> 298- Can you include one negative example where it is incorrectly classified? Swap out either the first or second negative example.
> 299- There is a chance that there will be a question about the position for certain stories, as the sentence generation is open ended. So based on someone's interpretation of the missing position, answers could vary. For example in this instance:
> {
> input: "Sentence1: Laverne needs to prepare something for her friend's party. Sentence2: She chooses a recipe and follows it closely. Sentence3: Laverne tests one of the brownies to make sure it is delicious. Sentence4: The brownies are so delicious Laverne eats two of them."
> output: "2, She decides to bake a batch of brownies."
> explanation: "As mentioned in the 3rd sentence, Laverne tests one of the brownies brownies; She must decides to take batch of brownies with her."
> }
> If the generated sentence was something like "She finished making a batch of brownies and waited for them to cool", it could go into position 3 instead, and the story would still make sense. I'm not sure how many stories exactly in the dataset would have this kind of ambiguity present. Could you clarify this?
> 300- The task is quite similar to 217 from PR #132, could you modify the definition/task a bit?

Thank you for your comments.

All the changes are done.

One comment on the task - 299:
This task is inspired by paper (data is also from this paper only) - [https://aclanthology.org/2020.latechclfl-1.19.pdf](https://aclanthology.org/2020.latechclfl-1.19.pdf)

They are training the model for the same task and as mentioned in the paper
> The missing position k was randomly decided based on a discrete uniform distribution.

I created the task the same way.

Let me know if it is fine or what kind of changes I can do with this task.

**Comment by aarunku5** [comment]
Thanks!

296
Modify the definition to: "... and your job is to complete the story by selecting one of the sentence choices from (A) and (B), such that the story sounds fully coherent."
Positive/Negative Examples: Modify the explanation to say "fourth sentence" instead of "last sentence (Sentence4)"

297
Modify the definition similar to 296
Positive/negative examples like 296

298
Minor grammatical errors in the definition
Positive/negative examples like 296

300
Can your reword the definition slightly to avoid putting text in ()? Replace "... therefore the" with "to create a". Also add an extra sentence with an example of the output format like "23451"
Positive/Negative examples: Can you refer to task 217 and give the explanations in a similar format?

299
Minor grammatical errors in the definition
Positive/negative examples like 296
I'm also ok with your present task format for 299 as long as the examples generated don't have cases of ambiguity like the instance I specified. Could you go over the instances once to double check? If you don't see such cases of ambiguity, then you can just make the changes to the definition and examples. Also if you're retaining the task as is, swap out the example about cooking brownies for something non-ambiguous.

**Comment by Mirzyaaliii** [comment]
> Thanks!
> 
> 296
> Modify the definition to: "... and your job is to complete the story by selecting one of the sentence choices from (A) and (B), such that the story sounds fully coherent."
> Positive/Negative Examples: Modify the explanation to say "fourth sentence" instead of "last sentence (Sentence4)"
> 
> 297
> Modify the definition similar to 296
> Positive/negative examples like 296
> 
> 298
> Minor grammatical errors in the definition
> Positive/negative examples like 296
> 
> 300
> Can your reword the definition slightly to avoid putting text in ()? Replace "... therefore the" with "to create a". Also add an extra sentence with an example of the output format like "23451"
> Positive/Negative examples: Can you refer to task 217 and give the explanations in a similar format?
> 
> 299
> Minor grammatical errors in the definition
> Positive/negative examples like 296
> I'm also ok with your present task format for 299 as long as the examples generated don't have cases of ambiguity like the instance I specified. Could you go over the instances once to double check? If you don't see such cases of ambiguity, then you can just make the changes to the definition and examples. Also if you're retaining the task as is, swap out the example about cooking brownies for something non-ambiguous.

Thank you for the comments!

All the changes are done.

For Task-299, I tried my best to remove ambiguity as much as I can. Please let me know if there are any other changes.

**Comment by aarunku5** [comment]
Thanks! Everything looks good to me here @swarooprm

**Review by swarooprm — APPROVED** [review]
LGTM

**Comment by swarooprm** [comment]
Please do gitpull, merge with the main, so that tests will pass and I can approve.

**Comment by Mirzyaaliii** [comment]
> Please do gitpull, merge with the main, so that tests will pass and I can approve.

Done.

**Comment by eshaanpathak** [comment]
If you look at the "Files changed" tab, it seems like there are a lot of changes to the README outside of tasks 296 to 300. I would recommend copying the current README from `allenai:master` and just adding in the rows for tasks 296 to 300 to not make any other changes. Otherwise this would undo a lot of my edits in #224.

**Comment by Mirzyaaliii** [comment]
> If you look at the "Files changed" tab, it seems like there are a lot of changes to the README outside of tasks 296 to 300. I would recommend copying the current README from `allenai:master` and just adding in the rows for tasks 296 to 300 to not make any other changes. Otherwise this would undo a lot of my edits in #224.

Done.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
