### PR TITLE
task 290 : TellMyWhy

### PR DESCRIPTION
**Pull request by amirrezamirzaei**
task 288 using [TellMyWhy](https://github.com/StonyBrookNLP/tellmewhy)

### CODE REVIEW

**Review by yeganehkordi — COMMENTED** [review]
Looks good to me. Some suggestions:
1. Please add the link to the dataset in the source field.
2. Why did He formulate a machine? Wasn't it because of that he decided to revolutionize the industry?
3. Maybe you can mention in the description that question and passage are separated with "\n" or write the input with the format of {passage} \n Question: {question}

#143

**Comment by amirrezamirzaei** [comment]
@yeganehkordi  thanks for the suggestions, I fixed them.

**Comment by danyaljj** [comment]
Thanks! 

For a future PRs: I think you can also create a task for answering why-questions that are answerable.

**Review by swarooprm — APPROVED** [review]
LGTM!
+1 on creating more tasks from this dataset.

**Pull request merged**
