### PR TITLE
Update task1509_evalution_antonyms

### PR DESCRIPTION
**Pull request by yeganehkordi**
Addressing the #752 
These tasks are similar but their sources are different. I restored the previous version of task 1509 in #483.

### CODE REVIEW

**Comment by danyaljj** [comment]
@yeganehkordi do we know in what PR the two tasks became identical?

**Comment by yeganehkordi** [comment]
> @yeganehkordi do we know in what PR the two tasks became identical?

Yes, After closing the first PR(#483), they became identical in #527. It was the contributor's mistake and since they were reviewed in the first PR, we didn't notice that.

**Comment by danyaljj** [comment]
I see. Thanks for clarifying!

**Comment by todpole3** [comment]
Thanks very much for addressing this @yeganehkordi and @danyaljj!

**Pull request merged**
