### PR TITLE
Add web nlg, personachat, quartz and wiqa

### PR DESCRIPTION
**Pull request by Palipoor**
I added a task from web nlg (data to text), two tasks from personachat, a task from quartz and a task from wiqa(the main task). However, they don't have categories and domains.

### CODE REVIEW

**Review by yizhongw — COMMENTED** [review]
It seems that `definition` is empty in the `task1727_wiqa_what_is_the_effect.json`?

**Review by yeganehkordi — COMMENTED** [review]
Thanks! Looks good to me. Some minor comments:
- Please add the URL field to the files. As suggested in #742 
- I think domains, reasoning, and categories are:
`task1727_wiqa_what_is_the_effect.json`
Domains: Natural Science, Reasoning: Relational Reasoning, Deductive Reasoning, Categories: Question Answering
`task1728_web_nlg_data_to_text.json`
Domains: Wikipedia, Reasoning: Relational Reasoning, Commonsense Reasoning, Categories: Data to Text
`task1729_personachat_generate_next.json`
Domains: Dialogue, Reasoning: Reasoning on Social Interactions, Commonsense Reasoning -> Social Situations, Categories: Dialogue Generation
`task1730_personachat_choose_next.json`
Domains: Dialogue, Reasoning: Reasoning on Social Interactions, Commonsense Reasoning -> Social Situations, Categories: Dialogue Generation
`task1731_quartz_question_answering.json`
Domains: Natural Science, Reasoning: Relational Reasoning, Scientific Reasoning, Categories: Question Answering
-  I think the original options in wiqa dataset (more/less/no effect) could be better outputs for `task1727_wiqa_what_is_the_effect`.
-  "Contributors" field is empty in the first four tasks.

**Comment by Palipoor** [comment]
@yeganehkordi I fixed everything, except this:

> I think the original options in wiqa dataset (more/less/no effect) could be better outputs for task1727_wiqa_what_is_the_effect.

I think "for" and "against" are more intuitive, especially since "more" and "less" are very commonly used in sentences. E.g. :
`  What is the effect of strenuous exercise being undertaken on less oxygen reaching the body.?` 
I think it's more meaningful to say the first event is "against" the second event than to say it "lessens" it.

**Review by yeganehkordi — APPROVED** [review]
It makes sense, LGTM!

**Comment by yizhongw** [comment]
LGTM!

**Review by danyaljj — APPROVED** [review]

**Pull request merged**
