### PR TITLE
Task109 SpamSMS detection

### PR DESCRIPTION
**Pull request by SavanDoshi**
Please Review.

### CODE REVIEW

**Review by swarooprm — CHANGES_REQUESTED** [review]
Thanks for creating PR! The test is failing, you can fix this by removing duplicate instances and adding an updated readme file (similar to the other PRs where the test is passing)

This task looks good. Some feedbacks.
1. In the definition, define what is a spam and what is a ham. Definition looks narrow now.
2. There are some typos in the explanation e.g. "this message consits the word free and promies to give somthing free. therefore it is can be classify to spam."
3. Finally, make sure to include the source dataset name and task category name while creating the json file name. You can use this format: taskabc_<source dataset>_<task category>.json E.g. in task001_quoref_question_generation.json, the source dataset is 'quoref' and the task category is 'question generation.

**Comment by danyaljj** [comment]
After addressing the comments, please pull and merge with the main branch.

**Comment by danyaljj** [comment]
Please use the command line git to merge with the master.

**Comment by SavanDoshi** [comment]
I tried to resolve the conflicts because of some reason. Therefore I am closing this pull request. and creating new request.

**Pull request closed without merging**
