### PR TITLE
Task 394-396: PersianQA

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on the: https://github.com/sajjjadayobi/PersianQA

### CODE REVIEW

**Comment by danyaljj** [comment]
Since this is a non-English task, please add the appropriate fields based on #113. 

@Palipoor wondering if you can review this PR?

**Comment by yeganehkordi** [comment]
In most of the cases, the output language is Persian, but there are some questions asking about a scientific term, etc, and their answer is in English. Is it okay to have two output languages?

**Comment by danyaljj** [comment]
I think we should go with the single dominant language, which in this case is "fa".

**Comment by yeganehkordi** [comment]
Thanks!

**Comment by Palipoor** [comment]
The tasks look good to me! 
I'm not sure about the descriptions though. Should they be in English? (Just asking to know for future tasks)

**Comment by yeganehkordi** [comment]
Thanks! Yes, descriptions and explanations should be in English.

**Comment by danyaljj** [comment]
Thanks! Merging!

**Pull request merged**
