### PR TITLE
Task1186: natural-ness evaluation

### PR DESCRIPTION
**Pull request by Sujan242**
Based on https://arxiv.org/pdf/2109.02938.pdf 
Suggested in issue #286

### CODE REVIEW

**Comment by danyaljj** [comment]
@Ravsehajsinghpuri wondering if you can review this PR?

**Comment by Ravsehajsinghpuri** [comment]
@danyaljj Sure, will do!

**Comment by Sujan242** [comment]
@Ravsehajsinghpuri All the labels have been converted to integers because labels "1.0" and "1" would represent 2 different classes.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Pull request merged**
