### PR TITLE
Task 476-487: CLS Dataset - Multilingual Sentiment Classification of Product Reviews

### PR DESCRIPTION
**Pull request by gkaramanolakis**
Task: classify a given product review to positive or negative sentiment.

The CLS dataset (https://aclanthology.org/P10-1114/) contains product reviews from four languages (English, German, French, Japanese) and three product domains (books, dvd, music). Each task here corresponds to a unique language and domain. 

All datasets have the same label distribution: 
POS    1000
NEG    1000

### CODE REVIEW

**Review by Maitreyapatel — CHANGES_REQUESTED** [review]
Thanks for submitting these tasks. Please refer following few suggestions:
1. In task file names, add "_classification" at the end as they are classification tasks. (i.e., task476_cls_english_books -> task476_cls_english_books_classification)
2. In all descriptions, apart from giving (domain: music, language: English) mention something like "In this task, you are given music reviews in English language."
3. Please give more explanations. Instead of mentioning overall sentiment is positive or negative, try to give the reason why that's the case.
4. Also, there are lots of unicode characters. Please use the proper encoding scheme to remove them and retain the original information. 
5. And remove unnecessary '\n' from the files.

**Comment by gkaramanolakis** [comment]
> Thanks for submitting these tasks. Please refer following few suggestions:
> 
> 1. In task file names, add "_classification" at the end as they are classification tasks. (i.e., task476_cls_english_books -> task476_cls_english_books_classification)
> 2. In all descriptions, apart from giving (domain: music, language: English) mention something like "In this task, you are given music reviews in English language."
> 3. Please give more explanations. Instead of mentioning overall sentiment is positive or negative, try to give the reason why that's the case.
> 4. Also, there are lots of unicode characters. Please use the proper encoding scheme to remove them and retain the original information.
> 5. And remove unnecessary '\n' from the files.

Done. Thank you for the very helpful suggestions.

**Comment by yeganehkordi** [comment]
Since this is a multilingual task, please add the appropriate fields based on: #113

**Comment by gkaramanolakis** [comment]
> Since this is a multilingual task, please add the appropriate fields based on: #113

Done, thanks!

**Comment by danyaljj** [comment]
Thank you, all!

**Pull request merged**
