### PR TITLE
ASSET two tasks 111 and 112

### PR DESCRIPTION
**Pull request by Palipoor**
I create two tasks with the dataset ASSET. This is my first time doing this and I would appereciate your feedback. Thanks.

### CODE REVIEW

**Comment by Palipoor** [comment]
Oh I see. I will fix the problem.

**Comment by danyaljj** [comment]
Thanks! 

- Do you think `for non-native English speakers` is necessary? Basically, I am wondering whether native speakers of English can objectively solve these tasks, in which case, the mention of `non-native speakers` is redundant. 
- `have unnecessary   phrases`: redundant space before `phrases`  
- In the task definition, define what is the expected output. `You are expected to output "Text one"  if the first sentence is simpler. Otherwise, ....` 
- After PR #53 is merged, please pull and merge with the main branch. It should trigger a bunch of new tests.

**Comment by Palipoor** [comment]
@danyaljj Thanks for the feedback. Sorry if I had many mistakes, it was my first time doning this.
The reason I put "non-native speakers" is the task description in ASSET dataset's mturk templates had it. I will remove it.
I will also fix other problems. thanks.

**Comment by danyaljj** [comment]
> The reason I put "non-native speakers" is the task description in ASSET dataset's mturk templates had it.  

If that's how the original task was phrased, let's keep it. We want to remain as faithful as possible to the original instructions.

**Comment by Palipoor** [comment]
At first I fixed some duplicate issues with other tasks but then I realized I'll encounter conflicts with the master branch, so I just went back.

**Review by danyaljj — APPROVED** [review]
Thanks! It's green from my side! ✅ 
@swarooprm feel free to merge when you're happy with the task.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
