### PR TITLE
tasks 1331-1333

### PR DESCRIPTION
**Pull request by Ravsehajsinghpuri**

### CODE REVIEW

**Comment by aarunku5** [comment]
Thanks, here are the comments for your tasks:

1331-
in a certain order--> in a random order

1332-
A year may be a leap year if it is evenly divisible by 4. Years that are divisible by 100 (century years such as 1900 or 2000) cannot be leap years unless they are also divisible by 400.  Include this concept in the definition.
Update your explanations and instances as well based on this.

1333-
Specify conditions for date validity in the definition.
Update your explanations as well based on this.
(suggestion- you can do a mm/dd/yyyy task and a date translation task as well based on this)

**Comment by Ravsehajsinghpuri** [comment]
@aarunku5 thanks for the review. working on the changes. Also, thanks for the suggestion - will add these tasks as well to the next PR

**Comment by Ravsehajsinghpuri** [comment]
@aarunku5 is this PR good to go and merge?

**Comment by swarooprm** [comment]
@Ravsehajsinghpuri, can you add 3 new fields as the error message says so that tests pass?

**Comment by Ravsehajsinghpuri** [comment]
@Ravsehajsinghpuri 
You need to have 3 new fields in each task json:
Since everything in your tasks are in English, you can add these 3 lines to your files
"Input_language": [
        "English"
    ],
    "Output_language": [
        "English"
    ],
    "Instruction_language": [
        "English"
    ]

You can also check any task jsons, they now have these fields (we have recently updated all of them)

**Comment by swarooprm** [comment]
@Ravsehajsinghpuri You need to have 3 new fields in each task json: Since everything in your tasks are in English, you can add these 3 lines to your files 
"Input_language": [ "English" ], 
"Output_language": [ "English" ], 
"Instruction_language": [ "English" ]

You can also check any task jsons, they now have these fields (we have recently updated all of them)

**Comment by Ravsehajsinghpuri** [comment]
@swarooprm got it, will do that - thanks!

**Pull request merged**
