### PR TITLE
Tasks 573-578 air_dialog and curiosity_dialog instructions

### PR DESCRIPTION
**Pull request by jayavardhan3112**

### CODE REVIEW

**Comment by danyaljj** [comment]
@cosmicishan  wondering if you can review this PR?

**Comment by swarooprm** [comment]
@Palipoor's reviews are here: https://github.com/swarooprm/CSE576HW/pull/58

**Comment by swarooprm** [comment]
Please rename your files to 573-578

**Comment by cosmicishan** [comment]
> @cosmicishan wondering if you can review this PR?

Do I need to review it now or @swarooprm took care of it?

**Comment by jayavardhan3112** [comment]
> > @cosmicishan wondering if you can review this PR?
> 
> Do I need to review it now or @swarooprm took care of it?

@cosmicishan - @swarooprm has already reviewd it,

**Comment by swarooprm** [comment]
> > @cosmicishan wondering if you can review this PR?
> 
> Do I need to review it now or @swarooprm took care of it?

@cosmicishan, please review. We need reviews from at least 2 persons.

**Comment by cosmicishan** [comment]
> > > @cosmicishan wondering if you can review this PR?
> > 
> > 
> > Do I need to review it now or @swarooprm took care of it?
> 
> @cosmicishan, please review. We need reviews from at least 2 persons.

I will review it.

**Comment by cosmicishan** [comment]
> _No description provided._

Correct grammar and typos in the explanation and definition from all the tasks. Few suggestions: Capitalise the first word and add a full stop in the end.

It would be better if you add space before and after '\n' in all inputs. Because that's what everyone else done in their task. Even though it will add a new space in the new line, it would be better when it comes to readability. You can see other tasks where they add space before and after. For example, take a look at this ->  [here](https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task314_europarl_sv-en_classification.json)

Add Contributor and Categories at the top of the JSON file, not at the bottom.

Edit your readme, elaborate your summary in a little bit more detail. It would be better if you make readme a little bit more informative by providing more context.

For example:

You can specify by writing Task 573 is the classification of the context of a conversation between flight agent and customer, task 575 is a classification of the sentence spoken by 'agent' and 'customer', task 577 is a classification of the sentence spoken by 'assistant' and 'user'. 

Other than that I think it looks good.

**Comment by jayavardhan3112** [comment]
> > _No description provided._
> 
> Correct grammar and typos in the explanation and definition from all the tasks. Few suggestions: Capitalise the first word and add a full stop in the end.
> 
> It would be better if you add space before and after '\n' in all inputs. Because that's what everyone else done in their task. Even though it will add a new space in the new line, it would be better when it comes to readability. You can see other tasks where they add space before and after. For example, take a look at this -> [here](https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task314_europarl_sv-en_classification.json)
> 
> Add Contributor and Categories at the top of the JSON file, not at the bottom.
> 
> Edit your readme, elaborate your summary in a little bit more detail. It would be better if you make readme a little bit more informative by providing more context.
> 
> For example:
> 
> You can specify by writing Task 573 is the classification of the context of a conversation between flight agent and customer, task 575 is a classification of the sentence spoken by 'agent' and 'customer', task 577 is a classification of the sentence spoken by 'assistant' and 'user'.
> 
> Other than that I think it looks good.

@cosmicishan Solved the comments, please review. Thanks. 😊

**Comment by cosmicishan** [comment]
> > > _No description provided._
> > 
> > 
> > Correct grammar and typos in the explanation and definition from all the tasks. Few suggestions: Capitalise the first word and add a full stop in the end.
> > It would be better if you add space before and after '\n' in all inputs. Because that's what everyone else done in their task. Even though it will add a new space in the new line, it would be better when it comes to readability. You can see other tasks where they add space before and after. For example, take a look at this -> [here](https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task314_europarl_sv-en_classification.json)
> > Add Contributor and Categories at the top of the JSON file, not at the bottom.
> > Edit your readme, elaborate your summary in a little bit more detail. It would be better if you make readme a little bit more informative by providing more context.
> > For example:
> > You can specify by writing Task 573 is the classification of the context of a conversation between flight agent and customer, task 575 is a classification of the sentence spoken by 'agent' and 'customer', task 577 is a classification of the sentence spoken by 'assistant' and 'user'.
> > Other than that I think it looks good.
> 
> @cosmicishan Solved the comments, please review. Thanks.

Looks good to me. 

@swarooprm Do final check.

**Review by swarooprm — APPROVED** [review]
LGTM! Merging. Congrats on acceptance of your first set of tasks. 

I have a minor concern, task576 and task578 have almost the same file name, make sure to change by contextualizing the task. Do it in your next PR.

**Comment by jayavardhan3112** [comment]
> LGTM! Merging. Congrats on acceptance of your first set of tasks.
> 
> I have a minor concern, task576 and task578 have almost the same file name, make sure to change by contextualizing the task. Do it in your next PR.

Noted @swarooprm , Thank you for suggesting, will rectify this mistake from the next time,

**Pull request merged**
