### PR TITLE
Tasks 213-222 ROCStories

### PR DESCRIPTION
**Pull request by aarunku5**
5 answer generation, 3 classification

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! Can you check how your introduced tasks are different from tasks 67-72?

**Comment by aarunku5** [comment]
Tasks 215 and 216 don't have any restrictions when writing a new story ending unlike the ANLI tasks.
Tasks 217 and 218 are sentence ordering oriented.
Tasks 219 and 220 assign titles to the story.

Tasks 213 and 214 are similar to the ANLI tasks, but have a longer context story provided. If they are too similar, I can modify those 2 tasks to something like:
213-  given 3 options, choose which 2 sentences belong to the story (so out of abc picking 2 as say 'bc')
214- similar to 213, but also answer which places they must be slotted into the story (so you pick ab, the full answer is that  they are slotted in '2a, 3b' respectively)

**Comment by aarunku5** [comment]
Have added the 2 tasks mentioned above

**Comment by danyaljj** [comment]
Got it. Let's keep all the tasks, but these are important considerations for when we publish the dataset and provide an experimental setup (which includes test and train sets). 

One quick comment: 
"and the title of the story" move it earlier in your definition: title -> sentences -> options. 

More comments later.

**Comment by aarunku5** [comment]
Have updated the descriptions

**Comment by danyaljj** [comment]
Here are some more comments: 
- `task213_rocstories_correct_ending_classification.json` looks good. 
- `task214_rocstories_incorrect_ending_classification.json` looks good. 
 - `task215_rocstories_incorrect_answer_generation`: is this really true? `Your job is write the last sentence of the story such that it does not connect with the rest of the story.` Like can someone copy a random sentence from the internet and use to it to respond to all the instances? Looking through the outputs, it seems to me that there is some form of semantic relevance between the endings and the story (even though the ending does not quite complete the story). 
 - `task216_rocstories_correct_answer_generation.json` the description is wrong? 
 - `tasks/task217_rocstories_ordering_answer_generation.json` looks good. 
 - `task218_rocstories_swap_order_answer_generation.json` : "is apt for the title" rephrase to make it more clear. 
 - `task219_rocstories_title_answer_generation.json`: a concern with this task is whether avg humans can agree on generating these titles. Even more: given a title, can humans agree whether it's a good title? Not sure. 
 - `task220_rocstories_title_classification`: `more apt` rephrase. 
- `task221_rocstories_two_choice_classification`:  `In this task, you're given the title of a five-sentence story, three sentences, and three options for sentences to add to the story as a,b,c.` Unclear; re-do the description. 
- `task222_rocstories_two_chioce_slotting_classification` also needs more improved/simpler/crisper definition.

**Comment by aarunku5** [comment]
Descriptions changed for 215, 216, 218, 220, 221, 222

I haven't changed anything in 219. Considering that titling is a subjective task, I can update the description to restrict the title to say less than 5 words, to be as simple as possible, and include the main topic of the story. Would that be ok?

**Comment by swarooprm** [comment]
> Descriptions changed for 215, 216, 218, 220, 221, 222
> 
> I haven't changed anything in 219. Considering that titling is a subjective task, I can update the description to restrict the title to say less than 5 words, to be as simple as possible, and include the main topic of the story. Would that be ok?

Thanks.  Yes, please update the description.

**Comment by aarunku5** [comment]
Updated 219

**Comment by danyaljj** [comment]
> * `task215_rocstories_incorrect_answer_generation`: is this really true? `Your job is write the last sentence of the story such that it does not connect with the rest of the story.` Like can someone copy a random sentence from the internet and use to it to respond to all the instances? Looking through the outputs, it seems to me that there is some form of semantic relevance between the endings and the story (even though the ending does not quite complete the story).

Thanks! It looks better! 

> * `task216_rocstories_correct_answer_generation.json` the description is wrong?

looks good. 


> * `task219_rocstories_title_answer_generation.json`: a concern with this task is whether avg humans can agree on generating these titles. Even more: given a title, can humans agree whether it's a good title? Not sure.

Looks good.

> * `task221_rocstories_two_choice_classification`:  `In this task, you're given the title of a five-sentence story, three sentences, and three options for sentences to add to the story as a,b,c.` Unclear; re-do the description.

🔴  Still not completely clear.  
 - When you say "three sentences out of a five-sentence story" are these the first three sentences or any arbitrary sentences (out of 5)? Make it clear. 
 - Do the selected sentence need to be sorted? (for example, is "ab" different from "ba")? Make it clear. 

> * `task222_rocstories_two_chioce_slotting_classification` also needs more improved/simpler/crisper definition.

I suppose the above questions apply to this task too.

**Comment by aarunku5** [comment]
Updated descriptions.

task221:
In this task, you're given the title and three arbitrary sentences out of a five-sentence story. You are also given three additional sentence options a,b, and c that may or may not belong to the story. Your job is to pick the the two sentence options that seamlessly connect with the rest of the story; note that the selected choices may fit into the story at any point. Indicate your selected choices in order, i.e., as 'ab'/'bc'/'ac' and not as 'ba'/'ca'/'cb'. If options are equally plausible, pick the ones that make more sense.

task222:
In this task, you're given the title and three arbitrary sentences out of a five-sentence story. You are also given three addtional sentence options a,b, and c that may or may not belong to the story. Your job is to pick the the two sentence options that seamlessly connect with the rest of the story, as well as the line number of the story that they will be inserted into; note that the selected choices may fit into the story at any point. Your answer must be in the form of '2a,5b', in order of the selected choices, i.e., '2a,5b' is allowed, and '5b,2a' is not allowed in the output. If options are equally plausible, pick the ones that make more sense.

**Comment by danyaljj** [comment]
task221: is clear. 

> the line number of the story 

not sure if this is clear. We may wanna talk about sentence order rather than "line number".

Maybe also exemplify it: "2a" means, the candidate sentence "a" will be inserted as the 2nd sentence in the story.

**Comment by aarunku5** [comment]
Changed 222's Definition:
In this task, you're given the title and three arbitrary sentences out of a five-sentence story. You are also given three addtional sentence options a,b, and c that may or may not belong to the story. Your job is to pick the the two sentence options that seamlessly connect with the rest of the story, as well as its position in the sentence order of the story; note that the selected choices may fit into the story at any point. Your answer must be in the form of '2a,5b', where '2a' means, the candidate sentence 'a' will be inserted as the 2nd sentence in the story. The answer must also be in order of the selected choices, i.e., '2a,5b' is allowed, and '5b,2a' is not allowed. If options are equally plausible, pick the ones that make more sense.

**Comment by danyaljj** [comment]
Looks good to me!

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
