### PR TITLE
Add tasks 513 and 514

### PR DESCRIPTION
**Pull request by Palipoor**
tasks 513 and 514 on argument classification from papers
_Leakage-Adjusted Simulatability: Can Models Generate Non-Trivial Explanations of Their Behavior in Natural Language?_
and
_Unsupervised Stance Detection for Arguments from Consequences_

### CODE REVIEW

**Comment by amirrezamirzaei** [comment]
looks good to me! a few really minor comments

- in task 513 can you specify the outputs label in the definiton.
- in task 514 definition in the readMe file I think its better if you change it like this `...consequence of that topic`

**Comment by Palipoor** [comment]
Thanks! I fixed them.

**Comment by danyaljj** [comment]
@amirrezamirzaei want to give the updated PR another look?

**Comment by amirrezamirzaei** [comment]
- task 513 looks good it would be better if `argument's stance on that topic` was changed to `argument's stance toward that topic`
- task 514 `related of that topic` should be `related to that topic`. also the last comment from my previous comment

**Comment by Palipoor** [comment]
Done.

**Comment by amirrezamirzaei** [comment]
thank you everything look good to me.

**Pull request merged**
