### PR TITLE
Tasks 1499-1504

### PR DESCRIPTION
**Pull request by Pruthvi98**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Pruthvi98, Thanks for the PR. I have renamed it to tasks 862-867 as task numbers till 861 are taken in the previous PR. Can you also rename your files names.

**Comment by Pruthvi98** [comment]
Hi @swarooprm, I have made the changes. The branch is task616-621, in it I have changed filenames and updated README

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/25

**Comment by swarooprm** [comment]
@Pruthvi98, these tasks look good to me and are ready to merge. Just that, I saw tasks numbered from 862-867 are already part of the accepted tasks in the tasks folder. Could you just rename your files with updated task numbers so that we can go ahead with merging?

**Comment by swarooprm** [comment]
Closing this as updated PR is in https://github.com/allenai/natural-instructions-expansion/pull/461

**Pull request closed without merging**
