### PR TITLE
Task 304 and 401 from paper "Where’s My Head? Definition, Data Set, and Models for Numeric Fused-Head Identification and Resolution"

### PR DESCRIPTION
**Pull request by Palipoor**

### CODE REVIEW

**Review by yeganehkordi — COMMENTED** [review]
Thanks! Looks good to me. Some suggestions:

- Maybe you can add some more explanation about the second negative example and remove an extra dot from "In this example, eight is being an indicator of an age.."
- I think you can mention the format of marked number (i.e., "_" +number+ "_") in the definition.

**Comment by swarooprm** [comment]
Can you address reviewer comments @Palipoor ?
I was wondering why certain labels (YEARS, AGE etc.) are in capital while certain others are not?

Also, you can create more tasks from this dataset.

**Comment by Palipoor** [comment]
> Can you address reviewer comments @Palipoor ?
> I was wondering why certain labels (YEARS, AGE etc.) are in capital while certain others are not?
> 
> Also, you can create more tasks from this dataset.

Sorry, I forgot about this. Will do asap.

**Comment by Palipoor** [comment]
> Can you address reviewer comments @Palipoor ?
> I was wondering why certain labels (YEARS, AGE etc.) are in capital while certain others are not?
> 
> Also, you can create more tasks from this dataset.

I think the change I just made will fix that capital issue. The thing is, for one of the labels the task is to give the referenced entity from the text. That's why they were not in capital letters.

**Comment by danyaljj** [comment]
@yeganehkordi can you check the changes made to the PR?

**Comment by yeganehkordi** [comment]
Sure! Looks good to me.

**Comment by danyaljj** [comment]
Thank you all!

**Pull request merged**
