### PR TITLE
Task 243- 245: Set operation tasks

### PR DESCRIPTION
**Pull request by nrjvarshney**
`task243_count_elements_in_set_intersection.json` | Count number of elements in the intersection of two given sets | Counting
`task244_count_elements_in_set_union.json` |  Count number of elements in the union of two given sets | Counting
`task245_check_presence_in_set_intersection.json` | Check presence of an element in the intersection of two given sets | Answer Generation

### CODE REVIEW

**Review by slowy07 — COMMENTED** [review]
hello @nrjvarshney ,thanks for the contribution !,can you solve the conflict before our merge,thanks !

**Comment by danyaljj** [comment]
Looks good to me! Thanks!

**Review by slowy07 — APPROVED** [review]
LGTM, thanks for the contribution!

**Review by swarooprm — APPROVED** [review]
Merging as of now. But please address these in your next PR.
1. Task245 should be of classification category and not answer generation.
2. While creating synthetic tasks, make sure that such tasks do not exist. In this case, similar tasks already exist e.g. https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task098_conala_list_intersection.json.

Note for constructing data splits: Decide whether to include these tasks in the repo later. If we decide to include it, make sure to keep this and task098 in separate splits.

**Pull request merged**
