### PR TITLE
Fix for Issue #652.

### PR DESCRIPTION
**Pull request by RushangKaria**

### CODE REVIEW

**Comment by danyaljj** [comment]
I'm not sure if I understand the changes in the PR. 
Isn't a predicate supposed to be "part of a sentence"? If so, what does "NAME" mean in the following instance? 

```
        {
            "input": "The route 42, 43 are Mount pleasant line.",
            "output": [
                "NAME"
            ]
        },
```

**Comment by RushangKaria** [comment]
Copying over the comment i made in issue #652.

> Hi @danyaljj

> It looks like the "food" label is the only predicate that actually appears in the sentence.
> Other sentences in this dataset have different special labels that appear as predicates for which there is no documentation.

> I've put up a PR using these special tags however im not sure where to find their definitions.

For the predicates that actually appear in the sentences, "food" appears in most of the cases as observed by the skew. If i remove the code that checks whether the predicate actually appears in the sentence, then the predicates have these special tags which were added by the annotators for the predicates.

Not sure where the definitions for them lie.

**Comment by danyaljj** [comment]
Got it. Let's remove this task.

**Comment by RushangKaria** [comment]
Cool! Should i delete both the file and the entry in README.md?

**Comment by danyaljj** [comment]
Yes

**Pull request merged**
