### PR TITLE
task 282 : Scruples

### PR DESCRIPTION
**Pull request by amirrezamirzaei**
task 282 using scruples Anecdotes dataset.

### CODE REVIEW

**Review by swarooprm — COMMENTED** [review]
Looks good. Some comments:
1. "label the instances" should be "Label the instances" and there should be space after full stop.
2. Mention when to label historical and when hypothetical. E.g. historical when author has already done something, hypothetical when about to do something.

**Review by swarooprm — COMMENTED** [review]
LGTM!

**Review by swarooprm — APPROVED** [review]
LGTM!

**Comment by Palipoor** [comment]
Hi @amirrezamirzaei
Is this the same SCRUPLES in line 58 of the tasks spreadsheet?

**Comment by amirrezamirzaei** [comment]
hi @Palipoor 
yes its the same! so sorry I made the first task(106) with scruples a while ago so I didn't check the sheet recently

**Pull request merged**
