### PR TITLE
task 170, 191-192: HotpotQA

### PR DESCRIPTION
**Pull request by Mihir3009**
Please review

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! Do you think if it's possible to create other tasks for this dataset? For example:  
 - question generation; 
 - merging/fusing two evidence sentences to make a complex question, 
 - given a question, indicating the relevant sentence from an evidence paragraph. 



FYI @swarooprm

**Comment by Mihir3009** [comment]
Task 170: Answer Generation
Task 191: Question Generation
Task 192: Facts Generation

Please review. I will add more tasks on HotpotQA.

**Comment by danyaljj** [comment]
looks good ro me.

**Review by swarooprm — COMMENTED** [review]
1. [Minor] Task 170: Category should be answer generation and not question answering.
2. See if it makes sense to add a 4th task where the input is supporting facts, output is a question and then a 5th task where input is supporting facts, question, and output is answer. Basically, see if it is possible to create task by getting rid of the passage.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
