### PR TITLE
Task 344-347 and Task 382: HybridQA

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on: https://arxiv.org/pdf/2004.07347.pdf
I wasn't sure if I could add another answer generation task like task 347, which asks about the part-of-speech tag of one word in the question.

I recognized I hadn't shuffled dream and duorc datasets before; I fixed them in this PR.

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mirzyaaliii, can you review these tasks?

**Comment by Mirzyaaliii** [comment]
> Based on: https://arxiv.org/pdf/2004.07347.pdf
> I wasn't sure if I could add another answer generation task like task 347, which asks about the part-of-speech tag of one word in the question.
> 
> I recognized I hadn't shuffled dream and duorc datasets before; I fixed them in this PR.


General comments for all 4 tasks

-> Please add more negative examples which help to understand which kind of output is not allowed for that particular task.
-> With research paper also include a dataset link in the source (see task 164).

- Task 344: 
-> Can you elaborate more on the definition??

- Task 345:
-> Looks good to me just add negative examples.
-> In the negative examples you can add something like this - the input sentence has 5 words but output generates POS for fewer words than in input.

- Task 346:
-> Please modify the description of this task (in README), it sounds a little confusing.

- Task 347:
-> In this task instead of question in the input, you can just simply form your input like this -
`
"input": write_your_input_question \n Word: word_from_question_for_which_you_want_POS,
"output": POS_of_the_given_word
`
The above form of input is a bit easier to understand or you can just simply change your input like this -
`
"input": "What is the part-of-speech tag of the word \"the\" in the following question: Who were the builders of the mosque in Herat with fire temples ?",
"output": "IN"
`
-> Also, as suggested by you, you can create a new task that generates the right POS of the given word in output (which is the same as this task except for the right answer).

**Comment by yeganehkordi** [comment]
Thanks for the comments. I updated the tasks.

**Comment by danyaljj** [comment]
Thanks! The PR makes changes to DuoRC-related tasks. Are these intentional?

**Comment by yeganehkordi** [comment]
Thanks! Yes, I hadn't shuffled dream and duorc instances before; I fixed them in this PR.

**Comment by Mirzyaaliii** [comment]
> Thanks for the comments. I updated the tasks.

Looks good to me, @swarooprm do a final check and merge.

**Pull request merged**
