### PR TITLE
Tasks 271-273: Europarl

### PR DESCRIPTION
**Pull request by Mihir3009**
2 Sentence Generation Tasks and 1 Classification Task. Please review.

### CODE REVIEW

**Review by yeganehkordi — COMMENTED** [review]
Thanks! Looks good to me. 
We already have the "Translation" category in the tasks. I think this would be a better category for the first two tasks.

**Comment by Mihir3009** [comment]
> "Translation" category

I updated the "Translation" category for the first two tasks. Thanks.

**Comment by danyaljj** [comment]
Please use the language indicators as suggested in #113

**Comment by Mihir3009** [comment]
> Please use the language indicators as suggested in #113

Resolved and files are updated.

**Review by swarooprm — APPROVED** [review]
Looks good!
We have relatively fewer multi-lingual tasks, so more tasks are encouraged.
Make sure that you and @Mehrad0711 don't end up creating the same task.

**Pull request merged**
