### PR TITLE
Failing tests in the main branch

### PR DESCRIPTION
**Pull request by yeganehkordi**

### CODE REVIEW

**Review by swarooprm — APPROVED** [review]
LGTM

**Comment by yeganehkordi** [comment]
@danyaljj We can change the test file to have a warning for domains instead of asserting errors before assigning all the categories and domains.

**Comment by danyaljj** [comment]
> @danyaljj We can change the test file to have a warning for domains instead of asserting errors before assigning all the categories and domains.

I am happy to force these, otherwise, we might deviate from our hierarchy.

**Comment by yeganehkordi** [comment]
Sounds good!

**Pull request merged**
