### PR TITLE
Task 579-581 Socialiqa

### PR DESCRIPTION
**Pull request by cosmicishan**
task535_socialiqa_answer_generation -> Given a context, a question, and three options; provide the correct answer for the question based on the context.
task536_socialiqa_classification -> Given a context, a question, and an answer; classify whether the answer is correct or not.
task537_socialiqa_question_generation -> Generate a question based on the given context and an answer.

### CODE REVIEW

**Comment by swarooprm** [comment]
Renamed this PR to 579-581 as tasks till 578 are already taken.
https://github.com/allenai/natural-instructions-expansion/pull/271

Please rename your files.

**Comment by swarooprm** [comment]
@colinzhaoust, wondering if you can help review this PR?

**Comment by cosmicishan** [comment]
Also, please suggest to me another task I can create from this dataset.
Thanks in advance!!

**Review by swarooprm — APPROVED** [review]
LGTM!
File names and task numbers were swapped in the readme, I fixed that. 
I assume class labels are balanced in the classification task, if not please fix in your next PR.

More task suggestions: Whenever you have an MCQ dataset, apart from creating the regular MCQ task, you can always create an answer generation and an incorrect answer generation task similar to Task004 and Task005.

**Pull request merged**
