### PR TITLE
Task 402 and 404 from grailqa. 

### PR DESCRIPTION
**Pull request by Palipoor**
source paper:
https://arxiv.org/pdf/2011.07743.pdf

Another task(s) yet to come.

### CODE REVIEW

**Comment by danyaljj** [comment]
- I think you can drop this: "Endeavor to fully understand the original question."
- In the examples and instances, should we include a separator before "answer type:" to make it easier to distinguish from the answers that come before it? Similarly, might be good to separate "auxiliary information". For example, "\n auxiliary information: " (\n before and colon after).

**Comment by Palipoor** [comment]
>     * I think you can drop this: "Endeavor to fully understand the original question."
> 
>     * In the examples and instances, should we include a separator before "answer type:" to make it easier to distinguish from the answers that come before it? Similarly, might be good to separate "auxiliary information". For example, "\n auxiliary information: " (\n before and colon after).

done. thanks!

**Comment by eshaanpathak** [comment]
Please remove the extra lines added to `tasks/README.md` from line 265 to 333. And make sure you add your tasks in the right order. The checks should pass then. New checks and edits were added in #224 if you want to see what they are.

**Comment by eshaanpathak** [comment]
It seems like you made a lot of changes to the overall approved edits I made in #224, as can be seen in the "Files changed" tab. Please revert back and just add tasks 402 and 404.

**Comment by Palipoor** [comment]
> It seems like you made a lot of changes to the overall approved edits I made in #224, as can be seen in the "Files changed" tab. Please revert back and just add tasks 402 and 404.

I think it's ok now. sorry.

**Comment by eshaanpathak** [comment]
No worries. Merge conflicts can be annoying lol.

The README.md is still changed in other places. Maybe take a look at the "Files changed" tab and make those changes by hand? Not sure what the best way to fix it is otherwise.

@danyaljj @swarooprm Any advice on how to fix this?

**Comment by Palipoor** [comment]
Now I just copied the readme from #224 and added 402 and 404 at the end.

**Pull request closed without merging**
