### PR TITLE
Task 901-1000 Updated Files

### PR DESCRIPTION
**Pull request by aarunku5**

### CODE REVIEW

**Comment by aarunku5** [comment]
Created this to fix the other PR, because I don't have the write permission to resolve the conflict.

There's some error in translation task 914 that's occurring, not sure how to address this?

**Comment by danyaljj** [comment]
The merge is not done correctly. 
In some of the files (e..g, `task914_bianet_translation`) you're changing the definition and examples.

**Comment by aarunku5** [comment]
Thanks, have updated the files

**Comment by swarooprm** [comment]
Categories are good to go. @danyaljj

**Pull request merged**
