### PR TITLE
Task 1161-1164 Coda19

### PR DESCRIPTION
**Pull request by cosmicishan**
task1161_coda19_title_generation -> Given a paragraph from a research paper, your task is to generate the title of the paper 
task1162_coda19_title_classification -> Given a paragraph from the research paper and the title, your task is to classify whether the title belongs to the paper. 
task1163_coda19__section_classification -> Given a sentence from a research paper, your task is to classify among the section the sentence belongs to. 
task1164_coda19__section_correction_classification -> Given a sentence from a research paper and the section, your task is to classify whether the sentence belongs to that sentence.

Please Review.

### CODE REVIEW

**Comment by danyaljj** [comment]
@mishra-sid  wondering if you can review this PR?

**Comment by mishra-sid** [comment]
@danyaljj Sure I'll have a look now  and make some comments/suggestions.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by cosmicishan** [comment]
@swarooprm @danyaljj  Can I get someone to review these tasks?

**Comment by danyaljj** [comment]
@cosmicishan please update the thread when you're done addressing @mishra-sid 's suggestions.

**Comment by cosmicishan** [comment]
All the changes are done.
Please review again. @mishra-sid

**Comment by swarooprm** [comment]
> All the changes are done. Please review again. @mishra-sid

@mishra-sid, check if you are happy or have any other concern?

**Comment by danyaljj** [comment]
Thanks @cosmicishan! I also added the category definitions from the corresponding paper. 
Will merge upon green!

**Pull request merged**
