### PR TITLE
Tasks 1425-1428 and 1317-1322

### PR DESCRIPTION
**Pull request by sumantapatro**

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi! Sorry I saw your previous PR and I numbered two tasks as 1315 and 1316. Can you update your task number to be 1317?

**Review by sumantapatro — COMMENTED** [review]
Removed duplicate entry in the task json file

**Review by sumantapatro — COMMENTED** [review]
Updated task_1319

**Review by sumantapatro — COMMENTED** [review]
Updated task_1319

**Review by sumantapatro — COMMENTED** [review]
Updated task1320.

**Review by sumantapatro — COMMENTED** [review]
Updated Task 1317-1321

**Comment by aarunku5** [comment]
Thanks, here are the comments for your tasks:

1317- Can you specify the output format in the definition i.e., it is '+' followed by the number
1318- Indicate in the definition that some countries have multiple national dishes and to name any one
1319- Your output is like this "030 – 039" in the instances. Either modify the definition to state specify the range, or modify the instance outputs to be a comma separated list and specify that one prefix  is enough for output in the definition.
1320- Specify that the output is "." followed by the domain
1321- Rephrase the definitions and explanations to say "the continent to which the country belongs"
1322- Add a sentence to the definition with a list of possible government types that can be the answer. It would also be good if you specified the year in the definition -- "government type as of the year ___"-- since it can fluctuate over time.

**Review by sumantapatro — COMMENTED** [review]
Updated task1319 and task1320 Definition

**Comment by sumantapatro** [comment]
Updated definitions of tasks 1317-1322

**Comment by aarunku5** [comment]
Thanks, I made a couple of edits to the definitions in 1317, 1318, 1320, 1321, they are good to go now.

Couple of changes you need to make:

In 1319, can you change the instances which have ranges as follows:
"input":"United States drugs",
 "output":[ "030","031", "032","033", "034","035", "036","037", "038","039"]

In 1322, in the defintion, you need to be more explicit about the possible answer choices.
The second sentence should be: "The following are possible government types that are considered valid answers: _____"
List every unique government type from your instances in that space.

**Review by sumantapatro — COMMENTED** [review]
updated ReadMe

**Comment by swarooprm** [comment]
@sumantapatro 
For the tests to pass, You need to have 3 new fields in each task json:
Since everything in your tasks are in English, you can add these 3 lines to your files
"Input_language": [
"English"
],
"Output_language": [
"English"
],
"Instruction_language": [
"English"
]

You can also check any task jsons in the repo, they now have these fields (we have recently updated all of them)

**Comment by aarunku5** [comment]
> Thanks, I made a couple of edits to the definitions in 1317, 1318, 1320, 1321, they are good to go now.
> 
> Couple of changes you need to make:
> 
> In 1319, can you change the instances which have ranges as follows: "input":"United States drugs", "output":[ "030","031", "032","033", "034","035", "036","037", "038","039"]
> 
> In 1322, in the defintion, you need to be more explicit about the possible answer choices. The second sentence should be: "The following are possible government types that are considered valid answers: _____" List every unique government type from your instances in that space.

@sumantapatro can you fix these 2 tasks? The rest looks good to go

**Comment by sumantapatro** [comment]
Updated task1322 Definition

**Comment by sumantapatro** [comment]
Updated task1319

**Comment by sumantapatro** [comment]
Updated task1319 definition and instances

**Comment by sumantapatro** [comment]
Added Task 1425 and 1426

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by aarunku5** [comment]
I've modified the definitions for 1322, 1425-1428.

In 1427, can you list the unique region names (similar to what you did for government types in 1322)? Rest of the tasks are good to go.

**Pull request merged**
