### PR TITLE
Task1447-1453 and Tasks 1479-1497 Drug_Extraction

### PR DESCRIPTION
**Pull request by Ishani-Mondal**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Ishani-Mondal, I have fixed the key issue. But, now the issue is: output of instances is not a list. I am not able to change it here, could you make each output of instances a list?

**Comment by Ishani-Mondal** [comment]
> @Ishani-Mondal, I have fixed the key issue. But, now the issue is: output of instances is not a list. I am not able to change it, could you make the each output of instances a list?

Sure, thanks a lot @swarooprm, it was really helpful.

**Comment by Ishani-Mondal** [comment]
@swarooprm , hi it seems to me that even if I am uploading a version, the build is running on the older version.

**Comment by swarooprm** [comment]
> @swarooprm , hi it seems to me that even if I am uploading a version, the build is running on the older version.

I deleted the old file, now task1447 is passing tests. Now, lets add task1448 to readme and tests should pass. @Ishani-Mondal

**Comment by Ishani-Mondal** [comment]
@

> > @swarooprm , hi it seems to me that even if I am uploading a version, the build is running on the older version.
> 
> I deleted the old file, now task1447 is passing tests. Now, lets add task1448 to readme and tests should pass. @Ishani-Mondal

A huge thanks to you. I got intimidated when the changes were not reflected, but I didn't notice that it was coming from the latest one. I will try to upload the other files as well.

**Comment by swarooprm** [comment]
tests are green now. I had a quick look at your task, it looks good. Just one question: task1447 and 1448 seem to be same (?)

**Comment by Ishani-Mondal** [comment]
> tests are green now. I had a quick look at your task, it looks good. Just one question: task1447 and 1448 seem to be same (?)

No no. I was actually uploading different files to check if the problem could be resolved. I have updated 1448. It is the task of disease extraction from NCBI Dataset.

**Comment by swarooprm** [comment]
@mattf1n, wondering if you can help review these tasks?

**Comment by swarooprm** [comment]
@gkaramanolakis, can you review tasks in this PR?

**Comment by gkaramanolakis** [comment]
The tasks look good to me. Below are some comments: 

First, there are some inconsistencies in the output formats for some tasks:

- For example, in task1447_drug_extraction_ade.json, the "Positive Examples" contain an "output" of type string, while "Instances" contain outputs that are lists. Can you convert all outputs to list format?
- The instruction is to list the tokens mentioning specific types of entities, however it's not clear what the format of the output should be in case of multiple entities appearing in the same sentence. If there is just a single entity in the text by task definition, then this should be clear in the task description (e.g., I see that this is the case in 1447, 1448 but the description is not clear)
- How should we handle cases where the same entity appears multiple times? For example, in task 1448 there's an instance: "_A hot spot for PTEN mutation in **CD** was identified in exon 5 that contains the PTPase core motif , with 13 of 30 ( 43 % ) **CD** mutations identified in this exon ._" that contains "CD" twice. It'd be better to make the task description more precise to address this type of cases. 
- It is weird that all instances have a single entity in the output while there are clearly cases where multiple target entities appear in a sentence. For example, in task 1449, the following sentence "_Anorexigens and pulmonary hypertension in the United States : results from the surveillance of North American pulmonary hypertension ._" contains two diseases: "Anorexigens" and "pulmonary hypertension" but just the second is in the output. Is this an issue with the original labels or with the pre-processing procedure when you created this file? 

Second, there are some syntactic/grammatical/semantic errors in the task description:
- task1448: "list the tokens that mentions" -> "list the tokens that mention" (the same phrase should be corrected in all tasks that it appears).
- task1448, first positive example: Cardiovascular disorder -> cardiovascular disorder (should not be capitalized; the same phrase should be corrected in all tasks that it appears).
- task 1451: "list the tokens which indicate the tokens which determine the doses" ->  "list the tokens which indicate the doses".
- tasks 1488 and 1489: the labels for all instances are wrong: "sarcasatic"->"sarcastic" and "non-sarc asatic"->"non-sarcastic".
- many tasks: "If no information about the participants is mentioned" -> "If no target entities are mentioned".

More corrections: 
- task 1451: in the negative examples, you list "high-dose" as a wrong extraction, but there are many instances that actually have "high-dose" as output. I'd suggest finding a better negative example. 
- task1488: in the negative examples, I'd expect to see at least one mislabeled example, e.g., a sarcastic label that is labeled as non-sarcastic. Same for task 1490 (personal / non-personal), 1491-1494, 1496 and others.
- task 1491: the second positive example is labeled as "religious" while the two classes are "political" and "non-political". 
- task 1494 is the multi-task version of the binary classification tasks 1491-1493. Should this redundancy be an issue? @swarooprm 
- task 1496 is binary (positive/negative) sentiment classification but the task description defines what a *sarcastic* sentence is. 
- I'd suggest changing "task1496_bengali_reviews_sentiment_classification.json" to "task1496_bengali_restaurant_reviews_sentiment_classification.json" to be consistent with the format of task 1497 (bengali_book_reviews)


Category information: 
- task1452_location_entity_extraction_btc_corpus.json should not be listed under "Biology -> Clinical Knowledge".

Optionally, some of those tasks could be expressed as NER tasks ([Issue 95](https://github.com/allenai/natural-instructions-expansion/issues/95)).

**Comment by swarooprm** [comment]
> Reviewed all files

thanks @gkaramanolakis for your detailed review.
task 1494 redundancy is not an issue.

@Ishani-Mondal, could you address reviewer comments?

**Comment by Ishani-Mondal** [comment]
> > Reviewed all files
> 
> thanks @gkaramanolakis for your detailed review. task 1494 redundancy is not an issue.
> 
> @Ishani-Mondal, could you address reviewer comments?

Sure @swarooprm , I will address these as early as I can.

**Comment by Ishani-Mondal** [comment]
Point 1,2,3 : Addressed in the task descriptions and modified the task outputs as lists.
Point 4: It seems that the original dataset contained these annotations.

Other minor comments by the reviewer have also been addressed. 

@swarooprm , please let me know what else needs to be done.

**Comment by swarooprm** [comment]
@gkaramanolakis, check if you are happy or have any other comments?

**Comment by swarooprm** [comment]
> @gkaramanolakis, check if you are happy or have any other comments?

A gentle reminder @gkaramanolakis

**Review by gkaramanolakis — COMMENTED** [review]
Thanks for all the updates! I just checked all the files and they look good to me.

**Comment by swarooprm** [comment]
Thanks @gkaramanolakis 
@Ishani-Mondal, can you resolve the merge conflicts in the readme file so that we can go ahead and merge this PR?
I tried to do it in UI, but am unable to do so. You need to do it in the command line.

**Comment by Ishani-Mondal** [comment]
@swarooprm , sure, but could you please come on a call sometime so it I would be able to quickly resolve the same?

**Comment by Ishani-Mondal** [comment]
> Thanks @gkaramanolakis @Ishani-Mondal, can you resolve the merge conflicts in the readme file so that we can go ahead and merge this PR? I tried to do it in UI, but am unable to do so. You need to do it in the command line.

@swarooprm , sure, but could you please come on a call sometime so that I would be able to quickly resolve the same?

**Review by swarooprm — APPROVED** [review]
Fixed error and updated several things in all the files.
Good to merge now.

**Pull request merged**
