### PR TITLE
Task 933 Style Transfer (Simplify Sentences)

### PR DESCRIPTION
**Pull request by garyhlai**
- Instructions for simplifying wikipedia sentences. Input is normal wikipedia sentence, output is the aligned wikipedia sentence in simple English. 
- Created based on the HuggingFace dataset "wiki_auto"
- **Citation:**
        @inproceedings{acl/JiangMLZX20,
          author    = {Chao Jiang and
                       Mounica Maddela and
                       Wuwei Lan and
                       Yang Zhong and
                       Wei Xu},
          editor    = {Dan Jurafsky and
                       Joyce Chai and
                       Natalie Schluter and
                       Joel R. Tetreault},
          title     = {Neural {CRF} Model for Sentence Alignment in Text Simplification},
          booktitle = {Proceedings of the 58th Annual Meeting of the Association for Computational
                       Linguistics, {ACL} 2020, Online, July 5-10, 2020},
          pages     = {7943--7960},
          publisher = {Association for Computational Linguistics},
          year      = {2020},
          url       = {https://www.aclweb.org/anthology/2020.acl-main.709/}
        }

### CODE REVIEW

**Comment by danyaljj** [comment]
@ghlai9665 thanks for the PR! Wondering if there is anything else we can say about what it means to have a "simpler" sentence?

**Comment by danyaljj** [comment]
Thanks! Leaving it for @swarooprm to give it a 2nd look.

**Comment by garyhlai** [comment]
> @ghlai9665 thanks for the PR! Wondering if there is anything else we can say about what it means to have a "simpler" sentence?

@danyaljj Just pushed another commit to elaborate further on the definition. 

By the way, I think it might be a good idea to incorporate format (e.g. boldface) in these instructions to help the model know which words to pay particular "attention" to (just like for humans).

For example: "In this task, we ask you to rewrite the sentence in simple English without changing its general meaning. Essentially, you want to make the sentence [bold] easier to read [/bold] by using simpler words, utilizing more straightforward sentence structures, and omitting non-essential information etc."

What do you think?

**Comment by danyaljj** [comment]
> > @ghlai9665 thanks for the PR! Wondering if there is anything else we can say about what it means to have a "simpler" sentence?
> 
> @danyaljj Just pushed another commit to elaborate further on the definition.
> 
> By the way, I think it might be a good idea to incorporate format (e.g. boldface) in these instructions to help the model know which words to pay particular "attention" to (just like for humans).
> 
> For example: "In this task, we ask you to rewrite the sentence in simple English without changing its general meaning. Essentially, you want to make the sentence [bold] easier to read [/bold] by using simpler words, utilizing more straightforward sentence structures, and omitting non-essential information etc."
> 
> What do you think?


That's an interesting suggestion, which we probably need to address as future work.

**Comment by swarooprm** [comment]
@ghlai9665 I like this task, but I see sometimes the output is longer than the input. When I read the definition- "omitting non-essential information", I get the feeling that output will be shorter than the input.
"input": "Rocky Balboa is a 2006 American boxing sports drama film written , directed by , and starring Sylvester Stallone .\n",
            "output": [
                "Rocky Balboa -LRB- also known as Rocky VI -RRB- is the sixth and final movie in the Rocky series , written , directed by and starring Sylvester Stallone .\n"
            ]

**Comment by danyaljj** [comment]
> @ghlai9665 I like this task, but I see sometimes the output is longer than the input. When I read the definition- "omitting non-essential information", I get the feeling that output will be shorter than the input. "input": "Rocky Balboa is a 2006 American boxing sports drama film written , directed by , and starring Sylvester Stallone .\n", "output": [ "Rocky Balboa -LRB- also known as Rocky VI -RRB- is the sixth and final movie in the Rocky series , written , directed by and starring Sylvester Stallone .\n" ]

That's a good observation. I think `-LRB` and `-RRB-` should be replaced with `(` and `)` (https://github.com/UniversalDependencies/UD_English-EWT/issues/1).

**Comment by danyaljj** [comment]
Also, we should drop all the `\n` tags at the end of each sentence.

**Comment by garyhlai** [comment]
@danyaljj @swarooprm Done! New commits should address all of the above issues.

**Comment by swarooprm** [comment]
Looks good to me @danyaljj

**Pull request merged**
