### PR TITLE
Task 405 from NarrativeQA

### PR DESCRIPTION
**Pull request by Palipoor**
Will add more tasks from this dataset.

### CODE REVIEW

**Comment by danyaljj** [comment]
@shailaja183 wondering if you can review this PR?

**Comment by shailaja183** [comment]
Task 405 looks good mostly, just a couple of minor comments;
1. Negative example explanation - instead of "two-part question", I would suggest to write "do not combine multiple questions"
2. Negative example explanation says that "The names in parantheses are the names of the actors and they shouldn't be in your question. Only ask questions with character names." -- also add this in the definition 
3. Typos - charracters, parantheses

**Comment by danyaljj** [comment]
@shailaja183 check if the changes look good to you?

**Comment by shailaja183** [comment]
looks good to me!

**Comment by swarooprm** [comment]
@Palipoor: this task looks good and I am ready to merge as soon as the following comment gets addressed:
In the definition, replace "questions" with "a question". We expect model to generate a single question, so let's say that.

**Comment by swarooprm** [comment]
Suggested Definition: 
"You will be given a summary of a story. You need to create a question that can be answered from the story. You can create a question about characters, events, facts and beliefs, etc. Your question should be specific, try not to use pronouns instead of full names. As the stories are sometimes movie plots, they will contain actor names in parentheses. You should not use those names. Only use character names. Try to ask a question about all parts of the plot, not just the beginning."

I tried changing it in your branch, but I don't have push access.

**Comment by swarooprm** [comment]
Also, you can create other tasks from NarrativeQA such as answer generation.

**Comment by Palipoor** [comment]
@swarooprm I changed the definition. Sure, I will create other tasks as well!

**Comment by swarooprm** [comment]
> @swarooprm I changed the definition. Sure, I will create other tasks as well!

Great! That was quick!

**Review by swarooprm — APPROVED** [review]

**Pull request merged**
