### PR TITLE
Tasks 1323-1330

### PR DESCRIPTION
**Pull request by abhilashreddyy**
-> Added task related to question generation, answer generation, language translation and classification
-> These tasks were already checked during the assignment.

### CODE REVIEW

**Comment by aarunku5** [comment]
Thanks, can you renumber your tasks? Below are the comments for the tasks with your current numbering:

1317- 
Remove "The task is" from the definition, and combine the first 2 sentences into a single sentence to be more concise.
Can you define relation more clearly in the definition (may give a couple of examples).
Couple of grammatical errors in the definition, please fix those, and ":" before you start listing rules for the question.
In your explanations, split the sentences into multiple shorter sentences to improve the clarity.

1318-
Definition's first sentence: "Read the context and answer from the given input and generate a question which can yield the answer."
Change to "dataset: 1."
Couple of grammatical errors in the definition and explanations, please fix those

1319-
Change definition's first sentence like 1318
Change to "answers: 1."
Couple of grammatical errors in the explanations, please fix those.

1320-
Change first sentence to:
"The task is about reading the context and classifying the relation of question with respect to the context. The relation will be from among the following categories: 1)...."
Specify that output format must be the category itself (not the numbering)
Couple of grammatical errors in the definition and explanations, please fix those

1321-
Capitalize English and Hindi
Have ":" before listing rules
Couple of grammatical errors in the definition, please fix those

1322-
Capitalize English and Telugu
Have ":" before listing rules
Couple of grammatical errors in the definition, typo for capitalization in the explanations, please fix those

1323- 
See 1321

1324-
See 1322

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
@abhilashreddyy, can you address reviewer comments?

**Comment by swarooprm** [comment]
> @abhilashreddyy, can you address reviewer comments?

A gentle reminder! @abhilashreddyy

**Pull request merged**
