### PR TITLE
Task 329-331: GAP

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on: https://arxiv.org/pdf/1810.05201.pdf   #174

### CODE REVIEW

**Comment by swarooprm** [comment]
@Mihir3009, can you review these tasks?

**Comment by swarooprm** [comment]
@Mehrad0711, wondering if you can review these tasks?

**Comment by Mehrad0711** [comment]
Thanks for your work!

In all three tasks I think it would be better to replace "\n" with a non-escaping character to avoid unwanted line splits when reading the file. Perhaps a special token like `<sep>` which can be added to the tokenizer special vocab list.

Was wondering what the motivation is behind `gap_incorrect_answer_generation` task? Is there a specific use-case for a model trained to generate wrong answers?

In the classification task, I noticed 4 labels are introduced but "Both" and "Neither" are not used in any other instances besides positive and negative examples. Maybe some examples can be added for those. Also, wondering if "Both" makes sense at all? The examples are designed not to have overlapping references afaiu.

Also please add 1 more example for positive and 1 more example for negative instances. The tests are not catching this right now (PR #216).

It looks good to me otherwise.

**Comment by yeganehkordi** [comment]
Thanks for your comments!
I updated the tasks based on the comments.
For the incorrect answer generation task, I followed the task types that were created by Daniel and Swaroop. I'm not sure about the motivation, but I think some questions can be easily answered by the system without actually understanding the concept. If a system can pass both answer generation and wrong answer generation tasks with high precision, we can have a better evaluation of its understanding.

**Comment by swarooprm** [comment]
Thanks @yeganehkordi.
@Mehrad0711, please let us know if you are happy with the PR or have any suggestions?

**Comment by Mehrad0711** [comment]
Yes, this looks good to me now. Thanks.

**Pull request merged**
