### PR TITLE
Task 348-349: Squad2.0

### PR DESCRIPTION
**Pull request by shailaja183**
task348: squad2.0_unanswerable_question_generation- Given paragraph, generate questions that cannot be answered using paragraph
task349: squad2.0_answerable_unanswerable_question_classification- Given paragraph and a question, determine whether it is answerable or not

### CODE REVIEW

**Comment by swarooprm** [comment]
@amirrezamirzaei, can you review these tasks?

**Comment by amirrezamirzaei** [comment]
looks good to me. some minor comments:
1-Im not sure about this but the definition for task 349 could be a lot shorter. take a look at task 50 or 290 definition. also its better if the name of task 349 has the same format as task 50 & 290. (its also better if you label the instances as “True” if the question is answerable.)
2-in task 349 examples `second sentence of the paragraph-` remove the ‘-‘. there is no need to write the sentence that the answer is found in but if you want to do it put the sentence in double quotes.
3-in task 348 definition `but it is unanswerable` should be `but is unanswerable` . `Following are few suggestions` should be `Following are a few suggestions` . use "." instead of ";".  also typo in `quesitons`.
4-remove the ‘-‘ in task 348 examples also.
5-also can you use the same order we use for every task json fields (Contributors-Source-...).
6-in task 348 definition in the readMe file `generate question` should be `generate a question`

**Comment by shailaja183** [comment]
@amirrezamirzaei fixed all of your comments. Please verify and let me know if I missed out anything.

**Comment by amirrezamirzaei** [comment]
thanks for the changes! a few other minor comments.
1 - you missed removing the '-' from the examples. also you missed fixing `Following are few suggestions`.
2-task 349 categories should be Classification (in the json file)
3- also can you remove the `Carefully read the given passage and a question.` in 349 definition. maybe change it to `In this task you are given a passage and a question regarding that passage. You must determine ...`
4-can you remove the space between the json file fields(Contributors-Source-...)? it ins't really important but our other task don't have it.

**Comment by shailaja183** [comment]
Please review.

**Comment by amirrezamirzaei** [comment]
looks good to me 2 minor comments
1-in task 349 `you are given passage` should be `you are given a passage`.`answerable from a given passage` should be `answerable from the given passage`
2-there still spaces between the json file fields.(you only removed the space between Contributors and source)

**Comment by shailaja183** [comment]
Please review.

**Comment by amirrezamirzaei** [comment]
looks good to me!

**Comment by danyaljj** [comment]
Relevant PR #32

PS. I am not able to find the tasks added in #32 in the repo. It's possible that it was deleted mistakenly by a subsequent PR. Or I might be losing my mind. Any thoughts?

**Comment by shailaja183** [comment]
I added squad2.0 tasks previously but had some pending changes after review by @danyaljj, then due to the problem of repeat instances, the branch for squad2.0 was deleted. 
Not sure what I have to do in this case. Please guide me and I will fix.

**Comment by danyaljj** [comment]
I am actually not sure what happened. 

I went through the git history and I don't see where it was dropped. But here is one commit where they are available: 
 https://github.com/allenai/natural-instructions-expansion/tree/fa802e9092ff01c3016c4fef692617d4fb1e8f7a/tasks

At any rate, it's good that we're bringing them back in.

**Pull request merged**
