### PR TITLE
Task-223: QuaRTz

### PR DESCRIPTION
**Pull request by Mirzyaaliii**
Another task from the QuaRTz dataset - Task223_QuaRTz_explanation_generation

Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Looks good! 

For the QA task, it would be helpful to say that one should write the answer string (as opposed to "option 1/2"). 

Otherwise, it looks good to me!

**Comment by swarooprm** [comment]
Looks good to me. Please do git pull so that the conflict gets resolved. I will then be able to approve and merge PR.

**Comment by swarooprm** [comment]
I am not able to resolve conflict here, you need to do 'git pull' to resolve conflicts.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
