### PR TITLE
Task 281 Points of Correspondence detection

### PR DESCRIPTION
**Pull request by Palipoor**

### CODE REVIEW

**Review by Maitreyapatel — COMMENTED** [review]
Looks good to me. But there is an issue with output of second negative example. "sentence 2" is missing and "sentence" is missing from "sentence 3". 
Also, can you add the link to the paper or dataset ?

**Comment by Palipoor** [comment]
@Maitreyapatel   thanks. Fixed them. The missing "sentence 2" was intentional.

**Review by Maitreyapatel — COMMENTED** [review]
It make sense. Thanks for the update!

**Review by swarooprm — APPROVED** [review]
I like this task. This adds to task diversity.
We might need to keep it in training spilt though since annotations are not always reliable.

**Comment by swarooprm** [comment]
Also see if you can create more tasks from the same data. Say by dividing it based on place, person or thing (if those data is already separated) or by asking to generate the type of entity etc.

**Comment by Palipoor** [comment]
@swarooprm Sure! thanks.

**Pull request merged**
