### PR TITLE
Task 650-663: ParsiNLU-translation

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on: https://arxiv.org/pdf/2012.06154.pdf

### CODE REVIEW

**Comment by swarooprm** [comment]
@aarunku5, wondering if you can help review this tasks?

**Comment by aarunku5** [comment]
Thanks!
654, 655- In the definition, make it 'the Bible'
656, 657- In the definition, make it 'the Quran'
The rest look good.

**Comment by yeganehkordi** [comment]
Thanks! I fixed it.

**Comment by aarunku5** [comment]
Thanks! @swarooprm all the tasks look good here.

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
