### PR TITLE
Task 521 - classification from QANTA

### PR DESCRIPTION
**Pull request by Palipoor**
I added this task from QANTA (https://people.cs.umass.edu/~miyyer/qblearn/index.html) 
I wanted to add the question answering task too, but it's a trivia and needs external knowledge. Is it ok to do this? @swarooprm @danyaljj

### CODE REVIEW

**Comment by swarooprm** [comment]
I think we had some task from QANTA already in the repo. please check.
Also, seems like we have tasks from 517-520 already https://github.com/allenai/natural-instructions-expansion/pull/197

**Comment by Palipoor** [comment]
I couldn't find the other task from QANTA. I renamed the file though.

**Review by swarooprm — COMMENTED** [review]
This task looks good.
Some minor comments.
- The text is talking about anauthor and their works, so it belongs to theliterature category-->The text is talking about an author and their works, so it belongs to the literature category
- Also I would mention about '|||' in the definition since it's not normal to have these in instances.

**Comment by Palipoor** [comment]
Fixed! Thanks.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
