### PR TITLE
Task 193-194: DuoRC

### PR DESCRIPTION
**Pull request by yeganehkordi**
Two additional tasks, one for question generation and the other for answer generation on DuoRC

### CODE REVIEW

**Comment by swarooprm** [comment]
Hey, Thanks for the PR. Task 191-192 already taken (https://github.com/allenai/natural-instructions-expansion/pull/107), please rename your tasks as 193-194.

**Comment by yeganehkordi** [comment]
Thanks! Done.

**Comment by danyaljj** [comment]
Thanks, the task descriptions look good to me! We can move ahead after https://github.com/yeganehkordi/natural-instructions-expansion/pull/1 is merged. 

For future PRs: we used to follow "Emphasis & Caution:" and "Things to avoid" in the past; but since a while ago, we have decided to deviate from this rule and use the natural structure/phrasing of the tasks (i.e., just state the task as-is, without adding such artificial structures).

**Comment by yeganehkordi** [comment]
Thanks for telling me, I didn't notice it before! I'll use the natural structure/phrasing of the tasks for future tasks.

**Comment by danyaljj** [comment]
Looks good to me! @swarooprm

**Review by swarooprm — COMMENTED** [review]
Looks good. 
One Question: Did you use the original crowdsourcing template to write instructions?

**Comment by yeganehkordi** [comment]
Thanks,
Yes, I used their own crowdsourcing templates.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
