### PR TITLE
Downsampling skewed tasks

### PR DESCRIPTION
**Pull request by yeganehkordi**
Addressing the tasks in #427

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! I am waiting for us to merge #447, before moving on with this.

**Comment by yeganehkordi** [comment]
Sounds good! Thanks!

**Comment by danyaljj** [comment]
@yeganehkordi looks like most of these tasks were changed by other PRs. 
Did you use a script for downsampling? If so, how about we check in your script (so that we don't lose it) and we will apply it at some point when assigning category labels is done.

**Comment by yeganehkordi** [comment]
Yeah, I've added the script. I can resolve the merge conflicts later after updating the categories and addressing the feedback or drop the tasks to run the script later.

**Comment by danyaljj** [comment]
I will address this in a different PR. 
Closing this ...

**Comment by yeganehkordi** [comment]
Sounds good!

**Pull request closed without merging**
