### PR TITLE
Synthetic data 

### PR DESCRIPTION
**Pull request by nrjvarshney**
tasks
`task085_unnatural_addsub_arithmetic`	|  Performing Arithmetic with swapped operator symbols.	| Arithmetic
`task086_translated_symbol_arithmetic`	|  Performing Arithmetic with translated operator symbols.	| Arithmetic
`task087_new_operator_addsub_arithmetic`	|  Performing Arithmetic with newly defined operator symbols.	| Arithmetic
`task088_identify_typo_verification`	|  Identifying typo in a sentence.	| Verification
`task089_swap_words_verification`	|  Identifying swapped words in a sentence.	| Verification
`task090_equation_learner_algebra`	|  Answering based on the given equation.	| Algebra
`task092_check_prime_classification`	|  Finding whether the number is prime or not.	| Mathematics

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! 

Several issues: 

 - "continuous words" -> Consecutive words? 
 - "task089_swap_words_verification.json" --> mention the first word has index 1. 
 - "task090_equation_learner_algebra.json":  I think the inputs should be reformulated so that the inputs are easier to read (for humans, at least). For example, `[1,[1,2]]` could be `X=1, equation weights = [1,2]`. This should make your definitions easier to follow as well (which is currently difficult to follow). In the same task, "order" is not clear. Also, from the definition, not clear whether `[a, b]` should be interpreted as `a + bx` or `b + ax`.

**Comment by swarooprm** [comment]
Please pull and merge with the main branch. That should trigger the new automatic tests.

**Comment by danyaljj** [comment]
My last batch of comments, all on the "primer number classification task": 
 - "prime number" define what it means to be a prime number. e.g., `A "prime number" is a a whole number above 1 that can not be made by multiplying other whole numbers`
 - Update the explanations so that it reflects "why". E.g., "100 is not a prime number because ...." or "12 is not a prime number because ...."  
Feel free to merge after addressing these.

**Review by swarooprm — APPROVED** [review]

**Comment by danyaljj** [comment]
There is some feedback from crowd workers regarding your task(s), summarized here: 
https://github.com/allenai/natural-instructions-expansion/pull/276#issuecomment-942714679
Wondering if you can address the feedback?

**Pull request merged**
