### PR TITLE
Task 132: DAIS Dataset

### PR DESCRIPTION
**Pull request by Mirzyaaliii**
Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks for the PR! 

 - I am a bit fuzzy on the task. Initially, I thought this is a paraphrasing task, but now I am not sure. In other words, what does `semantically similar sentence for a given sentence` mean here? 
 - what does `same context` mean? (make makes two sentences have the `same context`?) 
 - add negative examples that do not involve grammatical issues 
 - If there are multiple valid outputs for each instance, let's add them. 
 - Please add a link to the original paper, too: https://arxiv.org/pdf/2010.02375.pdf

**Comment by Mirzyaaliii** [comment]
> Thanks for the PR!
> 
> * I am a bit fuzzy on the task. Initially, I thought this is a paraphrasing task, but now I am not sure. In other words, what does `semantically similar sentence for a given sentence` mean here?
> * what does `same context` mean? (make makes two sentences have the `same context`?)
> * add negative examples that do not involve grammatical issues
> * If there are multiple valid outputs for each instance, let's add them.
> * Please add a link to the original paper, too: https://arxiv.org/pdf/2010.02375.pdf

I updated the task file, please review it again.

**Comment by danyaljj** [comment]
Thanks!  
My last suggestion is to add "paraphrasing" to the task types; FYI @swarooprm

**Review by swarooprm — APPROVED** [review]
Have address pending reviewer comments. Looks good! Merging now.

**Pull request merged**
