### PR TITLE
update categories & domains for task 082-100

### PR DESCRIPTION
**Pull request by garyhlai**
- update categories & domains for task 082-100

### CODE REVIEW

**Comment by danyaljj** [comment]
@ghlai9665 let's merge this with the main branch since there has been plenty of changes to the task hierarchy.

**Comment by swarooprm** [comment]
@ghlai9665, are you available to talk today at 5pm? That might be quicker to review than iterating here

**Comment by garyhlai** [comment]
> @ghlai9665, are you available to talk today at 5pm? That might be quicker to review than iterating here

@swarooprm sounds good. send invite please

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
