### PR TITLE
added language tags for tasks 938-954

### LINKED ISSUE #572: Missing language tags
are missing for the following tasks: 
 - 938-943 
 - 944-954 

@tanay2001 could you address this issue?

### PR DESCRIPTION
**Pull request by tanay2001**
fixes #572

### CODE REVIEW

**Comment by tanay2001** [comment]
> fixes #572

not sure if the tests are failing cuz of the changes I have made, should I drop the task which is failing or the language name has to be something else ? would be great if you could help 
@danyaljj

**Comment by danyaljj** [comment]
Based on the fail log, `Odia` is not among ISO languages. But it looks like `Oriya` is an equivalent name that we have.

**Comment by danyaljj** [comment]
Punjabi -> Panjabi

**Comment by tanay2001** [comment]
> Punjabi -> Panjabi

yup , thanks a lot fixed it !

**Pull request merged**
