### PR TITLE
Task 473-474: ParsiNLU-multiple-choice

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on the: https://arxiv.org/pdf/2012.06154.pdf

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi. I think it's better if the task 473 is titled mc question answering, and not classification.

**Comment by yeganehkordi** [comment]
Hi, Thanks for reviewing!
Actually, I'm not sure about the category. I used classification based on Swaroop's comment here:  #172 

> The answer generation task is good, but its mostly a classification task. You can have another task to generate answer (here answer is (A), (B) etc. ,so classification, there the answer will be pure text generation). For example, look at task004 or task002

**Comment by swarooprm** [comment]
We actually had 'answer generation' category which was used when we used to generate text. But, clearly, we don't generate text here. MCQ is the most appropriate category here, feel free to create such a category if it does not exist.

@Palipoor, wondering if you can check and let @yeganehkordi know if you have any other feedback on this PR?

**Comment by yeganehkordi** [comment]
Thanks! I changed the category to the "Multiple-Choice Question". I think we can split this category into Multiple-Choice Question generation and Multiple-Choice Question answering.

**Comment by danyaljj** [comment]
Looks good, thank you all!

**Pull request merged**
