### PR TITLE
fixed #524

### LINKED ISSUE #524: task task903_deceptive_opinion_spam_classification bug
Introduced in #340 
@meghpatel  All instance labels are `true`.

### PR DESCRIPTION
**Pull request by pulkitverma25**
fixed #524

### CODE REVIEW

**Comment by danyaljj** [comment]
Thank you,  @pulkitverma25 !

**Comment by danyaljj** [comment]
Looks like the tests are failing though. 

Also, please drop the task number from this exclusion list: https://github.com/allenai/natural-instructions-expansion/blob/master/src/test_all.py#L120

**Comment by pulkitverma25** [comment]
This is finally ready for review. 
I should've checked the failing tests earlier. Will be more careful in the future.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
