### PR TITLE
Task 432-437: alt (language translation)

### PR DESCRIPTION
**Pull request by SavanDoshi**
English-Hindi
`task432_alt_en_hi_translation` | Given an English language sentence translate it into Hindi language. | Translation
`task433_alt_hi_en_translation` | Given a Hindi language sentence translate it into English language. | Translation
`task434_alt_en_hi_classification` | Given English and Hindi translation pair, check if it is correct or not. | Classification

English-Japanese
`task435_alt_en_ja_translation` | Given an English language sentence translate it into Japanese language. | Translation
`task436_alt_ja_en_translation` | Given an Japanese language sentence translate it into English language. | Translation
`task437_alt_en_ja_classification` | Given English and Japanese translation pair, check if it is correct or not. | Classification

### CODE REVIEW

**Comment by eshaanpathak** [comment]
You should explain why the positive examples are correct instead of just stating they are.

How is this task different from #231? These PRs both look the same to me.

**Comment by eshaanpathak** [comment]
Not sure if you saw my last comment, but you should explain why the output is correct instead of just saying it is. You can see my review in #231 to get a better idea of what I mean.

There are typos in the explanations of the positive examples for `task433_alt_hi_en_translation.json` with "ic".

In the first positive example of `task434_alt_en_hi_classification.json`, "Sentence" in the explanation should be lowercased.

In the positive and negative examples of `task437_alt_en_ja_classification.json`, you should remove the spaces in the outputs on the left and right parts. For example " Yes " should be "Yes".

Also, all of the outputs in the instances of `task437_alt_en_ja_classification.json` are "No" which is unbalanced. I'm guessing this is a bug, but this should be fixed.

**Comment by SavanDoshi** [comment]
@eshaanpathak  thank you for the suggestions. I have made the changes. Please check it again and let me know if anything else needs to be changed.

**Comment by swarooprm** [comment]
@eshaanpathak, check if your concerns are addressed?

**Comment by eshaanpathak** [comment]
@SavanDoshi You should go much more in depth in your explanations instead of just saying one word or one number is correctly translated or that sentence case is preserved. See the tasks and my reviews in #231 as a good example.

There also appears to be numerous grammatical issues and typos throughout a lot of the explanations, so please go through each one of them and fix them.

@swarooprm After Savan incorporates these edits, can you please delegate these tasks to a different reviewer? I'm pretty busy right now, so I won't be able to review his edits and look for other suggestions. Thanks!

**Comment by swarooprm** [comment]
> @SavanDoshi You should go much more in depth in your explanations instead of just saying one word or one number is correctly translated or that sentence case is preserved. See the tasks and my reviews in #231 as a good example.
> 
> There also appears to be numerous grammatical issues and typos throughout a lot of the explanations, so please go through each one of them and fix them.
> 
> @swarooprm After Savan incorporates these edits, can you please delegate these tasks to a different reviewer? I'm pretty busy right now, so I won't be able to review his edits and look for other suggestions. Thanks!

@SavanDoshi, any update on this?

**Comment by SavanDoshi** [comment]
I am updating it. With updated explanation and new tasks. I will update it soon.

**Comment by SavanDoshi** [comment]
@swarooprm I have made all changes that were requested. I have changed the explanation with more details. Also, I ran my every explanation through a grammar checker.

**Comment by SavanDoshi** [comment]
@swarooprm I have created other tasks using ALT in #367.

**Pull request merged**
