### PR TITLE
Task 583-584 Universal Dependency English Parts of Speech Tagging

### PR DESCRIPTION
**Pull request by mishra-sid**
Defined two tasks for Parts of Speech Tagging #94 using  [Universal Dependency English Dataset](https://github.com/UniversalDependencies/UD_English-EWT/blob/master/stats.xml). 
Added an extra input "Position" to the ones suggested to distinguish words present multiple times within a sentence.
Task 583: Universal Dependency English PoS tags **coarse** labels
Task 583: Universal Dependency English PoS tags **fine** labels 

All PoS tags have equal number of instances ( unless very few examples present in original corpus for e.g. XX tag in fine labels, in which case all of its instances are added ).

### CODE REVIEW

**Comment by swarooprm** [comment]
@kushalchawla, wondering if you can help review this PR?

**Comment by danyaljj** [comment]
Two comments: 
 - You mention the word "position": is it assuming that we use a simple space tokenizer (spaces defined boundaries of tokens). We may want to be explicit about it (and also make sure that our instances are consistent with this rule). 


 > The list of part-of-speech tags i.e tagset of this corpus is : 'ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X'."

 - Do you think an average human (say, a crowdworker) can understand what these tags mean? If not, we need to somehow define them.

**Comment by mishra-sid** [comment]
1. The inputs obtained from the dataset were already tokenized ( to perform token-level PoS tagging ). The input format requires it to be a string, which is why I "joined" the input tokens of the original dataset using spaces to form a sentence, so our instances are consistent with it. I can either provide the input as a list of tokens encoded with  ( '[' ',' ']' )   characters  or explicitly mention it to be space tokenized in the task definition. 

2. I think for coarse labels ( Task 583 ), it is reasonable to expect. But fine labels need Parts of speech domain expertise. I can add the explanation of each ( perhaps the definitions of the tags mentioned here [udpos-taglist](https://universaldependencies.org/u/pos/) ? ) of the tags inside the task definition, but that would make it a bit long. Another alternative ( A subset of which I have currently done ) is to define it in the explanation of positive examples. I can do this exhaustively for all of the tags. 

@danyaljj Let me know which options out of these you prefer for both of these responses.

**Comment by danyaljj** [comment]
Thanks! 

> 1. The inputs obtained from the dataset were already tokenized ( to perform token-level PoS tagging ). The input format requires it to be a string, which is why I "joined" the input tokens of the original dataset using spaces to form a sentence, so our instances are consistent with it. I can either provide the input as a list of tokens encoded with  ( '[' ',' ']' )   characters  or explicitly mention it to be space tokenized in the task definition.

Makes sense. Might be good to have a short phrase defining "positions" according to the whitespace. 

> 2. I think for coarse labels ( Task 583 ), it is reasonable to expect. But fine labels need Parts of speech domain expertise. I can add the explanation of each ( perhaps the definitions of the tags mentioned here [udpos-taglist](https://universaldependencies.org/u/pos/) ? ) of the tags inside the task definition, but that would make it a bit long. Another alternative ( A subset of which I have currently done ) is to define it in the explanation of positive examples. I can do this exhaustively for all of the tags.

I am leaning towards your first proposal (having a brief definition). I think the latter is also a good addition.

**Comment by swarooprm** [comment]
> Thanks!
> 
> > 1. The inputs obtained from the dataset were already tokenized ( to perform token-level PoS tagging ). The input format requires it to be a string, which is why I "joined" the input tokens of the original dataset using spaces to form a sentence, so our instances are consistent with it. I can either provide the input as a list of tokens encoded with  ( '[' ',' ']' )   characters  or explicitly mention it to be space tokenized in the task definition.
> 
> Makes sense. Might be good to have a short phrase defining "positions" according to the whitespace.
> 
> > 1. I think for coarse labels ( Task 583 ), it is reasonable to expect. But fine labels need Parts of speech domain expertise. I can add the explanation of each ( perhaps the definitions of the tags mentioned here [udpos-taglist](https://universaldependencies.org/u/pos/) ? ) of the tags inside the task definition, but that would make it a bit long. Another alternative ( A subset of which I have currently done ) is to define it in the explanation of positive examples. I can do this exhaustively for all of the tags.
> 
> I am leaning towards your first proposal (having a brief definition). I think the latter is also a good addition.

@mishra-sid, can you address reviewer comments?

**Comment by mishra-sid** [comment]
Hey @swarooprm , I am currently a bit occupied with an ICLR submission. I'll be submitting the resolved version for this, 2 more tasks for PoS ( PennTreeBank - coarse and fine) and 5 more NER Datasets ( In exactly the same format as this PoS task) by tomorrow EOD. All of these can be simultaneously reviewed and approved.

**Comment by swarooprm** [comment]
> Hey @swarooprm , I am currently a bit occupied with an ICLR submission. I'll be submitting the resolved version for this, 2 more tasks for PoS ( PennTreeBank - coarse and fine) and 5 more NER Datasets ( In exactly the same format as this PoS task) by tomorrow EOD. All of these can be simultaneously reviewed and approved.

Sure. Thanks for letting me know. All the best with your ICLR submission!

**Comment by swarooprm** [comment]
> > Hey @swarooprm , I am currently a bit occupied with an ICLR submission. I'll be submitting the resolved version for this, 2 more tasks for PoS ( PennTreeBank - coarse and fine) and 5 more NER Datasets ( In exactly the same format as this PoS task) by tomorrow EOD. All of these can be simultaneously reviewed and approved.
> 
> Sure. Thanks for letting me know. All the best with your ICLR submission!

@mishra-sid, wondering if you have any update on this?

**Comment by mishra-sid** [comment]
Hey @swarooprm , I have made the requested changes by @danyaljj to this branch. I have also added PennTreeBank and Brown corpus PoS Tags in #380 . Both of these can be approved/merged now. I am also happy to review any existing PR, please feel free to assign me.
I am also almost done and will make PRs soon for the following tasks. Kindly let me know if these will be good additions to the repo and haven't been added yet: 
1. NER ( CoNLL, GUM, wikigold, BTC) n = 4
2. [QA-SRL](https://qasrl.org) ( Question Answering Semantic Role Labeling QA-SRL 2.0 strict/loose, QADiscourse, QANom) n = 4 
3. [ConceptNet](https://github.com/commonsense/conceptnet5) (CommonSense Knowledge Graphs In all 10 core languages ) n = 10

**Comment by danyaljj** [comment]
One more suggestion: I am not quite happy with the idea of specifying a "position" (an index), mainly because it is hard to read/parse for an average human (besides potential complications that might come up due to tokenization issues). 

My suggestion is that we reformulate the input such that the token is easy to spot. For example, you can highlight the token with some easy-to-read special tokens (say, in between `-->` and `<--` or `{{ ...}}`). You can also specify the target word in the input (instead of its position).

**Comment by mishra-sid** [comment]
Hey @danyaljj , I completely agree with your suggestion. I made the changes in both this PR and in #380  with a special token  " {{ ... }} " , added the target word and removed position from input. Let me know if it looks good or if you have any other suggestions regarding this. 
Thanks !

**Comment by danyaljj** [comment]
Thanks! Could you also shuffle the instances, too? Currently, they seem to be sorted according to their output label.

**Comment by mishra-sid** [comment]
@danyaljj Shuffled the instances for both this PR as well as in #380 . Let me know if this is good to be merged or if there are any other changes necessary.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
