### PR TITLE
Task 363: SST2

### PR DESCRIPTION
**Pull request by gkaramanolakis**
task363_SST2_polarity_classification: Given a sentence from a movie review, classify the sentence to positive or negative sentiment

### CODE REVIEW

**Comment by danyaljj** [comment]
Relevant PR #122

 Looks good to me, thanks! 
Leaving it for @swarooprm  to take a look before we merge.

**Review by swarooprm — COMMENTED** [review]
LGTM! 
Please confirm that labels in instances are near uniform and not skewed towards one label.

**Comment by gkaramanolakis** [comment]
> Please confirm that labels in instances are near uniform and not skewed towards one label.

The label distribution is: 
POS:    3458 instances
NEG:   3042 instances

**Comment by swarooprm** [comment]
> > Please confirm that labels in instances are near uniform and not skewed towards one label.
> 
> The label distribution is:
> POS: 3458 instances
> NEG: 3042 instances

Looks good! Thanks.

**Review by swarooprm — APPROVED** [review]
LGTM!

**Pull request merged**
