### PR TITLE
Tasks 500-525: Assigning categories, domains, and addressing feedbacks 

### PR DESCRIPTION
**Pull request by yeganehkordi**

### CODE REVIEW

**Comment by danyaljj** [comment]
Notice that you have several conflicts already. Better merged them sooner than later.

**Comment by yeganehkordi** [comment]
Thanks! I resolved them.

**Review by swarooprm — COMMENTED** [review]
categories and domains are fine, as disscused in the meeting.
@danyaljj, leaving for you to review addressing human feedbacks before merging.

**Comment by danyaljj** [comment]
Looks good, thanks!

**Pull request merged**
