### PR TITLE
Task 613 Politifact

### PR DESCRIPTION
**Pull request by cosmicishan**
task613_politifact_text_generation -> Given a statement from politifact.com, your task is to generate the subject of the statement

Also, please suggest to me another task I can create from this dataset.
Thanks in advance!!

Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Based on the following example, 
```
            "input": "Under President Obamas health-care reforms, the premium for an average plan for a family didnt go down by $2,500 per year, its gone up about $2,500 per year.",
            "output": [
                "corporations,economy,health-care,public-health,workers"
            ]
```
it seems that there that "subjects" is not quite the grammatical "subject" of the sentence.  But rather, it is a broader definition of the subject of discussion (like "economy" and "healthcare"), which does not need to be a strict substring of the sentence. We may wanna clarify this. 


Also, why did you include all the possible outputs as a single comma-separated string? 
You could have created a list of strings: 
```
            "output": [
                "corporations", "economy", "health-care", "public-health", "workers"
            ]
```

**Comment by swarooprm** [comment]
> Based on the following example,
> 
> ```
>             "input": "Under President Obamas health-care reforms, the premium for an average plan for a family didnt go down by $2,500 per year, its gone up about $2,500 per year.",
>             "output": [
>                 "corporations,economy,health-care,public-health,workers"
>             ]
> ```
> 
> it seems that there that "subjects" is not quite the grammatical "subject" of the sentence. But rather, it is a broader definition of the subject of discussion (like "economy" and "healthcare"), which does not need to be a strict substring of the sentence. We may wanna clarify this.
> 
> Also, why did you include all the possible outputs as a single comma-separated string? You could have created a list of strings:
> 
> ```
>             "output": [
>                 "corporations", "economy", "health-care", "public-health", "workers"
>             ]
> ```

@cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings. Also +1 on representing output as a list of strings. Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.

Can you address these so that we can go ahead with merging?

**Comment by cosmicishan** [comment]
> > Based on the following example,
> > ```
> >             "input": "Under President Obamas health-care reforms, the premium for an average plan for a family didnt go down by $2,500 per year, its gone up about $2,500 per year.",
> >             "output": [
> >                 "corporations,economy,health-care,public-health,workers"
> >             ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it seems that there that "subjects" is not quite the grammatical "subject" of the sentence. But rather, it is a broader definition of the subject of discussion (like "economy" and "healthcare"), which does not need to be a strict substring of the sentence. We may wanna clarify this.
> > Also, why did you include all the possible outputs as a single comma-separated string? You could have created a list of strings:
> > ```
> >             "output": [
> >                 "corporations", "economy", "health-care", "public-health", "workers"
> >             ]
> > ```
> 
> @cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings. Also +1 on representing output as a list of strings. Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.
> 
> Can you address these so that we can go ahead with merging?

Hey, I have fixed the issue. Sorry, I took so long because I missed this PR and thought I didn't get reviewed but now I checked the review and I fixed it.

**Comment by danyaljj** [comment]
Thanks, @cosmicishan! 

Seems like this suggestion fell through the cracks :

> @cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings. 


I want to bring up the following suggestion; now that we're on this task, it might be easy to define and add this task: 

> Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.

**Comment by cosmicishan** [comment]
> Thanks, @cosmicishan!
> 
> Seems like this suggestion fell through the cracks :
> 
> > @cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings.
> 
> I want to bring up the following suggestion; now that we're on this task, it might be easy to define and add this task:
> 
> > Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.

Sure I will add that task.

**Comment by swarooprm** [comment]
> > Thanks, @cosmicishan!
> > Seems like this suggestion fell through the cracks :
> > > @cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings.
> > 
> > 
> > I want to bring up the following suggestion; now that we're on this task, it might be easy to define and add this task:
> > > Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.
> 
> Sure I will add that task.

Also, please clarify that subjects (or keywords/topic) are not necessarily sub-strings. @cosmicishan

**Comment by cosmicishan** [comment]
> > > Thanks, @cosmicishan!
> > > Seems like this suggestion fell through the cracks :
> > > > @cosmicishan, yes clarify that subjects (or keywords/topic) are not necessarily sub-strings.
> > > 
> > > 
> > > I want to bring up the following suggestion; now that we're on this task, it might be easy to define and add this task:
> > > > Re: more task suggestion- I think you are constrained by data here and can create only one more task such as given a sentence and a subject, generate 'yes' if both match, else generate 'no'.
> > 
> > 
> > Sure I will add that task.
> 
> Also, please clarify that subjects (or keywords/topic) are not necessarily sub-strings. @cosmicishan

I fixed that and I also added one more task. Please review again.

**Comment by swarooprm** [comment]
Looks good to me, but there are several redundant additions in readme @cosmicishan

**Review by swarooprm — APPROVED** [review]
Fixed readme ordering issue.

**Comment by cosmicishan** [comment]
> Fixed readme ordering issue.

Thank you. :)

**Pull request merged**
