### PR TITLE
Task 591-594 SciQ dataset

### PR DESCRIPTION
**Pull request by kuntalkumarpal**

### CODE REVIEW

**Comment by swarooprm** [comment]
-task 591- remove "the task is", directly say, generate. if you have multiple correct answers, add them as a list in instance outputs.
-task 592- this file appears same as 591- replace. It's likely that you will have multiple incorrect answer per input, add them as a list in instance outputs (not in positive examples).
- task 593- looks good
- task 594- I am not sure what this means "Make sure that the passage also supports some facts regarding the question generated.", rephrase

**Comment by swarooprm** [comment]
> -task 591- remove "the task is", directly say, generate. if you have multiple correct answers, add them as a list in instance outputs. -task 592- this file appears same as 591- replace. It's likely that you will have multiple incorrect answer per input, add them as a list in instance outputs (not in positive examples).
> 
> * task 593- looks good
> * task 594- I am not sure what this means "Make sure that the passage also supports some facts regarding the question generated.", rephrase

@kuntalkumarpal, can you address the comments ?

**Comment by kuntalkumarpal** [comment]
> > -task 591- remove "the task is", directly say, generate. if you have multiple correct answers, add them as a list in instance outputs. -task 592- this file appears same as 591- replace. It's likely that you will have multiple incorrect answer per input, add them as a list in instance outputs (not in positive examples).
> > 
> > * task 593- looks good
> > * task 594- I am not sure what this means "Make sure that the passage also supports some facts regarding the question generated.", rephrase
> 
> @kuntalkumarpal, can you address the comments ?

@swarooprm Updated. Please check.

**Review by swarooprm — APPROVED** [review]
LGTM.

**Comment by danyaljj** [comment]
I am not sure if the following is a clear definition of incorrect answer generation. 
```
"Definition": "Given a science question, generate an incorrect answer to the given question",
```
We may want to consult with the paper/authors to see what criteria they used for this task.

**Comment by danyaljj** [comment]
@kuntalkumarpal checking if you have seen my question above?

**Comment by kuntalkumarpal** [comment]
> @kuntalkumarpal checking if you have seen my question above?

@danyaljj 

The authors first used Mechanical Turks to create questions and correct answers. Then, they generated 6 candidate incorrect answers using feature-based random forest model training a binary classifier. Then the question, correct answer and 6 incorrect candidates were provided to another set of Mechanical Turkers. The Turkers were allowed to select not more than two out of the 6 and were instructed to write at least one on their own. 

The instruction for the answer candidates:
- should be plausible as alternatives to the correct answer
- should roughly have the same number of words as the correct answer
- should be false; i.e. should not accidentally be another correct answer to the question

The instructions and examples were clear that all the answers should be other items from the same categories but incorrect.

Also, 36.1% of the distractors in the final dataset were found to be generated by the model.

**Comment by danyaljj** [comment]
Okay, good. In your summary, there are relevant segments that we can incorporate in the definition of "incorrect answer generations": 

> should be plausible 
> all the answers should be other items from the same categories but incorrect.

**Comment by kuntalkumarpal** [comment]
Updated the definition for task 592

**Comment by swarooprm** [comment]
@kuntalkumarpal, can you update your files with input language and output language field (e.g. look at task001 in the repo) so that tests in the master pass?
Please do it on priority.

**Pull request merged**
