### PR TITLE
Tasks 676-684: OPP-115, HopeEDI, Ollie Datasets

### PR DESCRIPTION
**Pull request by kaushikpunyamurthula**

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/122#

**Comment by danyaljj** [comment]
@mattf1n could you review this PR?

**Review by mattf1n — CHANGES_REQUESTED** [review]
task679_hope_edi_english_text_classification.json: Misclassified examples, at least in my opinion :)

task676_ollie_relationship_answer_generation.json: Some incorrect examples, 

task678_ollie_actual_relationship_answer_generation.json: Many answers are not verb forms.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by kaushikpunyamurthula** [comment]
Hi @mattf1n @danyaljj,

Will make the changes and push again. Sorry for the delayed reply.

**Comment by swarooprm** [comment]
> Hi @mattf1n @danyaljj,
> 
> Will make the changes and push again. Sorry for the delayed reply.

@sskp-kaushik, can you address reviewer comments?

**Comment by danyaljj** [comment]
Improved the instructions. 
Merging upon green.

**Pull request merged**
