### PR TITLE
Tasks 629-635: dbpedia_14 and allegro_reviews datasets

### PR DESCRIPTION
**Pull request by divya0627**

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/87

**Comment by danyaljj** [comment]
If the question is always the same ("Question: Is the text about a person?"), why do you need to repeat it for each instance?

**Comment by divya0627** [comment]
> If the question is always the same ("Question: Is the text about a person?"), why do you need to repeat it for each instance?

@danyaljj You are right, I can change it to a classification task instead of the answer generation task.

**Comment by divya0627** [comment]
> > If the question is always the same ("Question: Is the text about a person?"), why do you need to repeat it for each instance?
> 
> @danyaljj You are right, I can change it to a classification task instead of the answer generation task.

@danyaljj  Made changes to the task as per the review.

**Comment by danyaljj** [comment]
Thanks! Another suggestion: for the tasks that are not English, add a language tag, as per #113.

**Comment by divya0627** [comment]
> Thanks! Another suggestion: for the tasks that are not English, add a language tag, as per #113.

@danyaljj Made changes to tasks 634,635 as per the review

**Pull request merged**
