### PR TITLE
Tasks 625-628

### PR DESCRIPTION
**Pull request by ananth-duggirala**

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/21

**Comment by swarooprm** [comment]
These tasks look good to me, some of the annotations in instances might not be distinguishable clearly based on whether the usage of the word has been done with the same meaning or not, but I guess this is a minority. Moreover, they come from this dataset https://aclanthology.org/2020.emnlp-main.584.pdf, so we can't control some of the potential noise this contains.

Do you see any issue in these tasks @danyaljj ?

**Comment by danyaljj** [comment]
Looks good to me! Feel free to merge.

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
