### PR TITLE
Tasks 438-441: English-Gujarati Language

### PR DESCRIPTION
**Pull request by Mihir3009**
2 Translation, 1 Classification - almost balanced labels, and 1 language identification (almost balanced data) tasks.

Please review.

### CODE REVIEW

**Comment by eshaanpathak** [comment]
You should explain why the positive examples are correct instead of just stating they are.

And in the negative examples, you should also state what is the correct answer and explain that.

**Comment by swarooprm** [comment]
@Mihir3009, can you address reviewer's comments?

**Comment by Mihir3009** [comment]
I resolved the comments.

**Comment by eshaanpathak** [comment]
There seems to be a few grammatical errors in each file. Please go through the explanations and fix them.

**Comment by Mihir3009** [comment]
Updated.

**Comment by eshaanpathak** [comment]
1. In `tasks/README.md`, put line 386 at the end of the last line. You should also just say "Language Identification". No need to add "(Binary)" to the category for this group of tasks as well as any other group of tasks with this category that you have already committed or will commit.
2. The first positive example for each task should be "The translated sentence also talks about a standing herd of sheep, thus we can say that it is a correct translation from English to Gujarati." You can just copy paste this.
3. The second positive example for each task should be "The translated sentence conveys the same meaning, which is a missing tank lid on the toilet, hence it is a correct translation." You can just copy paste this.
4. The third positive example for each task should be "The translated sentence conveys the same meaning where the man is riding a bike on a wet sidewalk, thus it is a correct translation from English to Gujarati." You can just copy paste this.
5. The first negative example for each task should be "This translation from English to Gujarati is wrong because there is no herd of cows but rather a herd of sheep. The correct translation is 'ઘેટાંની ટોળાં એક ગોચરમાં ચરાઈ સાથે મળીને ઊભા છે.'." You can just copy paste this with the minor changes for "Gujarati to English" and the translations to English for task 439.
6. The second negative example for each task should be "This translation from English to Gujarati is wrong because the bathroom is remodeled, not the living room. The correct translation is 'ટાંકીના ઢાંકણમાં ગુમ થયેલી શૌચાલયથી બાથરૂમ ફરી બનાવવામાં આવી રહ્યું છે.'." You can just copy paste this with the minor changes for "Gujarati to English" and the translations to English for task 439.
7. The third negative example for each task should be "This translation from English to Gujarati is wrong because the man is driving a motorcycle, not a car. The correct translation is 'એક માણસ ભીની ફૂટપાથ નીચે મોટરસાઇકલ ચલાવી રહ્યો છે.'." You can just copy paste this with the minor changes for "Gujarati to English" and the translations to English for task 439.

**Comment by Mihir3009** [comment]
I did the same explanation because it is the same just the different translation task. Can you please suggest your thoughts that what kind of changes we can do? I have seen other translation tasks, it's pretty much similar to them.

**Comment by eshaanpathak** [comment]
For task 438, you can copy paste what I recommend.

For task 439, you can still copy paste the explanation with the following changes as I said above:
1. Instead of "English to Gujarati", change it to "Gujarati to English".
2. Instead of the correct translation written in Gujarati, replace it with the correct translation written in English.

For task 440, you can copy paste what I recommend and replace "The translated sentence" with "These sentences" and fix other minor grammar stuff to fit this plural tense.

For task 441, you should capitalize "English" in the explanation of the second negative example.

Don't forget to also change `tasks/README.md` as I said above in my previous comment.

Let me know if you have any other questions.

**Comment by Mihir3009** [comment]
I addressed all comments @eshaanpathak. Please let me know what you think. Thanks for the comments.

**Review by swarooprm — APPROVED** [review]
LGTM 
Fixed some minor errors in readme.

**Pull request merged**
