### PR TITLE
Task 105 sentence generation

### PR DESCRIPTION
**Pull request by Mirzyaaliii**

### CODE REVIEW

**Comment by danyaljj** [comment]
For `"Source": "Story Cloze and ROCStories",` include a link. 

Otherwise, it's ✅ for me! @swarooprm merge when you're happy!

**Comment by swarooprm** [comment]
Looks good to me as well! I will merge once you address Daniel's comments.

On a separate note, next time when you pick a dataset please register it in the spreadsheet.
I see a conflict this time because ROC Stories is already registered by someone else. I am approving this time, but next time please register so that no one else works on the same dataset.

**Comment by swarooprm** [comment]
Please pull and merge with the main. I will then be able to merge your task.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Pull request merged**
