### PR TITLE
Task 119, 120 and 121: ZEST dataset

### PR DESCRIPTION
**Pull request by yeganehkordi**
Paraphrasing, semantic flip and combination tasks based on zest dataset: https://arxiv.org/abs/2011.08115

Partially addressing #78

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! 

One clarification: in the original repo I see more tasks. For example, [`output-structure`](https://github.com/allenai/zest/tree/master/mturk-templates/tasks/output-structure), [`extraction`](https://github.com/allenai/zest/tree/master/mturk-templates/labels/extraction) or [`classification`](https://github.com/allenai/zest/tree/master/mturk-templates/labels/classification). Was there any particular reason that you did not consider these tasks?

**Comment by danyaljj** [comment]
* `tasks/task119_zest_paraphrasing.json`: 

-  This sentence does not sound right: "Your paraphrased questions should have the same answer as the original would and should not change the meaning of the question. ". How about this?: "Your paraphrased questions should have the same answer as the original question" 
- `same type of answer as the original, yes or no.`: odd ending of the sentence. Do we need ", yes or no"? 


* `tasks/task120_zest_semantic_flips.json` and `tasks/task121_zest_combination.json` sound reasonable to me. 


For all these tasks, it might be helpful to indicate that all the words that are fully capitalized are keywords. For example, in `What wars did PRESIDENT initiate as president`, the word `PRESIDENT` is a keyword (which will be replaced with a name of an actual president). Hence, in the modification (paraphrasing, etc) this keyword should also be used as fully capitalized. 
 
 
 PS. heard from Orion Weller in Feb 2021: 
>  ... That link contains the template and some of the prompts we used to gather the output from the workers.  I don't think we still have the outputs of the MTurk tasks though (or at least, as far as I can find).

**Comment by yeganehkordi** [comment]
> Was there any particular reason that you did not consider these tasks?


Yes, I extract current tasks from the dataset but I need corresponding input/outputs for the output-structure and extraction tasks, the attributes and highlights which used in these tasks aren't included in the dataset. I'm waiting for the author's response. 
Also, the classification task seems to be similar to extraction.

> tasks/task119_zest_paraphrasing.json:


Yes, that's right. I used the exact sentences in the MTurk template. I'll fix it now.

> it might be helpful to indicate that all the words that are fully capitalized are keywords.


Sure, will do.

**Comment by yeganehkordi** [comment]
> PS. heard from Orion Weller in Feb 2021:
> ... That link contains the template and some of the prompts we used to gather the output from the workers. I don't think we still have the outputs of the MTurk tasks though (or at least, as far as I can find).

Heard the same thing from Matthew Peters today. I guess we still can extract another question-answering task from this dataset (it's not listed in MTurk tasks) or we could leave it here.

**Comment by danyaljj** [comment]
Alright, got it. That answers my comments above. 

One last question about `task121_zest_combination`: are **all** the generated questions here binary (yes/no)? If that's the case, maybe we should mention it explicitly in the task description.

**Comment by yeganehkordi** [comment]
No, there are some extractive questions as well.

**Comment by danyaljj** [comment]
Got it. 

@swarooprm I am signing off on this. Feel free to merge when you're happy.

**Review by swarooprm — COMMENTED** [review]
Looks good! One minor comment: Don't create three new categories. Categories of all the three tasks should be "Text Modification". I will merge once you do these changes.

Also, share your email id with me so that I can add you to a spreadsheet that contains many resources that can help you find more datasets to create tasks.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.

**Comment by swarooprm** [comment]
Congratulation on your first task @yeganehkordi !

**Comment by yeganehkordi** [comment]
Thanks, Here is my email id: yegane.kordi@gmail.com

**Pull request merged**
