### PR TITLE
Tasks 664-667 and 685-737: Measuring Massive Multitask Language Understanding 

### LINKED ISSUE #257: Measuring Massive Multitask Language Understanding
https://arxiv.org/abs/2009.03300

This covers 57 tasks including elementary mathematics, US history, computer science, law, and more.

### PR DESCRIPTION
**Pull request by Sujan242**
Based on https://arxiv.org/pdf/2009.03300.pdf. 
Mentioned in #257

### CODE REVIEW

**Comment by eshaanpathak** [comment]
I won't be able to fully review this, but if there are 57 tasks in the dataset, you should split them up by subject (mathematics, history, computer science, etc.) or some other way to split them up as opposed to just combining them all into one task. Maybe more people can help take this on if there are a lot of tasks, depending on how they are split up. @swarooprm @danyaljj 

Please also make sure you pass the checks.

**Comment by Sujan242** [comment]
Thanks for reviewing! The 57 tasks have been grouped into 4 categories based on the hierarchy in the paper. 
For example, Physics, Biology, Computer science, Math, and Engineering-related tasks are grouped into a single category called "STEM".

**Comment by swarooprm** [comment]
> Thanks for reviewing! The 57 tasks have been grouped into 4 categories based on the hierarchy in the paper.
> For example, Physics, Biology, Computer science, Math, and Engineering-related tasks are grouped into a single category called "STEM".

Hi Sujan, thanks for creating tasks. I think we should have 57 different tasks and not 4 tasks, primarily because each task belong to a different domain and having 57 tasks will help us evaluate model performance on each domain separately, similar to how it was done in the main paper.

Let me know if you have any question.

**Comment by Sujan242** [comment]
I have created 57 tasks different tasks, each belonging to a different domain. 
> 
> Hi Sujan, thanks for creating tasks. I think we should have 57 different tasks and not 4 tasks, primarily because each task belong to a different domain and having 57 tasks will help us evaluate model performance on each domain separately, similar to how it was done in the main paper.
> 
> Let me know if you have any question.

**Comment by swarooprm** [comment]
Looks good.
1. I would explicitly mention that "you need to answer the question." Remove the tag: "Things to avoid" in the following sentence. We don't need it.
"Things to avoid: 1. Do not generate anything else apart from one of the following characters: 'A', 'B, 'C', 'D'. 2. Give only one answer for each question."

2. Also, ensure that labels are balanced across instances.

Each of the tasks belongs to a different domain in this PR @danyaljj.  This will be helpful to add diversity to our task hierarchy.

**Comment by danyaljj** [comment]
Yeah, other than @swarooprm 's comment, looks like a good addition.

**Comment by Sujan242** [comment]
@swarooprm I have made the changes

**Review by swarooprm — APPROVED** [review]
LGTM!
I guess you have also balanced labels based on my last comment. If there is skewness, please fix in a new PR.

**Comment by Sujan242** [comment]
> LGTM! I guess you have also balanced labels based on my last comment. If there is skewness, please fix in a new PR.

Yes, I had balanced the labels in all the tasks.

**Pull request merged**
