### PR TITLE
Task 616 CoLA

### PR DESCRIPTION
**Pull request by cosmicishan**
task616_cola_classification -> Given a sentence you have to return if it is acceptable or unacceptable. 

Also, please suggest to me another task I can create from this dataset.
Thanks in advance!!

Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
You need to define "acceptability" in what sense (which seems to be in terms of whether the given sentence makes sense or not).

**Comment by cosmicishan** [comment]
> You need to define "acceptability" in what sense (which seems to be in terms of whether the given sentence makes sense or not).

I fixed that. Can you review it again?

**Comment by danyaljj** [comment]
Looks good to me. Leaving it here for @swarooprm to review it once more before merging.

**Review by swarooprm — APPROVED** [review]
LGTM.
I assume classes are balanced.
One new task can be given a grammatical incorrect sentence, correct it, but I don't know if the COLA dataset contain such instances.

**Pull request merged**
