### PR TITLE
Task 1115-1129 ALT

### PR DESCRIPTION
**Pull request by SavanDoshi**
Please review. These are translation tasks for Asian languages. These tasks are extensions of #233.

### CODE REVIEW

**Comment by danyaljj** [comment]
@tanay2001 wondering if you can review this PR?

**Comment by tanay2001** [comment]
Hi @SavanDoshi 

Is there any overlap with #269 ? , I feel the translation tasks of en-th seems to be already covered , please correct me if I am wrong 
Also for the definitions, why do you need to mention the capitalizing condition not sure if all the languages listed actually can allow for such a rule, ex: in Thai there is no such thing called capital or small letters.
I cannot verify the correctness of the instances as I don't speak those languages but the rest looks good

**Comment by SavanDoshi** [comment]
> good

@tanay2001 Yes, it has overlap with the other PR. I will make some other tasks in my PR.

**Comment by SavanDoshi** [comment]
@tanay2001  I have changed all the tasks as it has conflicts with other tasks.

Please review.

**Comment by tanay2001** [comment]
> @tanay2001 I have changed all the tasks as it has conflicts with other tasks.
> 
> Please review.

Looks good to me

**Comment by SavanDoshi** [comment]
@danyaljj Can you have a look at this? It is similar to tasks as #233.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
