### PR TITLE
Task 1187 Politifact 

### PR DESCRIPTION
**Pull request by cosmicishan**
task1187_politifact_classification -> Given a statement and subject of discussion, your task is to classify whether it's a correct subject or not. 

Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Here as well, Amazon review files seem to be redundant addition.

**Comment by cosmicishan** [comment]
> Here as well, Amazon review files seem to be redundant addition.

I removed it. I don't know how it got added.

**Comment by Palipoor** [comment]
Hi,
It seems like your task number has changed. please reflect it in readme and file names.
Also, these comments:
- Here in the task definition: "of the discussion is the correct for the given statement" please remove the "the" before "correct". Also, maybe change " your task is to generate" to "your task is to determine".
- Please reword the explanation of the third positive example. You don't need to mention "Military". It'd suffice if you explain that election is not a correct subject.
- The explanation for the second negative example is a bit weird. 
- In the explanation for the third negative example, please change "It's only supposed to return True or False." to "You're only supposed to answer with true or false". 
- Also, please point out in the definition that the subject can be multiple words.

**Comment by cosmicishan** [comment]
> Hi, It seems like your task number has changed. please reflect it in readme and file names. Also, these comments:
> 
> * Here in the task definition: "of the discussion is the correct for the given statement" please remove the "the" before "correct". Also, maybe change " your task is to generate" to "your task is to determine".
> * Please reword the explanation of the third positive example. You don't need to mention "Military". It'd suffice if you explain that election is not a correct subject.
> * The explanation for the second negative example is a bit weird.
> * In the explanation for the third negative example, please change "It's only supposed to return True or False." to "You're only supposed to answer with true or false".
> * Also, please point out in the definition that the subject can be multiple words.

Thank you for the thorough review and all the suggestions you provide to improve the definition and explanations. I have fixed that. Please review it again.

**Review by Palipoor — APPROVED** [review]

**Comment by danyaljj** [comment]
The PR seems to be removing two tasks? 😮

**Comment by cosmicishan** [comment]
> The PR seems to be removing two tasks? open_mouth

You told me in the above comment that some redundant files got added so I deleted them. So let me know what I should do if I should keep them or not?

**Comment by danyaljj** [comment]
Looks like the two of your PRs (this and #299) shared their git history, which has caused this conflict here (which is not a good practice when opening multiple pull requests). Your easiest solution is to copy the additions here to a fresh checkout of the main branch and open a new PR.

**Pull request closed without merging**
