### PR TITLE
Tasks 453-455 : Swag Dataset

### PR DESCRIPTION
**Pull request by kuntalkumarpal**

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi, the examples for all your three tasks are the same.

**Comment by kuntalkumarpal** [comment]
> Hi, the examples for all your three tasks are the same.

Thanks. I have made the examples much more diverse. Please have a look now.

**Comment by swarooprm** [comment]
@Palipoor, can you check and let @kuntalkumarpal know if you have any other feedback

**Comment by swarooprm** [comment]
Typo in 3rd task:
Her walking by the office is now way ---->Her walking by the office is no way 

1st task:
events in the context-->event in the context

Check once typos and grammatical mistakes in the full dataset.
Let me know once you are done @kuntalkumarpal

**Comment by kuntalkumarpal** [comment]
> Typo in 3rd task: Her walking by the office is now way ---->Her walking by the office is no way
> 
> 1st task: events in the context-->event in the context
> 
> Check once typos and grammatical mistakes in the full dataset. Let me know once you are done @kuntalkumarpal

@swarooprm  Fixed. Have a look

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
