### PR TITLE
Task 956: leetcode 420

### PR DESCRIPTION
**Pull request by DZuoShi**
This is based on leetcode question 420. 
https://leetcode.com/problems/strong-password-checker/

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! This task is extremely difficult for average humans. However, a modified version of the problem where one can decide whether a given password is "strong" or not, might be a better task since humans can relatively easily solve it.

**Comment by swarooprm** [comment]
> Thanks! This task is extremely difficult for average humans. However, a modified version of the problem where one can decide whether a given password is "strong" or not, might be a better task since humans can relatively easily solve it.

@DZuoShi, can you respond to reviewer comments and also the test failure?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by DZuoShi** [comment]
> Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

Can do! I'll get on it.

**Comment by danyaljj** [comment]
@DZuoShi please let us know if you can update the PR so that we can get it in as soon as possible.

**Comment by aarunku5** [comment]
> @DZuoShi please let us know if you can update the PR so that we can get it in as soon as possible.

@DZuoShi can you please update us on your progress?

**Comment by danyaljj** [comment]
Related to #127 

For future: we can create a verification version of this task as well.

**Pull request merged**
