### PR TITLE
Task 586-590 Amazon food review

### PR DESCRIPTION
**Pull request by cosmicishan**
task586_amazonfood_polarity_classification -> Given a review of an amazon food product, you have to classify if the review is positive or negative.
task587_amazonfood_polarity_correction_classification -> Given a review of amazon food products and it's polarity, you have to classify whether the polarity is correct or not.
task588_amazonfood_rating_classification -> Given a review of amazon food products, you have to classify the rating out of 5. 
task589_amazonfood_summary_text_generation -> Given a review of amazon's food product, you have to generate the summary of the review. 
task590_amazonfood_summary_correction_classification -> Given a review of amazon's food product and its summary, you have to classify whether the summary is correct or not. 

Please review.

### CODE REVIEW

**Comment by swarooprm** [comment]
@ethankim00, wondering if you can help review this PR?

**Comment by ethankim00** [comment]
Yes, I can take a look and make comments tonight

**Comment by ethankim00** [comment]
Thank you for the submission. This set of tasks creates several natural language instruction challenges from the same dataset.

General:
- task structure and examples and are clear and correct

Corrections:
- Avoid capitalizing word "Summary" throughout instructions and explanations
- Double check grammatical correctness and completeness of explanations, for example: 
Task 590
```
    {
            "input": "Product arrived labeled as Jumbo Salted Peanuts...the peanuts were actually small sized unsalted. Not sure if this was an error or if the vendor intended to represent the product as \"Jumbo\". \n Summary: Not as Advertised",
            "output": "True",
            "explanation": "The customer didn't get the product he show in the advertisement. So, it's a correct Summary. So, the correct answer is True."
        }
```

Suggestions:
- In the summarization tasks specify in the instructions that the review and summary will be separated by a newline 
- In task 589 possibly add the directive to generate a short summary to the instructions since many of the summaries are very short

**Comment by cosmicishan** [comment]
> Thank you for the submission. This set of tasks creates several natural language instruction challenges from the same dataset.
> 
> General:
> 
> * task structure and examples and are clear and correct
> 
> Corrections:
> 
> * Avoid capitalizing word "Summary" throughout instructions and explanations
> * Double check grammatical correctness and completeness of explanations, for example:
>   Task 590
> 
> ```
>     {
>             "input": "Product arrived labeled as Jumbo Salted Peanuts...the peanuts were actually small sized unsalted. Not sure if this was an error or if the vendor intended to represent the product as \"Jumbo\". \n Summary: Not as Advertised",
>             "output": "True",
>             "explanation": "The customer didn't get the product he show in the advertisement. So, it's a correct Summary. So, the correct answer is True."
>         }
> ```
> 
> Suggestions:
> 
> * In the summarization tasks specify in the instructions that the review and summary will be separated by a newline
> * In task 589 possibly add the directive to generate a short summary to the instructions since many of the summaries are very short

I solved those comments. Can you review it again?

**Review by ethankim00 — COMMENTED** [review]
Can you update the second positive example for task 588
The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he show in the description. So he gave 1 star.

to 

The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he was shown in the description. So he gave 1 star.

Otherwise looks good

**Comment by cosmicishan** [comment]
> Can you update the second positive example for task 588
> The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he show in the description. So he gave 1 star.
> 
> to
> 
> The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he was shown in the description. So he gave 1 star.
> 
> Otherwise looks good

Thank you for the good review and nice suggestion. I fixed it. Hope I didn't miss anything out. Can you review it again?

**Comment by swarooprm** [comment]
> > Can you update the second positive example for task 588
> > The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he show in the description. So he gave 1 star.
> > to
> > The customer seemed disappointed with the product he received. He really seems very unsatisfied that he didn't get what he was shown in the description. So he gave 1 star.
> > Otherwise looks good
> 
> Thank you for the good review and nice suggestion. I fixed it. Hope I didn't miss anything out. Can you review it again?

@ethankim00, check if you are happy or have any other feedback?

**Comment by ethankim00** [comment]
Looks good to me

**Comment by swarooprm** [comment]
@cosmicishan, tasks look good, some suggestions.
- task586: only one review will be given and model need to answer that. I would write definition this way "You are given a review from Amazon's food products. Your task is to classify it into two classes: Negative or Positive depending on the content the review contains."
- task 587: similar problems as previous, here's how I will write the definition "You are given an amazon food product review and its polarity (either positive or negative). You need to answer \"True\" if given sentence and its polarity match, otherwise answer \"False"
- task 588: you need to provide details regarding what does rating 1-5 means; here is how I will write "You are given an amazon food product review. Your task is to generate a rating for the product on a scale of 1-5, based on the review. Rating 1, 2, 3, 4, 5 represents extremely poor, poor, ok, good and excellent product respectively" Feel free to change the 1-5 representations.

Change definitions of other tasks accordingly. Check grammar. Also, ensure that first letter of only the first word of the sentence and keywords are capital (I found in task 589, summary is written as "Summary")
@cosmicishan

**Comment by cosmicishan** [comment]
> @cosmicishan, tasks look good, some suggestions.
> 
> * task586: only one review will be given and model need to answer that. I would write definition this way "You are given a review from Amazon's food products. Your task is to classify it into two classes: Negative or Positive depending on the content the review contains."
> * task 587: similar problems as previous, here's how I will write the definition "You are given an amazon food product review and its polarity (either positive or negative). You need to answer "True" if given sentence and its polarity match, otherwise answer "False"
> * task 588: you need to provide details regarding what does rating 1-5 means; here is how I will write "You are given an amazon food product review. Your task is to generate a rating for the product on a scale of 1-5, based on the review. Rating 1, 2, 3, 4, 5 represents extremely poor, poor, ok, good and excellent product respectively" Feel free to change the 1-5 representations.
> 
> Change definitions of other tasks accordingly. Check grammar. Also, ensure that first letter of only the first word of the sentence and keywords are capital (I found in task 589, summary is written as "Summary") @cosmicishan

I fixed all the definitions now. Thank you for all those helpful suggestions.

**Comment by swarooprm** [comment]
One thing is missing, hopefully, the last one.
Task588: reviews-->"an review" and "based on rating"-->"based on review"
Task589: reviews-->"an review"
Task 590: this definition is not changed. Here's the suggestion "You are given an amazon food product review and its summary. Generate \"True\" if given review and its summary match, otherwise generate \"False\".

This should be quick for you to implement. @cosmicishan

**Comment by cosmicishan** [comment]
> One thing is missing, hopefully, the last one. Task588: reviews-->"an review" and "based on rating"-->"based on review" Task589: reviews-->"an review" Task 590: this definition is not changed. Here's the suggestion "You are given an amazon food product review and its summary. Generate "True" if given review and its summary match, otherwise generate "False".
> 
> This should be quick for you to implement. @cosmicishan

I have fixed that. Sorry for missing it out previously and thank you for giving a good suggestion. Hopefully, it's good now. So, please review again.

**Pull request merged**
