### PR TITLE
Task 530-533 EuroParl Spanish dataset

### PR DESCRIPTION
**Pull request by cosmicishan**
task530_europarl_en_es_translation -> Given a English sentence, convert it into Spanish.  
task531_europarl_es_en_translation -> Given an Spanish sentence, convert it into English. 
task532_europarl_en-es_classification -> Given an English sentence and its corresponding Spanish sentence, classify whether it is correct or not. 
task533_europarl_es-en_language_identification -> Given a sentence, identify  whether it is in English or Spanish.

### CODE REVIEW

**Comment by danyaljj** [comment]
@BhavyaSri1001 wondering if you can help review this PR?

**Review by swarooprm — COMMENTED** [review]
Looks good. Some comments:
- I assume labels are balanced across classification tasks.
- Definition, examples etc. look very similar to https://github.com/allenai/natural-instructions-expansion/pull/231/files, make sure that the definition language has some differences and examples (and explanations) are diverse enough. 
You should be able to fix this by paraphrasing definition, explanation and modifying example.

**Comment by cosmicishan** [comment]
> Looks good. Some comments:
> 
> * I assume labels are balanced across classification tasks.
> * Definition, examples etc. look very similar to https://github.com/allenai/natural-instructions-expansion/pull/231/files, make sure that the definition language has some differences and examples (and explanations) are diverse enough.
>   You should be able to fix this by paraphrasing definition, explanation and modifying example.

I solved that. Please review again.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
