### PR TITLE
Task 934 Turk Simplification

### PR DESCRIPTION
**Pull request by cosmicishan**
task934_turk__simplification.json -> Given a sentence your task is to generate possible numbers of simplified sentences. 

Please Review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Why do we have amazon review tasks as part of this PR?

**Comment by cosmicishan** [comment]
> Why do we have amazon review tasks as part of this PR?

Where's that task?

**Review by swarooprm — COMMENTED** [review]
@cosmicishan, there are 2 extra files on amazon review. Look at the files changed tab, its showing 4 files.

Regarding the task, looks good. Some suggestions:
- "some possible numbers simplified sentence" is not clear, what do you mean by "numbers simplified". So, definition need to be improved.
- mention in the definition to generate only one output. In positive, negative examples also have one output, in instance have multiple output in the form of a list.
Look at task001 in the repo where the same has been implemented.

**Comment by cosmicishan** [comment]
> @cosmicishan, there are 2 extra files on amazon review. Look at the files changed tab, its showing 4 files.
> 
> Regarding the task, looks good. Some suggestions:
> 
> * "some possible numbers simplified sentence" is not clear, what do you mean by "numbers simplified". So, definition need to be improved.
> * mention in the definition to generate only one output. In positive, negative examples also have one output, in instance have multiple output in the form of a list.
>   Look at task001 in the repo where the same has been implemented.

I have fixed that. Can you review it again?

**Comment by danyaljj** [comment]
> > Why do we have amazon review tasks as part of this PR?
> 
> Where's that task?

Screen Shot 2021-10-04 at 11 10 44 AM

**Comment by cosmicishan** [comment]
> > > Why do we have amazon review tasks as part of this PR?
> > 
> > 
> > Where's that task?
> 
> Screen Shot 2021-10-04 at 11 10 44 AM

I don't know how it got added but I deleted it now.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Pull request closed without merging**
