### PR TITLE
fix xcopa_cause_effect_th

### PR DESCRIPTION
**Pull request by amirrezamirzaei**
addressing #522

### CODE REVIEW

**Comment by danyaljj** [comment]
@amirrezamirzaei could you briefly explain the fix?

**Comment by amirrezamirzaei** [comment]
of course, the dataset uses the same sentences for each language so I just used another language to find the labels.

**Comment by amirrezamirzaei** [comment]
something else I noticed was that the output for the reasoning tasks is exactly like each other for every language. 
but for the cause and effect task, they vary a little (around 20 to 60) between some languages should I evaluate these instances by hand?

**Comment by danyaljj** [comment]
> something else I noticed was that the output for the reasoning tasks is exactly like each other for every language. but for the cause and effect task, they vary a little (around 20 to 60) between some languages should I evaluate these instances by hand?

Well, somehow we need to verify the quality. Unfortunately, none of our contributors speak Thai. I wonder if we can use Google translate to verify a random subset of, say 20 instances?

**Comment by amirrezamirzaei** [comment]
most of the outputs were like each other so I used the first task (969) to check and fix all the differences with the help of google translate.

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
