### PR TITLE
Task 535-564 ALT & Discofuse Datasets

### PR DESCRIPTION
**Pull request by PhaniRohithaKaza**

### CODE REVIEW

**Comment by danyaljj** [comment]
@jayavardhan3112  wondering if you can review this PR?

**Comment by swarooprm** [comment]
@danyaljj, these tasks are already reviewed: https://github.com/swarooprm/CSE576HW/pull/64

**Comment by danyaljj** [comment]
That's good to know. Better to review it once more here, given that there are many tasks here.

**Comment by swarooprm** [comment]
@PhaniRohithaKaza, I have renamed your PR.
Please rename your files to 535-542 since task numbers till 534 are already taken.

**Comment by PhaniRohithaKaza** [comment]
@swarooprm Hello, Sure. I will rename that. But I have 30 tasks. Could you please assign the new task numbers?

**Comment by swarooprm** [comment]
renamed

**Comment by swarooprm** [comment]
> @jayavardhan3112 wondering if you can review this PR?

Could you review this PR @jayavardhan3112?

**Comment by jayavardhan3112** [comment]
Thanks for the update!
Some generic changes to be addressed, These are the following things that needs your attention

- Edit your readme, elaborate your summary in a little bit more detail. It would be better if you make readme a little bit more informative by providing more context. 

- Please re-read it or replace it with this format for the Summary of tasks 400-425 in README file -> Language Translate of Dataset Card for ALT from English questions to Japanese while preserving named entities in the original language. 

- Please update the summary for the other tasks as well in the README file

- For tasks 400-425 -> `Language Translation on Dataset Card for ALT` please change this to 
This format -> Ex: `task174_spl_translation_en_ja` mentioning the from language and to language

- please all the research paper link and the dataset link In the source of all the instructions

- Other than that I think it looks good.

- Don't forget to solve Merge conflicts in the README File

**Comment by PhaniRohithaKaza** [comment]
@jayavardhan3112 Reviewed all the changes. Could you please look into it? :)

**Comment by jayavardhan3112** [comment]
Looks good to me @swarooprm, Please do the final checks.

**Review by swarooprm — APPROVED** [review]
LGTM! Congrats on acceptance of your tasks.

**Pull request merged**
