### PR TITLE
Task 228-229: ARC

### PR DESCRIPTION
**Pull request by Mirzyaaliii**
**ARC** contains only natural, grade-school science questions and is partitioned into a hard Set and an easy Set.

task228_ARC_answer_generation_easy.json - Given a science question (easy-level), provide an answer based on scientific facts and reasoning. (Multiple Choice Question Answering)
task229_ARC_answer_generation_hard.json - Given a science question (hard-level), provide an answer based on scientific facts and reasoning. (Multiple Choice Question Answering)

Please review.

### CODE REVIEW

**Comment by danyaljj** [comment]
Change the definition so that it contains only what is needed for solving the task. 

E.g., the following sentence seems necessary to me. 

> ARC contains standardized 3rd to 9th grade science questions from 12 US states (hard-level). 

And instead, you can change the next sentence to: 


> You are given a **science** question and four ... 

    
Otherwise, it looks good to me.

**Review by swarooprm — COMMENTED** [review]
Can you address reviewer comments?
Get rid of the word ARC in definition as it does not give any new information, instead say "in this task".

**Comment by Mihir3009** [comment]
We updated according to the comment. Thanks.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging. 
You can create more tasks from this dataset
E.g. spilitng the MCQ task in to answer generation and incorrect answer generation task will give rise to 2 new tasks

**Pull request merged**
