### PR TITLE
tasks 254-263: SPL translation tasks

### PR DESCRIPTION
**Pull request by Mehrad0711**
Adding datasets for restaurants domain (with English as the target language).

### CODE REVIEW

**Review by eshaanpathak — CHANGES_REQUESTED** [review]
See my review in #151 for the same changes I recommend. Otherwise these look good to me too. Nice work.

**Review by swarooprm — COMMENTED** [review]
Looks good! 
Similar to the last PR, you are welcome to create more such translation tasks for texts other than questions.

**Comment by Mehrad0711** [comment]
Once the other PR #151 is merged I will rebase this branch on master and push again.

**Comment by swarooprm** [comment]
> Once the other PR #151 is merged I will rebase this branch on master and push again.

I just merged PR #151

**Review by swarooprm — APPROVED** [review]
LGTM

**Pull request merged**
