### PR TITLE
Adding tasks using examples from CoNaLa dataset.

### PR DESCRIPTION
**Pull request by kurbster**
Task 096 I created on my own, whereas every other dataset was created by finding an example in the CoNaLa dataset then generating data through python.

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! 

Several small suggestions: 

 - Simplify the phrasing a bit: 
```
In this task you will be given a list of numbers and you need to normalize them. Normalization in this case means that the output list should sum to the number one and every value in the input list should have the same weight in the output list.
```
How about this?: 
```
In this task, you will be given a list of numbers. The goal is to multiply all the numbers in the list by a constant such that the sum of the resulting numbers is one. 
```
 - `This is a bad example.` --> `This is an incorrect output`
 - Note that not all your numbers have 3 
 - in all the tasks, for the negative examples, add a short sentence/phrase that indicates the fix (i.e., how to turn them into positive examples).

**Review by swarooprm — COMMENTED** [review]
Looking good! I am happy that size of the list is a variable in instances, this is a good way to evaluate "scale invariance" in models.

Some comments:
1. Categories: Instead of "Mathematics", you can add "arithmetic". task097 category needs to be updated.
2. I would add formula of each task in the definition e.g. in case of average, you can say average can be found by summing numbers in the list and then dividing it by the number of elements in that list.

**Review by danyaljj — APPROVED** [review]
Looks good to me! 

@swarooprm  feel free to merge when happy.

**Review by swarooprm — APPROVED** [review]

**Comment by danyaljj** [comment]
There is some feedback from crowd workers regarding your task(s), summarized here: 
https://github.com/allenai/natural-instructions-expansion/pull/276#issuecomment-942714679
Wondering if you can address the feedback?

**Comment by kurbster** [comment]
@danyaljj I can look at the feedback today. Should I address all the comments then create another PR?

**Pull request merged**
