### PR TITLE
Tasks 739-742: lhoestq dataset question and answer generation

### PR DESCRIPTION
**Pull request by hanut1909**

### CODE REVIEW

**Comment by swarooprm** [comment]
@hanut1909, thank you for submitting tasks here. We name tasks sequentially here. Task number 738 was used in your previous PR, So I have renamed your PR to tasks 739-742. Could you please rename your files to 739-742.

**Comment by swarooprm** [comment]
Reviews:https://github.com/swarooprm/CSE576HW/pull/92

**Comment by hanut1909** [comment]
Ohh...
Ok Swaroop.
Will rename the tasks.

**Comment by danyaljj** [comment]
@mattf1n could you review this PR?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Pull request merged**
