### PR TITLE
Tasks 1283-1284: Evaluating quality and Informativeness of System Generated Reference

### PR DESCRIPTION
**Pull request by Sujan242**
Based on https://researchportal.hw.ac.uk/en/datasets/human-ratings-of-natural-language-generation-outputs
The task for naturalness has already been added in #371

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi! Thanks for the contribution.
Can you please explain the differences between 2, 3, 4, 5? Or maybe provide examples with the correct answer being 2,3,4,5?

**Comment by Sujan242** [comment]
Thanks for the review! 
I have included an example for each of the ratings from 1 to 6. 
Let me know your thoughts on this.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by danyaljj** [comment]
Thanks @Sujan242! 

The issue with this task is that the quality judgments (1-6) are quite subjective and likely noisy. I might label something 3 today and after a few days, I might consider it a 2. 

To amend this issue, I suggest you collapse the labels to, say, 2 labels (`high-score` and `low-score`).

**Comment by Sujan242** [comment]
Thanks for the review @danyaljj. 
The dataset contains 3 judgments given by three different human annotators for each instance. The label that I have added is the median of these 3 scores. Will that not eliminate the noise to a certain extent? 
Also, if I consider the minimum and maximum of these 3 scores, I might be including an outlier. 
Please let me know your thoughts on this

**Comment by danyaljj** [comment]
> Thanks for the review @danyaljj. The dataset contains 3 judgments given by three different human annotators for each instance. The label that I have added is the median of these 3 scores. Will that not eliminate the noise to a certain extent? 

It does to some extent. But there is so much subjectivity about ranking items from 1-6 that the median of 3 judgments might not be enough to suppress the noise. I think think that we should binarize this task. 

Side note: if we can't get this PR in this week, it might not make it since we're catching a deadline soon.

**Comment by Sujan242** [comment]
So should I set a threshold of 3 and everything below that is a 0 and everything above is 1 and update the task definitions accordingly?

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
