### PR TITLE
Tasks 1090-1114: TED translation task for 25 language directions.

### PR DESCRIPTION
**Pull request by davidstap**
* I have used the multilingual TED dataset to create 25 tasks, i.e. 25 different translation directions.
* Since all language directions have > 6500 examples, I have sampled 6500 instances.
* I have taken the EuroParl translation task by Mirali Purohit (already merged to master, tasks 312 and 313) as template for `Definition`, `Positive Examples` and `Negative Examples`.
* If someone thinks it is worthwhile to add some more translation directions I can do that, let me know.
* I’m happy to take a look at some pull requests, just @ me.

### CODE REVIEW

**Comment by davidstap** [comment]
(I’ll fix the duplicate issue soon, no time now. This is why the build fails currently.)

EDIT: Issue is fixed now, checks pass successfully.

**Comment by danyaljj** [comment]
Thanks! 

@XudongOliverShen wondering if you can review this PR?

**Comment by XudongOliverShen** [comment]
looks good to me! Although I am not able to judge the quality of the translation. But it should be good since it's from an established dataset.

**Comment by davidstap** [comment]
> looks good to me! Although I am not able to judge the quality of the translation. But it should be good since it's from an established dataset.

Thanks for your review! Indeed the translation quality is good; this dataset is commonly used in multilingual machine translation.

**Comment by danyaljj** [comment]
Thanks! Leaving it here for @swarooprm to review before merging it.

**Review by swarooprm — APPROVED** [review]
LGTM.
I see that some pair of translation tasks are missing (e.g. Japanese to Spanish or English to Spanish etc.). Can you add the missing translation tasks so that every pair of translation is covered among the languages you have used in this PR?
Please create a new PR when you add the missing tasks @davidstap

**Comment by davidstap** [comment]
@swarooprm Thanks for merging. I can do that, but creating tasks for all combinations for these languages (English, Japanese, Spanish, Arabic, Hebrew, Galician, Italian, Polish, Farsi and Portuguese) would mean an additional 10*10 - 10 (ignore copy tasks) - 25 (tasks already in this pull request) = 65 tasks. 

Let me know if you think an additional 65 TED translation tasks is okay or too much?

**Comment by swarooprm** [comment]
Yes, please go ahead and create the 65 tasks (because no body else will touch this TED dataset once they find this dataset is has been already used and these tasks will be missing if we don't create now).
I hope you can automate most of the creation of these tasks and it won't take much time. @davidstap

**Pull request merged**
