### PR TITLE
Tasks 230-238 IIRC Tasks

### PR DESCRIPTION
**Pull request by aarunku5**
4 classification, 4 answer generation

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks, I will review this in the coming days. 

For future: PRs with less than 5 tasks are preferred over large PRs with many tasks.

**Review by swarooprm — COMMENTED** [review]
Seems like you have exhausted all possibilities to create tasks. 

Some suggestions:
1. Task 230: "In this task, you're a question, along with three passages, 1, 2, and 3. Your job is to determine which passage can be used to answer the question by searching for further information using terms from the passage. Inidcate your choice as 1, 2, or 3.", there are grammatical mistakes here, it should be "you are given a question", and "Indicate".
2. Task 231: Typo- "Inidcate"
3. Task 232: "which has extra information available on certain terms mentioned in it"- where is the extra information available? Some explanations are not clear e.g. "The passage talks about both Francis and John Ford, so more details on both are needed to answer the question." I am not sure how reliable annotations in this task is? Please verify the automatic method you used to create data.
4. Task 233: not sure how it is different from Task232
5. Task234: looks good.
6. Task 235: looks good. One question: Is it always true that the question uses both context and link information to answer?
7. 236-238: Looks good, some places may need rephrasing. Again make sure that, the question or answer involves both context and link.

**Comment by aarunku5** [comment]
232- Clarified definition to specify that proper nouns in the passage are the extra info terms. Verified data creation- multiple links are needed when answering questions that require math and/or refer to multiple entities in the passage for some kind of comparison.
233- Some questions have no relevant links with answers present in the passage, 233 identifies those links. 232 checks if more than 1 link is needed, or if 1 suffices. 232 also omits questions where there is no answer in the links.
235-238- Yes both context and link are needed to answer

**Comment by swarooprm** [comment]
Looks good to me. Thanks @aarunku5

**Comment by danyaljj** [comment]
@yeganehkordi wondering if you can also review this PR? It's a large PR and I think it would benefit from a second eye.

**Comment by yeganehkordi** [comment]
Sure! I'll review it now.

**Review by yeganehkordi — COMMENTED** [review]
Thanks! Some comments:
- " On D Day," in the first example, shouldn't be "On a day"?
- I suggest using json.dumps(obj, ensure_ascii=False) to make Latin letters in JSON more human readable.

- Task 232-233: Since you said "Indicate your choice as `a` for Yes or `b` for No." in the definition, I think you can drop "Choices: a. Yes b. No." from the instances.

- Task 234: Output in some instances isn't a sentence. (e.g, "In 586") I think you should clarify them in the definition.
- I can't understand the difference between task 235 and task 236 and between task 237 and task 238 clearly. Can you elaborate more about them in the definition?
-  Task 237-238: As some of the question are not answerable, please explain about them in the definition.

**Comment by aarunku5** [comment]
Thanks!

- D-Day here is the name of the WW2 Normandy landings operations.
- Update all tasks to make  Latin letters readable.
- Updated tasks 232, 233.
- Have eliminated instances with incomplete sentence answers in 234.
- 235, 236 use a single sentence+link and passage+link respectively as the context information. The same goes for 237, 238. 
- 237, 238- have updated the definition to include "none" answer specifications.

**Comment by yeganehkordi** [comment]
Thanks!
Still, some outputs in task 234 are vague for me. For example, in line 104: `Preston in a 2–0 victory over Huddersfield Town in the`
Other tasks look good to me.

**Comment by aarunku5** [comment]
Thanks! I've fixed 234's outputs.

**Comment by yeganehkordi** [comment]
Looks good to me, but the problem is we have a paragraph in some cases instead of a sentence (e.g., line 110). I  think you can simply change the `sentence` to `sentences` in the definition.

**Comment by aarunku5** [comment]
Done 👍

**Comment by yeganehkordi** [comment]
Thanks! Looks good to me.

**Comment by danyaljj** [comment]
Thank you all!

**Pull request merged**
