### PR TITLE
categories & domains for task300-321

### PR DESCRIPTION
**Pull request by garyhlai**

### CODE REVIEW

**Comment by garyhlai** [comment]
@swarooprm this PR should be ready to merge now

**Comment by Palipoor** [comment]
A lot of the tasks' domains are "Captions -> Image Captions" but it seems to be unrelated to their domain. Or there's something here I don't understand.

**Comment by garyhlai** [comment]
> A lot of the tasks' domains are "Captions -> Image Captions" but it seems to be unrelated to their domain. Or there's something here I don't understand.

What do you mean? Note that in this PR I am merely replacing "Commonsense -> Captions -> Image Captions" with "Captions -> Image Captions" in response to discussion #458

**Review by swarooprm — APPROVED** [review]

**Comment by garyhlai** [comment]
@swarooprm I don't have write access so you need to merge it

**Pull request merged**
