### PR TITLE
Tasks 857-861

### PR DESCRIPTION
**Pull request by ashutosh1608**

### CODE REVIEW

**Comment by swarooprm** [comment]
@ashutosh1608, thank you for submitting. Task numbers till 856 are taken in the previous PR. So, I have renamed your PR to 857-861.

**Comment by ashutosh1608** [comment]
> @ashutosh1608, thank you for submitting. Task numbers till 856 are taken in the previous PR. So, I have renamed your PR to 857-861.

Oh okay, sorry I didn't see the previous PRs. Thanks for changing them.

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/125

**Comment by aarunku5** [comment]
Thanks. Can you rename your task numbers to match the PR? Here are comments for your current task numbers:

616,617:
Change the negative examples to be different texts from the positive examples

618:
Change the negative examples to be 3 unique examples. Also, make your definition more explicit- the question is directly answerable and unambiguous.
To clarify, in this task, the 4 objects at the end of the context are result of appending answer choices? 

619, 620:
Is the group actually necessary to answer any of the generated questions? Or is the context sufficient?

Also, make sure your definitions for all the tasks clearly specify the output format- is it a word/sentence/choice number etc.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
@ashutosh1608, can you address reviewer comments?

**Comment by swarooprm** [comment]
> @ashutosh1608, can you address reviewer comments?

A gentle reminder @ashutosh1608

**Comment by danyaljj** [comment]
Updated the task descriptions a bit. Merging upon green.

**Pull request merged**
