### PR TITLE
Task523

### PR DESCRIPTION
**Pull request by fsiar**

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi. Please change the task name to reflect the content and update thee README file.

**Comment by danyaljj** [comment]
@Palipoor wondering if you can check the updated PR? Thanks for your help in the reviewing process.

**Comment by Palipoor** [comment]
Hi,
1. Please change the languages in task metadata to two-character abbreviations like this:
`"Input_language": "en",
    "Output_language": "fa",
    "instruction_language": "en",`
2. Please add a link or a paper title under "Source"
3. Please update tasks/README.md to reflect your task. Check other PRs like #272.
4. I don't think we have something called "Mixed Examples" in the template, please remove it.
5. Your task should have instances. Please read the instructions carefully and update your submission accordingly.

**Comment by fsiar** [comment]
[image: image.gif]Hi
I update the 1 and 2(this was self-created for emotion understanding with
emotion label and is modified for this dataset ). I included the basic task
that I tried to fit for this set.
3- I am not sure if this task is fit for this set.  Let me update the
readme at the last phase.
4- Let me know how to apply this one: Given a tweet, classify it into one
of 4 categories: Positive, Negative, Neutral, or Mixed.
5- The task instruction in the task repo is confusing for me. There is no
clear definition for task instance.
Thank you

  "examples":  
      "input": "It is christmas. I love snow. I got my first snow today.",
      "target_scores": {
        "Sad": 0,
        "Afraid": 0,
        "Happy": 1,
        "Angrey": 0

**Comment by Palipoor** [comment]
So I think there's a misunderstanding here. "Positive Examples" refer to examples with correct outputs and explanations on why that output is correct. "Negative Examples" refer to examples with incorrect outputs and an explanation(Check other accepted tasks for example). They don't refer to classification labels. 
Also, what do you mean by "5- The task instruction in the task repo"? Can you give a link?

**Comment by fsiar** [comment]
[image: image.gif]Hi,
Thank you. So I was wrong.
This one:(5)
https://github.com/allenai/natural-instructions-expansion

So I think this task is not suitable for this benchmark.
I will try to check if I can change the task, or close the PR.
Thank you.







[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
09/25/21,
11:46:41 PM

**Comment by Palipoor** [comment]
Please check out the tasks in `tasks/` folder to find good examples. Like [this one](https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task248_dream_classification.json) that is a multi-class classification.

**Pull request closed without merging**
