### PR TITLE
Task 1626 - 1631

### PR DESCRIPTION
**Pull request by AnshitaSinghBais**

### CODE REVIEW

**Comment by aarunku5** [comment]
I've renamed this PR. Can you rename your files and update your readme accordingly?

**Comment by aarunku5** [comment]
Also, make sure you include the following fields:

Input_language, Output_language, Instruction_language
(see task_003 for the format)

**Comment by AnshitaSinghBais** [comment]
I am confused as what conflict is the branch facing? @aarunku5

**Comment by aarunku5** [comment]
Thanks! I've resolved the merge conflict. Also made some updates to fix the task format, and included language details.

Can you rename 1630 to: task1630_openpi_classification.json and also update the readme? There should be no uppercase letters in the task name or the tests fail.

**Review by aarunku5 — APPROVED** [review]

**Comment by aarunku5** [comment]
LGTM

**Pull request merged**
