### PR TITLE
Tasks 766-769 craigslist_bargains, qed

### PR DESCRIPTION
**Pull request by vimcity**

### CODE REVIEW

**Comment by swarooprm** [comment]
Please rename your tasks to 766-769 as task names till 768 are used in the previous PR.

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/97

**Comment by vimcity** [comment]
Fixed task numbers

**Comment by aarunku5** [comment]
Thanks, just one correction- in 767, there are couple of grammatical errors in the definition, fix those and resubmit.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by vimcity** [comment]
@aarunku5 Fixed.

@danyaljj My 'Categories' fields seem to follow the taxonomy.

**Comment by danyaljj** [comment]
@ritvik7 the tests are failing at this point since all the task files must have language tags:
```
  "Input_language": ["English"], 
  "Output_language": ["English"], 
  "Instruction_language": ["English"], 
```

**Review by swarooprm — APPROVED** [review]

**Pull request merged**
