### PR TITLE
Tasks 1450-1500: Assigning categories, domains and addressing feedback 

### PR DESCRIPTION
**Pull request by yeganehkordi**

### CODE REVIEW

**Comment by swarooprm** [comment]
task categories and domains look good to get merged @danyaljj

**Comment by danyaljj** [comment]
Looks like the PR is a "draft"?

**Comment by yeganehkordi** [comment]
Yeah, I want to modify the gene/chemical extraction tasks. I've noticed that the definition mentioned that the task is to list the items, but all the outputs have one item. I'll fix them soon.

**Comment by swarooprm** [comment]
We can merge this PR @danyaljj  if you are happy with feedback addressing.

**Review by swarooprm — APPROVED** [review]

**Pull request merged**
