### PR TITLE
Tasks 510-511: Reddit Tifu dataset

### PR DESCRIPTION
**Pull request by shailaja183**
1. task510_reddit_tifu_title_summarization.json | Given the text of a social media post, generate a title summarizing the post | Summarization 
2. task511_reddit_tifu_long_text_summarization.json | Given the text of a social media post, generate a short summary the post | Summarization

### CODE REVIEW

**Comment by Palipoor** [comment]
Looks good to me!

**Comment by danyaljj** [comment]
@SavanDoshi wondering if you can review the PR too? It's a relatively large PR and could benefit from an additional pair of eyes.

**Comment by danyaljj** [comment]
Why are the `torque` tasks part of this PR? 
Otherwise the task looks good!

**Comment by shailaja183** [comment]
Removed torque tasks, hopefully can be merged now.

**Pull request merged**
