### PR TITLE
Tasks600-606

### PR DESCRIPTION
**Pull request by Nikhitha0911**

### CODE REVIEW

**Comment by swarooprm** [comment]
@Nikhitha0911, thank you for your submission. I have renamed your PR to 600-606 since task numbers till 599 were taken in the previous PR. Also can you please add your file names in readme so that tests pass?

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/37

**Comment by danyaljj** [comment]
@Nikhitha0911 thanks for the PR! Looks like the tests are failing because some files are uppercase and probably the exact file names are not included in the readme file.

**Comment by danyaljj** [comment]
- `task600_qangaroo_answer_generation`: In the examples, should they be "Question: **What** interacts_with DB00773?" 
 - `task603_wikitext-103_fill_in_the_blank`: I think you can drop this: "A sentence from the passage will be picked as the question with a blank. "
 - `task606_qangaroo_classification`: "Indicate your choice with the number of the option you choose." -> "Indicate the answer with the number associated with the answer entity".

**Comment by danyaljj** [comment]
@swarooprm what do you think about these tasks?

**Comment by swarooprm** [comment]
@Nikhitha0911, these tasks look good. But I have some comments:
- In certain cases, the length of the input is too large and will be more than the 2048 token limit that a model such as GPT3 can take. This happens in tasks from qangaroo dataset as well as the wikitext dataset. I was wondering if you can filter instances that have relatively lower lengths. Also, in examples use the ones with smaller input. 
- In case of qangaroo dataset, question generation task can be created (similar to task001 in this repo)
- neen to english translation conversion task can be created. Also, the dataset contains other language translations which you can add as new tasks if you want.

Let me know your thoughts regarding these.

**Comment by danyaljj** [comment]
For the qangaroo task, honestly, I am in favor of dropping it, if we can't reformulate in a way that is not understandable to humans.

**Comment by danyaljj** [comment]
@Nikhitha0911 could you drop the tasks that are difficult to read (e.g., Qangroo) so that we can move this PR?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
> @Nikhitha0911, these tasks look good. But I have some comments:
> 
> * In certain cases, the length of the input is too large and will be more than the 2048 token limit that a model such as GPT3 can take. This happens in tasks from qangaroo dataset as well as the wikitext dataset. I was wondering if you can filter instances that have relatively lower lengths. Also, in examples use the ones with smaller input.
> * In case of qangaroo dataset, question generation task can be created (similar to task001 in this repo)
> * neen to english translation conversion task can be created. Also, the dataset contains other language translations which you can add as new tasks if you want.
> 
> Let me know your thoughts regarding these.

@Nikhitha0911, any update?

**Comment by Nikhitha0911** [comment]
> > @Nikhitha0911, these tasks look good. But I have some comments:
> > 
> > * In certain cases, the length of the input is too large and will be more than the 2048 token limit that a model such as GPT3 can take. This happens in tasks from qangaroo dataset as well as the wikitext dataset. I was wondering if you can filter instances that have relatively lower lengths. Also, in examples use the ones with smaller input.
> > * In case of qangaroo dataset, question generation task can be created (similar to task001 in this repo)
> > * neen to english translation conversion task can be created. Also, the dataset contains other language translations which you can add as new tasks if you want.
> > 
> > Let me know your thoughts regarding these.
> 
> @Nikhitha0911, any update?

I am dropping Qangaroo dataset task

**Review by swarooprm — APPROVED** [review]

**Pull request merged**
