### PR TITLE
Task 669-671: AmbigQA

### PR DESCRIPTION
**Pull request by Mirzyaaliii**
task669_ambigqa_answer_generation -> Given an open-domain, provide an answer for that question.
task670_ambigqa_question_generation -> Given an ambiguous question, return all possible questions which clarify the given question.
task671_ambigqa_text_generation -> Given an ambiguous question, provide one clarifying question and answer for the generated question.

Please review.

### CODE REVIEW

**Comment by swarooprm** [comment]
@nrjvarshney, wondering if you can help review this tasks?

**Comment by swarooprm** [comment]
@yeganehkordi, wondering if you can help review these tasks.

**Review by yeganehkordi — COMMENTED** [review]
Thanks! Looks good to me.
I think it's better to say, `Your task is to return a question` in task 670. All the possible questions might be unclear. Although this task has many correct answers here, we only need one answer, and we can have all the possible answers in output.

**Comment by swarooprm** [comment]
@Mirzyaaliii, these tasks look good to me as well. I agree with @yeganehkordi's comment: we should ask the model to generate only one question (instead of all possible questions). Just that minor fix and this PR is good to go!

**Comment by Mirzyaaliii** [comment]
Thanks for the comments!!

Changes are done as per suggestion.

**Comment by danyaljj** [comment]
Thanks! Sorted several lines in the tasks readme and merging the PR after the tests turn green.

**Pull request merged**
