### PR TITLE
Merge all kpa tasks

### PR DESCRIPTION
**Pull request by Palipoor**
Due to the discussion under #626

### CODE REVIEW

**Comment by yeganehkordi** [comment]
Thanks! I think we don't need the topic in the input.
Also, I was thinking if we can keep them and evaluate generalization over domains using these kinds of tasks.

**Comment by danyaljj** [comment]
Sorry I missed the PR. Just seeing it now.

**Comment by yizhongw** [comment]
I think we certainly don't want to have different topics as separate tasks (they are too many!). For domain generalization evaluation, we probably don't want to evaluate using just one task but on different domains. So, I think merging all the topics into one task is fine.

On whether to put topic in the input, I think either way is fine. I vote for keeping them, since this information is provided in the original task and we probably don't want to make the assumption that this information is not needed.

**Comment by danyaljj** [comment]
@yeganehkordi do you have any strong opinions regarding @yizhongw 's comment above?

**Comment by yeganehkordi** [comment]
> @yeganehkordi do you have any strong opinions regarding @yizhongw 's comment above?

No, it sounds good! My opinion is not strong and I'm fine if we decide to merge them and keep topics.

**Pull request merged**
