### PR TITLE
Tasks910-916: Bianet and Imppres

### PR DESCRIPTION
**Pull request by mirror3**

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks @mirror3 for the PR! Can you please merge your branch with our main branch? (so that the latest changes are reflected). 

@gkaramanolakis wondering if you can review this PR?

**Comment by gkaramanolakis** [comment]
Hi @mirror3, below are some comments: 

1. Pls make sure to merge your branch with the main branch and make task names in the README consistent with the JSON filenames.
2. In task910_bianet_classification.json, the "Negative Examples" field should not have instances with "No" label (which is the right label) but instead should be instances that have been assigned a wrong label. For example, it should be one instance for which the assigned label is "Yes" while it should be "No" (and the reverse). 
3. Please write more descriptive task names in README to differentiate them. For example, instead of having task793_bianet_classification and task795_bianet_classification, you could have task793_bianet_correct_translation_classification and task795_bianet_language_classification. Also, task798_naturalLanguageInference should be marked as a classification task, e.g., task798_imppres_nli_classification. (Of course, task numbers should be fixed.)
4. Please improve the descriptions of the following tasks to make sure they're syntactically and grammatically correct and capitalize language names. Here are suggestions for new descriptions: 
  * "Classifying whether two sentences are translations of each other"
  * "Generating a translation of an English sentence into Kurdish"
  * "Classifying a given sentence into English or Kurdish"
  * "Generating a translation of a Kurdish sentence into Turkish"
  * "Given a premise and a hypothesis, determine if the premise-to-hypothesis entailment is positive, negative or neutral"
 5. task915_imppres_longTextGeneration.json looks too artificial and somewhat weird: there are many examples for which, in contrast to the task definition, it looks like the generated hypothesis is not derived from the premise. Consider, for example, the following instance from the file: "input" (premise): "The five waiters that approached Paul depart.", "output" (hypothesis): "There are exactly five waiters that approached Paul.". The output should not necessarily be derived from the input. Also, all examples look very similar to each other to the extent that a simple rule-based approach could achieve great performance on this task. If you don't have ideas on how to make this specific task more natural, you could remove it. 
  
Thanks!

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
@mirror3, can you address reviewer comments?

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/80

**Pull request merged**
