### PR TITLE
Task 1166-1167 PennTreeBank and Brown Corpus Parts of Speech Tags

### PR DESCRIPTION
**Pull request by mishra-sid**
Defined two Parts of Speech tagging tasks using [Penn Treebank](https://catalog.ldc.upenn.edu/LDC99T42) and [Brown Corpus](http://korpus.uib.no/icame/brown/bcm.html)

Similar structure as in #279.  Task originally suggested in #94 .

### CODE REVIEW

**Comment by danyaljj** [comment]
@davidstap wondering if you can review this PR?

**Comment by mishra-sid** [comment]
@davidstap If it helps, the reviews from the same task ( PoS Tagging ) on another dataset are available in #279 .

**Comment by davidstap** [comment]
LGTM! These POS tasks follow the same structure as #279, including improvements such as the {{ ... }} notation (instead of position) and clear explanations for the abbreviated POS tags. I think this can be merged.

Some small issues that could optionally be improved:
- Both tasks have 7 positive examples and 1 negative example. Maybe a more balanced spread is better?
- The definition for this task is quite long (326 words), this might be problematic? OTOH I don't know how to make this description shorter without making it worse.

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by aarunku5** [comment]
> Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

@mishra-sid can you please update the PR accordingly?

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
