### PR TITLE
task108 abuse detection

### PR DESCRIPTION
**Pull request by Maitreyapatel**
Added new task 111 for abuse detection. Please review it.

### CODE REVIEW

**Comment by swarooprm** [comment]
@Maitreyapatel , thanks for creating PR. can you name your task as task108, since the latest task we had is task107?

Some other feedbacks:

- Create at least 1 or 2 negative examples, the field should not be empty.
- \u2018identity\u2019 should be identity. Make the definition more readable.
- Since Things to Avoid, Emphasis etc. are empty, just drop them instead of adding them with empty values.

**Comment by Maitreyapatel** [comment]
I have made the required changes. Please review it once again.

**Review by swarooprm — COMMENTED** [review]
Looks good! Thanks! One question: what is the source dataset?
Usually we add source dataset name and task category name ('Classification') while naming JSON files. E.g. task001_quoref_question_generation.json here source dataset is quoref and task category is 'question generation.

**Comment by Maitreyapatel** [comment]
The dataset is CAD: the Contextual Abuse Dataset from [https://www.aclweb.org/anthology/2021.naacl-main.182/](https://www.aclweb.org/anthology/2021.naacl-main.182/)

Which one of the following name is more suitable?
1) task108_cad_classification
2) task108_ContextualAbuseDetection_classification

**Comment by swarooprm** [comment]
task108_ContextualAbuseDetection_classification.
Make sure to also register in the spreadsheet, so that no one else works on the same dataset.

**Comment by Maitreyapatel** [comment]
Renamed the task file name. Also, can you point me to the spreadsheet? Thanks!

**Comment by swarooprm** [comment]
Thanks! I shared the spreadsheet with patel.maitreya57@gmail.com.

**Review by swarooprm — APPROVED** [review]

**Comment by danyaljj** [comment]
Reformulate the definition so that it's easier to read:
```
Read the given text and if the the context is Identity Directed Abuse (e.g., Content which contains a negative statement made against an identity. An identity is a social category that relates to a fundamental aspect of individuals community, socio-demographics, position or self-representation) or Affiliation Directed Abuse (e.g., Content which express negativity against an affiliation. We define affiliation as a (more or less) voluntary association with a collective. Affiliations include but are not limited to: memberships (e.g. Trade unions), party memberships (e.g. Republicans), political affiliations (e.g. Right-wing people) and occupations (e.g. Doctors).) or Person Directed Abuse (e.g., Content which directs negativity against an identifiable person, who is either part of the conversation thread or is named. Person-directed abuse includes serious character based attacks, such as accusing the person of lying, as well as aggression, insults and menacing language.) or Counter Speech (e.g., Content which challenges, condemns or calls out the abusive language of others.), indicate via \"yes\". Otherwise, response via \"no\"."
```

Start with what needs to be done, before getting into the weeds: 
```
Read the given text and if the content contains ..... (indicate via \"yes\") and otherwise .... 
[then define what "abuse classification" means:] 
We consider the context to be abusive, if it contains any of the following instances: (1) ... (2) ... 
```

**Comment by danyaljj** [comment]
After addressing the comments, please pull and merge with the main branch.

**Comment by swarooprm** [comment]
The issue of running test only for the modified task will be fixed in a different PR. Once this PR gets merged, https://github.com/allenai/natural-instructions-expansion/pull/41 will also pass.

**Comment by Maitreyapatel** [comment]
Got it! Thanks for the update.

**Comment by swarooprm** [comment]
Tests should pass now. Pull and merge with the main branch with your changes.

**Comment by danyaljj** [comment]
Thanks! Happy with this task! ✅ 
@swarooprm merge when you're happy.

**Pull request merged**
