### PR TITLE
adding tasks 145-150

### PR DESCRIPTION
**Pull request by liusiyi641**

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! Some thoughts: 

 - The output scales: Wondering if it makes to binarize the task to make it more well-defined. 
- "afs": add website and/or paper links 
 - `basedon` typo

**Comment by liusiyi641** [comment]
Thanks!

- I can certainly binarize the task if you think it can make it easier for the model to learn. But I'm not sure if that would make it more well-defined since they defined different levels of similarities and I'm simply borrowing their crowdsourcing templates. Besides, there's another paper (https://aclanthology.org/P19-1054.pdf) that I plan on adding. It has a dataset with similar definitions of similarities and also have four levels of similarities. Should I also binarize that dataset as well? And what about the argument quality task?

- Where can I add the paper link and in what format should it be? Should I add it in the "Source" entry in the .json file? I didn't find a good example in the first several sample tasks.

- Will do in the next pull request.

**Comment by liusiyi641** [comment]
Oh and here's the link to this afs dataset paper if you want to take a look. https://arxiv.org/pdf/1709.01887.pdf

**Comment by danyaljj** [comment]
>I can certainly binarize the task if you think it can make it easier for the model to learn. 

It's less about models and more about humans. How often do you think 10 average humans would agree that the label of a particular instance should be 4 (and not 3 or 5)?  My guess is that it won't be a high agreement ratio. 


> Should I add it in the "Source" entry in the .json file? I didn't find a good example in the first several sample tasks. 

Yup, `Source` is a string field. Just append it there.

**Comment by swarooprm** [comment]
@liusiyi641, could you answer reviewer comments so that we can approve your tasks?

**Comment by liusiyi641** [comment]
I just binarized all the six tasks and added the link to the paper in the source field. Let me know if there's anything more needed. Thanks!

**Comment by swarooprm** [comment]
@liusiyi641 , test is failing as there is overlap across positive examples and instances. Please resolve the issue.

**Comment by liusiyi641** [comment]
@swarooprm , I'm not sure why it didn't show me the errors locally when I ran the test script, but I did see the overlapped ones and filtered them out. Hopefully this time it works. Thanks.

**Review by swarooprm — APPROVED** [review]
Looks good! Merging.
Congrats on acceptance of your first task. Looking forward to more contributions.

**Comment by swarooprm** [comment]
@liusiyi641 Re: tests. There was merge conflict, make sure to git pull and sync with master so that tests run. Tests ran after I resolved the merge conflicts in the readme file.

**Pull request merged**
