### PR TITLE
Add tasks 171-175

### PR DESCRIPTION
**Pull request by Mehrad0711**
Adding more datasets from SPL project

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks! 

Now that we're adding more tasks for other languages, wondering if you can help us address #113, before we merge this PR.

**Comment by eshaanpathak** [comment]
Can't these MT tasks also go the other way around? For example, Spanish to English too.

**Comment by Mehrad0711** [comment]
Hi @danyaljj, 
Thanks for your suggestion! I added input/ output language tags for the SPL tasks.
Please let me know if there's anything else.

**Comment by Mehrad0711** [comment]
> Can't these MT tasks also go the other way around? For example, Spanish to English too.

Yes. The sentences are actually aligned between languages so you can go from any source language to any target language within the 11 languages supported. There are 2 domains in SPL so there will be a total of 220 tasks. After adding all tasks with English sources, I can continue adding other directions if the main authors think this is indeed a good addition.

CC: @danyaljj, @swarooprm

**Comment by danyaljj** [comment]
Looks good to me, thanks!


> After adding all tasks with English sources, I can continue adding other directions if the main authors think this is indeed a good addition. 

Sure we would be happy to see them in future PRs,!

**Review by swarooprm — COMMENTED** [review]
Looks good!
[minor comment]: Define "special placeholders" like you have defined other terms.

**Review by swarooprm — APPROVED** [review]
Merging!
Looking forward to more such tasks in reverse and other languages as you have mentioned in your comment.

**Comment by swarooprm** [comment]
Updated Readme to resolve merge conflicts.

**Pull request merged**
