### PR TITLE
Task 497-509 : Scruples-Anecdote-Dilemmas-datasets

### PR DESCRIPTION
**Pull request by kuntalkumarpal**

### CODE REVIEW

**Comment by amirrezamirzaei** [comment]
hi @kuntalkumarpal,
we already have a few tasks made with scruples dataset.  please make sure there aren't any duplicates in your tasks.

**Comment by swarooprm** [comment]
@amirrezamirzaei , wondering if you can review these tasks since these are similar to your tasks on the same dataset?

**Comment by amirrezamirzaei** [comment]
- task 497 : we already have this task (task 282)
- task 498 : typo in `ccategories ` in the definition.  please make sure the labels are balanced otherwise looks good.
- task 499 : we already have this task (task 224)
- task 500 : I'm not very sure about this task. the definition is `identify the action phrases` which isn't really what were doing.
- task 501 : isn't this the same as task 497? we are answering a question that only has two answers which is essentially a binary classification task.
- task 502 : looks good.
- task 503 : looks good. but why not make it into a classification task with (answerable and not answerable class)
- task 504&505 : we already have this task (task 106). although one is choosing less ethical and another one is choosing the ethical task I think both of them are the same task just with different wording. the one wein task 106 is choosing the less ethical choice.
- task 506&507&509 : drop these tasks. we have no way of generating the specific output from the input.
- task 508 : looks good

**Comment by danyaljj** [comment]
@kuntalkumarpal any updates on this thread?

**Comment by kuntalkumarpal** [comment]
> @kuntalkumarpal any updates on this thread?

@danyaljj Yes working on it. Will update by tonight.

**Comment by kuntalkumarpal** [comment]
> * task 497 : we already have this task (task 282)
> * task 498 : typo in `ccategories ` in the definition.  please make sure the labels are balanced otherwise looks good.
> * task 499 : we already have this task (task 224)
> * task 500 : I'm not very sure about this task. the definition is `identify the action phrases` which isn't really what were doing.
> * task 501 : isn't this the same as task 497? we are answering a question that only has two answers which is essentially a binary classification task.
> * task 502 : looks good.
> * task 503 : looks good. but why not make it into a classification task with (answerable and not answerable class)
> * task 504&505 : we already have this task (task 106). although one is choosing less ethical and another one is choosing the ethical task I think both of them are the same task just with different wording. the one wein task 106 is choosing the less ethical choice.
> * task 506&507&509 : drop these tasks. we have no way of generating the specific output from the input.
> * task 508 : looks good

@amirrezamirzaei Thanks for your comments. 

- task 497 : Removed
- task 498 : typo fixed. Labels balanced
- task 499 : Removed
- task 500 : I have rephrased the task description
- task 501 : I have rephrased the task. Through this task, I am mainly hoping to test whether model is able understand a negative claim about the type of the paragraph which is not being tested in the classification task. Here also negative and positive samples have been balanced
- task 503 : Thanks for the suggestion. I have modified it into a classification task with (answerable and not answerable class)
- task 504&505 : Yes one is less ethical and another is more ethical identification. But I have removed them since they have same objective
- task 506&507&509 : Just want to understand before removal. Do you mean if the model generates some less ethical / more ethical action than the given one, there is no way for us to evaluate whether it is correct or incorrect ?

**Comment by amirrezamirzaei** [comment]
thank you for the changes
regarding task 506&507&509: yes that's what I meant, let me know if you think I'm wrong.

**Comment by kuntalkumarpal** [comment]
> thank you for the changes regarding task 506&507&509: yes that's what I meant, let me know if you think I'm wrong.


Got it. Removed

**Comment by swarooprm** [comment]
> > thank you for the changes regarding task 506&507&509: yes that's what I meant, let me know if you think I'm wrong.
> 
> Got it. Removed

@amirrezamirzaei, do you have any other feedback or are you happy with the PR?

**Comment by amirrezamirzaei** [comment]
sorry for the late review. thank you for the changes everything looks good just a few typos and grammar errors.
- task 498 : in the second positive example `screemed ` should be `screaming` and `said ` should be `saying`.
- task 500 : in the first positive example type in `desrie `. also `not wanting give` should be `not wanting to give`.
- task 501 : In the first negative example : typo in  `beinng `. also `about an event` should be `an event`
- task 502 : same as 498
- task 503 : you didn't change the instances label. also can you please change this task definition a bit its a bit weird having a question in the definition. maybe change it to something like `Given a real-life annecdote of a complex ethical situation, judge whether or not a specific someone is at wrong here. answer ..'not answerable' if more information..`

**Comment by kuntalkumarpal** [comment]
> sorry for the late review. thank you for the changes everything looks good just a few typos and grammar errors.
> 
> * task 498 : in the second positive example `screemed ` should be `screaming` and `said ` should be `saying`.
> * task 500 : in the first positive example type in `desrie `. also `not wanting give` should be `not wanting to give`.
> * task 501 : In the first negative example : typo in  `beinng `. also `about an event` should be `an event`
> * task 502 : same as 498
> * task 503 : you didn't change the instances label. also can you please change this task definition a bit its a bit weird having a question in the definition. maybe change it to something like `Given a real-life annecdote of a complex ethical situation, judge whether or not a specific someone is at wrong here. answer ..'not answerable' if more information..`

Thanks for your detailed comments. I have fixed these. Please have a look

**Comment by amirrezamirzaei** [comment]
thank you, you forgot to fix `screemed` typo in 498 and 502.

**Comment by amirrezamirzaei** [comment]
@swarooprm LGTM! I'm still not sure about the verification tasks(501&502) but the tasks themselves look good.

**Comment by danyaljj** [comment]
* "verify if the claim about the type of the post is true or not" --> it is a bit difficult to see where/what is the claim. How can we make it more clear?

**Comment by kuntalkumarpal** [comment]
> * "verify if the claim about the type of the post is true or not" --> it is a bit difficult to see where/what is the claim. How can we make it more clear?

To make it more explicit, I can add a prefix and change the format like below for each instance
"CLAIM : The following post is HYPOTHETICAL. POST : ......."

and change the definition to 
"Given a real-life anecdote of a complex ethical situation and an associated claim about its type, verify if the claim is true or not. Say 'yes' if it is true otherwise say 'no'"

**Comment by danyaljj** [comment]
> > * "verify if the claim about the type of the post is true or not" --> it is a bit difficult to see where/what is the claim. How can we make it more clear?
> 
> To make it more explicit, I can add a prefix and change the format like below for each instance "CLAIM : The following post is HYPOTHETICAL. POST : ......."
> 

If it is possible to add such prefixes consistently, I think that could improve the readability.

**Comment by kuntalkumarpal** [comment]
Updated the Prefix. Definition Updated

**Comment by danyaljj** [comment]
Thanks!

**Pull request merged**
