### PR TITLE
Task 820-826: proto_qa & peixian/rtGender

### PR DESCRIPTION
**Pull request by Mda233**
From HW2: Mihir: Task 505-511: proto_qa & peixian/rtGender #40
Contributor: DongAo Ma

### CODE REVIEW

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/40

**Comment by danyaljj** [comment]
@mattf1n could you review this PR?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by danyaljj** [comment]
- 822: classifying a text into gender sounds like a problematic thing to teach to a machine. Dropping it. 
- 824 & 825: unclear definitions. Someone's gotta apply major improvements before we can merge them in.

**Pull request merged**
