### PR TITLE
Update Categories and Domains for Task161-180

### PR DESCRIPTION
**Pull request by garyhlai**

### CODE REVIEW

**Comment by danyaljj** [comment]
Let's resolve the conflicts and get this in, before it further diverges.

**Comment by garyhlai** [comment]
@swarooprm let me know when you can meet so we can discuss and merge this PR as well as task 181-199

**Comment by Palipoor** [comment]
The problem here seems to be that you still have files named *_spl_* but according to #477 they have all been renamed to *_alt_*. @ghlai9665

**Comment by garyhlai** [comment]
thank you @Palipoor . @swarooprm this PR is ready to merge now as per discussed today

**Review by swarooprm — APPROVED** [review]

**Pull request merged**
