### PR TITLE
add tasks 402 and 404 

### PR DESCRIPTION
**Pull request by Palipoor**
@eshaanpathak Sorry, I created this again.

### CODE REVIEW

**Comment by danyaljj** [comment]
Replaces PR #219 
@eshaanpathak see if you're happy with this PR?

**Comment by eshaanpathak** [comment]
`task402_grailqa_paraphrase_generation.json`:
1. Can you add another positive example? They may add in the change in #216 to have 3 positive examples and 2 negative examples.

`task404_paraphrase_validation.json`:
1. In the definition and also the explanation of the first positive example, it should be "paraphrase of" instead of "paraphrase for".
2. Can you add "grailqa" to the filename too to make it `task404_grailqa_paraphrase_validation.json`?
3. Can you add another positive example and another negative example? They may add in the change in #216 to have 3 positive examples and 2 negative examples.

**Comment by Palipoor** [comment]
done!

**Comment by eshaanpathak** [comment]
`task404_grailqa_paraphrase_validation.json`:
1. In all of the examples and instances, there's a typo with "quetion" in the inputs.
2. Can you include a second negative example?

**Comment by Palipoor** [comment]
done! thanks.

**Comment by eshaanpathak** [comment]
`task404_paraphrase_validation.json`:
1. In the definition, it should be "paraphrase of" instead of "paraphrase for".
2. In the explanation of the first positive example, it should say "good paraphrase of the first question and they". In other words, "good paraphrase for" should instead be "good paraphrase of" and "first questions" should instead be "first question".

**Comment by swarooprm** [comment]
@Palipoor, can you fix the minor suggestions so that we can go ahead with merging?

**Review by swarooprm — APPROVED** [review]
LGTM!
I assume labels are not skewed in the classification task. Please verify and fix in your next PR if they are skewed.

**Comment by swarooprm** [comment]
Also, see you might be able to create other tasks such as answer generation from the same GrailQA dataset.

**Pull request merged**
