### PR TITLE
Task 274: overruling

### PR DESCRIPTION
**Pull request by yeganehkordi**
Based on: https://reglab.stanford.edu/data/the-overruling-dataset-a-benchmark-for-detecting-legal-decisions-that-have-been-overruled/

### CODE REVIEW

**Review by Palipoor — COMMENTED** [review]
Looks good to me!

**Comment by yeganehkordi** [comment]
Thanks!

**Comment by yeganehkordi** [comment]
Thanks, I added another negative example.

**Review by Maitreyapatel — APPROVED** [review]
Looks good. Thanks!

**Review by swarooprm — APPROVED** [review]
I like this task as it's sort of different than the type of tasks we have. More such tasks are encouraged, also may be we should have a new task category.

Merging! Consider fixing in your next PR if you plan to add a new task category.

**Pull request merged**
