### PR TITLE
Fixing several outstanding issues 

### PR DESCRIPTION
**Pull request by danyaljj**
- check if there are any repeated examples #25

### CODE REVIEW

**Comment by danyaljj** [comment]
Until we address the issues in issue #39 this is going to fail.

**Comment by swarooprm** [comment]
All issues in #39 seems to be addressed now
.

**Comment by danyaljj** [comment]
Sounds good! Looks like the added tests are passing now.  
 @swarooprm give it a review and merge, if it looks good.

**Review by swarooprm — APPROVED** [review]
looks good

**Pull request merged**
