### PR TITLE
Tasks 1612-1625

### PR DESCRIPTION
**Pull request by aarunku5**

### CODE REVIEW

**Comment by aarunku5** [comment]
1612-1618
1619-1625

**Comment by aarunku5** [comment]
Have checked the instances, LGTM

**Comment by aarunku5** [comment]
Reviews:
https://github.com/swarooprm/CSE576HW/pull/82
https://github.com/swarooprm/CSE576HW/pull/54

**Review by swarooprm — APPROVED** [review]

**Comment by swarooprm** [comment]
LGTM

**Pull request merged**
